### ISSUE TITLE
timeframe='today 7-d', doesn't seem to work

### ISSUE THREAD

**Issue by samarv** [GeneralMills/pytrends#100]
Hey Man, Thanks a lot for this new update. It's quite remarkable, what you are doing for the open source community. Thank you.

`pytrends = pytrend.build_payload(kw_list = ['pizza'], cat=0, timeframe='today 5-y', geo='', gprop='')
x = pytrend.interest_over_time()`

This Works, wonderfully!

`pytrends = pytrend.build_payload(kw_list = ['pizza'], cat=0, timeframe='today 7-d', geo='', gprop='')`

This gives an error, as follows

`JSONDecodeError: Expecting value: line 1 column 1 (char 0)
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-142-30948d8285fe> in <module>()
----> 1 pytrends = pytrend.build_payload(kw_list = ['pizza'], cat=0, timeframe='today 7-d', geo='', gprop='')
/usr/local/lib/python3.5/site-packages/pytrends/request.py in build_payload(self, kw_list, cat, timeframe, geo, gprop)
     77         token_payload['req'] = json.dumps(token_payload['req'])
     78         # get tokens
---> 79         self._tokens(token_payload)
     80         return
     81 
/usr/local/lib/python3.5/site-packages/pytrends/request.py in _tokens(self, token_payload)
     90         # strip off garbage characters that break json parser
     91         widget_json = req.text[4:]
---> 92         widget_dict = json.loads(widget_json)['widgets']
     93         # order of the json matters...
     94         first_region_token = True
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    317             parse_int is None and parse_float is None and
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:
    321         cls = JSONDecoder
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>  
ClearInterruptRestart
/Users/samar/python/pythonwd`

**Comment by dreyco676** [comment]
I'll take a look into it.

**Comment by dreyco676** [comment]
Try `now 7-d`

**Comment by dreyco676** [comment]
Updated documentation.

**Comment by samarv** [comment]
Thanks @dreyco676 , It's working !
