### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by timothy2799** [GeneralMills/pytrends#103]
Thank you very much for the update! My question may be stupid since I'm new to python.

I run your example and it quietly stops. I don't know how to extract the output. Besides, I don't receive any notice of Google Login and the program runs as usual even I type wrong login ID and password. It seems that the program has not logged in my Google account.

**Comment by dreyco676** [comment]
Hmm I wonder if Google is not sending you notifications about it.

Most things like `interest_over_time_df ` in the example are `pandas.DataFrame`. If you wish you view them you can just write `print(interest_over_time_df)` or if you wish to save them off to a file you can use `pandas.to_csv()`

Can you try to print the output and let me know if it returns anything?

Check out this 10min to Pandas Guide.
http://pandas.pydata.org/pandas-docs/stable/10min.html

**Comment by timothy2799** [comment]
Thank you for your response! I can now extract the data and save it to csv. Still, I was using 'xxx@gmail.com' and 'xxx' as password. No warning or error pops up.

**Comment by dreyco676** [comment]
Thanks for the heads up.
