### ISSUE TITLE
Two-Factor

### ISSUE THREAD

**Issue by polinarcissus** [GeneralMills/pytrends#104]
How does this handle two-factor authentication logins for Google?

**Comment by dreyco676** [comment]
I think you just need to approve the computer it's running from. I have two-factor auth on and I just get a text message saying that someone has tried to log in. I'm not 100% sure what is happening to be honest.

**Comment by dreyco676** [comment]
Let me know if this is an issue for you, it seems to work for me but honestly I can't remember if I had to do something special.

**Comment by polinarcissus** [comment]
I'll take another look. I just turned off two factor for a moment to play around. I think I need a place to enter the code google sends to me via text. But maybe I can authorize the computer another way previously to using the python package. 

Awesome tool. Thanks for being so responsive.
