### ISSUE TITLE
Anaconda can't see pytrends

### ISSUE THREAD

**Issue by avjgit** [GeneralMills/pytrends#105]
Windows 10; installed Python 3.6.0, installed pytrends, then installed Anaconda 4.3.0 (Python 3.6, 64-bit).
Anaconda does not see my pytrends package: error "No module named 'pytrends'".
Pytrends is installed - Python Shells accepts "from pytrends.request import TrendReq".

**Comment by avjgit** [comment]
`conda install` does not work either. Workaround - I copied packages manually, from python lib to Anaconda lib folder.

**Comment by dreyco676** [comment]
I'll take a look at the first issue, that shouldn't happen. For the second issue that's to be expected it isn't on conda, just PyPi. That said you should be able to point `conda install` at the zip of the repo and install it that way.

**Comment by dreyco676** [comment]
Added to conda via Binstar.
