### ISSUE TITLE
pytrends stopped working

### ISSUE THREAD

**Issue by shobute** [GeneralMills/pytrends#110]
The API is no longer able to pick up data for me. If I manually navigate to https://www.google.com/trends/trendsReport it is returning
```
This resource is no longer available.
If you require support please email trends-data-request@google.com
```

Is this due to a change on Google's side, or is there something wrong on my side?

**Comment by shobute** [comment]
Closing this issue, as I've investigated further and it seems to be a duplicate of #111.

**Comment by kritideep** [comment]
hey@ https://www.google.com/trends/api/widgetdata/comparedgeo    I think this api is not working properly when i am browsing this url the error comes out..   Region problem is the big problem it's only applicable thhis code onlly us regional.
