### ISSUE TITLE
json decoder error when i find out the interest_by_region_df = pytrend.interest_by_region()

### ISSUE THREAD

**Issue by kritideep** [GeneralMills/pytrends#112]

**Comment by samemon** [comment]
Same. I get No Json Object could be decoded.

**Comment by samemon** [comment]
So there is some problem with the timeframe. When I give an argument of the form : pytrend.build_payload(kw_list=['food'],geo='US') for interest by region, it works well. But if I add timeframe, it gives a json error mentioned above.

**Comment by samemon** [comment]
Actually if you give it a timeframe of the kind 'all_year' it does not work. But if its the date, it does. Some problem with the parsing I think.

**Comment by dreyco676** [comment]
@samemon weird it works only specifically for 'all_2008' and nothing else. Since you can get the same data by specifying dates I think the best course of action is just to remove that option.

**Comment by samemon** [comment]
I guess for now just try to use "2011-1-1 2011-12-31" instead of 'all_2011'

**Comment by dreyco676** [comment]
Updated the docs. I'd love feedback on how better capture errors since we are sending requests to a blackbox and when they fail we just get a 503 error from Google.
