### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by ns3115neha** [GeneralMills/pytrends#113]
I cant get to work these commands

# Get Google Hot Trends data
trending_searches_df = pytrend.trending_searches()

# Get Google Top Charts
top_charts_df = pytrend.top_charts(cid='actors', date=201611)

it gives me the same error,Howerver i can execute every other without error

**Comment by ernestk89** [comment]
Same here. Does anyone have an idea on how to overcome this?

**Comment by dreyco676** [comment]
You are welcome to take a look, I probably won't get a lot of free time to look at this until mid/late April. 

`print(req.text)` before the `json.loads()` in the source code will show you what the server is returning before parsing. Pair this with manual inspection of Google Trends using Fiddler 4 to see if something else should be changed.

**Comment by shawnhill** [comment]
@dreyco676 I forgot to associate the commit with this issue, but this PR fixes this bug. https://github.com/GeneralMills/pytrends/pull/118

**Comment by rmertens** [comment]
@dreyco676 @petersonnek any chance either of you could merge #118 ? it's a 2 line PR that un-breaks the library :)

**Comment by petersonnek** [comment]
Sorry for the delay. @dreyco676 normally takes care of this repo and he's out of the office. I've tested your change and merged your pull request.
