### ISSUE TITLE
gprop argument doesn't appear to be working

### ISSUE THREAD

**Issue by sgagnon** [GeneralMills/pytrends#117]
When I try to change the gprop argument, the output results don't appear to change. For instance, the following returns the same values regardless of gprop specified:

```
terms = ['Keystone Pipeline']
gprop_list = ['images', 'news', 'youtube', 'froogle', None, 'OTHER']

for gprop in gprop_list:
    pytrend.build_payload(kw_list=terms, timeframe=u'today 5-y', gprop=gprop)
    d = pytrend.interest_over_time().reset_index()

    if gprop:
        d['gprop'] = gprop
    else:
        d['gprop'] = 'web searches'

    dt = dt.append(d, ignore_index=True)
```

**Comment by dreyco676** [comment]
I can confirm this is an issue. My guess is there is some other key that needs to get set in the request. It will take me some time to dive in with Fiddler

**Comment by RiceeeChang** [comment]
You may change the gprop key in build_payload
