### ISSUE TITLE
Order of arguments not guaranteed

### ISSUE THREAD

**Issue by rubencart** [GeneralMills/pytrends#123]
In Google Trends you sometimes get a slightly different result if you switch the order of your search terms. Because pytrends uses a dictionary for token_payload in the build_payload function, the order in which you pass your arguments is not preserved...

I know the params argument to build a Request, from the Request package, takes a dict, but do you think there is a way to preserve the order anyway?

**Comment by dreyco676** [comment]
You could actually switch to Python 3.6 which now guarantees order of Dicts

https://stackoverflow.com/questions/39980323/dictionaries-are-ordered-in-python-3-6
