### ISSUE TITLE
Limit?

### ISSUE THREAD

**Issue by reedshaw** [GeneralMills/pytrends#129]
Hi! Thanks for this package -- am I hitting a request limit on my calls? Things seem to be working well until about 53 calls. Anyway to avoid that? trying to eventually get 600.

Thanks!

**Comment by josai** [comment]
Same here, I got about 40 calls per keyword search. Need to make about 300.

**Comment by dreyco676** [comment]
Have you trying using `time.sleep(5)` to space your requests? I was able to get 250+ doing that before I closed out the application.
