### ISSUE TITLE
code refactoring

### ISSUE THREAD

**Issue by bdewilde** [GeneralMills/pytrends#13]
Currently, all code is bundled in a single module, but it would probably help with developing, debugging, and usability to refactor it into separate modules for, say, connecting to Google, interfacing with user queries, and parsing raw CSV data. Modules for Py2/3 compatibility and a package-specific Exception class may also be useful.

I have a `refactor` branch going, but it may be a while before everything is ready for a PR. It currently breaks the API -- I renamed a couple classes and class methods, for clarity and adhering to community standards.

Do you think this is a good idea, @dreyco676? Any preferences or requests?

**Comment by dreyco676** [comment]
I was thinking the same thing. I was thinking Parsing, Requests, Exception and a Test module. I would also like to refactor the request to use Requests library for readability and maintainability.

**Comment by bdewilde** [comment]
I like the idea of a single user-facing module + class that calls out to other modules for connecting to Google, parsing data, throwing exceptions. Focus is on clarity and usability, whereas the other modules can be more... involved. And IIRC, tests usually go in their own directory, alongside the package directory.

HUGE :+1: to using `requests` instead of the low-level `urllib`, I was saving that suggestion for another day. ;)

Check out my refactor branch if you're curious... I'm very open to suggestions!

**Comment by dreyco676** [comment]
Also be sure to add your email to the setup.py. You are as much an author at this point as I am.

**Comment by bdewilde** [comment]
Ha! I did. Thanks for adding me, and putting up with all my issues and pull requests...

**Comment by dreyco676** [comment]
Is there any interest in completing this or can I close it out and manage a PR when you are ready?

**Comment by bdewilde** [comment]
Oh gosh, I really dropped the ball on this, huh? I _do_ want to finish it, just got sidetracked by a new job and new side projects. :grin: Since this already has PR #15 , I think it's good to close out this issue.

**Comment by dreyco676** [comment]
No worries we all get busy!
