### ISSUE TITLE
Fix support for using categories for search.

### ISSUE THREAD

**Issue by jeffreywu1996** [GeneralMills/pytrends#130]
In the API there is a option to define categories to narrow search results. 

In the API it states,
> Find available cateogies by inspecting the url when manually using Google Trends. The category starts after cat= and ends before the next &
> For example: "https://www.google.com/trends/explore#q=pizza&cat=71" 
> '71' is the category

However, google trends seems to have updated their URLs to a different format.
For example, if I want to search the term 'apple' and narrow the result to the company 'Apple' instead of the fruit, doing it manually on google trends will result in the url:
https://trends.google.com/trends/explore?q=%2Fm%2F0k8z

The 'cat=' field is no longer there in the url.

I was wondering if there is a way around this.

I am willing to help out if someone can point me to a direction on how to get it to work.

Thanks.

**Comment by dreyco676** [comment]
I think I understand the issue. I'll see if I can carve out some time to fix.

**Comment by dreyco676** [comment]
Hmm so it looks like you can add categories to queries but for some reason pytrends is getting back the same data regardless. This seems to be a similar issue to the #117.
