### ISSUE TITLE
AttributeError: 'TrendReq' object has no attribute 'interest_over_time_widget'

### ISSUE THREAD

**Issue by mosesmc52** [GeneralMills/pytrends#136]
Hi running pytrends within ipython notebook and I'm seeing this error. Any clue what is causing this error. 

Thanks,

![screen shot 2017-06-06 at 10 47 27 am](https://user-images.githubusercontent.com/5233925/26838419-a4a9e7dc-4aa5-11e7-9ac9-a0462f866a34.png)

**Comment by chandlertwilson** [comment]
I'm getting the same. No idea. Use this about 3 months ago and don't remember having the same problem. Hope it's not something systemic to G Trends.

**Comment by florianriche** [comment]
Just had the same issue and it appears that my widget titles were in french. 

As a consequence, If statements in the "`_tokens`" method were always False hence `interest_over_time_widget` is never assigned.
As a quick and dirty workaround, I  hardcoded the statements to test for the french titles version. 

Maybe your problem is related;

**Comment by JacquotLeHaricot** [comment]
has to do with the `hl` parameter. Another workaround would be to leave the `hl`parameter as is, and to adjust the `geo` parameter

**Comment by dreyco676** [comment]
@florianriche are you saying that the following code needs to be language specific?

```      for widget in widget_dict:
            if widget['title'] == 'Interest over time':
                self.interest_over_time_widget = widget
            if widget['title'] == 'Interest by region' and first_region_token:
                self.interest_by_region_widget = widget
                first_region_token = False
            if widget['title'] == 'Interest by subregion' and first_region_token:
                self.interest_by_region_widget = widget
                first_region_token = False
            # response for each term, put into a list
            if widget['title'] == 'Related queries':
                self.related_queries_widget_list.append(widget)```
