### ISSUE TITLE
Issue with subregions

### ISSUE THREAD

**Issue by franuentes** [GeneralMills/pytrends#145]
Hello,

I have the following code based off of the example that works with no issues:

```
from pytrends.request import TrendReq

google_username = "***@gmail.com"
google_password = "***"
path = ""

# Login to Google. Only need to run this once, the rest of requests will use the same session.
pytrend = TrendReq(google_username, google_password, hl='en-US', tz=360, custom_useragent='My Pytrends Script')

pytrend.build_payload(kw_list=['Pizza', 'Bagel'], geo='US', timeframe='all')

interest_by_region_df = pytrend.interest_by_region()
interest_over_time_df = pytrend.interest_over_time()
suggestions_dict = pytrend.suggestions(keyword='pizza')


print interest_by_region_df
print interest_over_time_df
print suggestions_dict

interest_by_region_df.to_csv('example.csv', date_format='%Y%m%d')
interest_over_time_df.to_csv('example2.csv', date_format='%Y%m%d')
```

However, once I specify a state or subregion, such as changing geo to 'US-AL' or 'GB-ENG', I get the following error:

`Traceback (most recent call last):
  File "C:\Users\Desktop\example2.py", line 12, in <module>
    interest_by_region_df = pytrend.interest_by_region(resolution='city')
  File "C:\Python27\lib\site-packages\pytrends\request.py", line 147, in interest_by_region
    region_payload['req'] = json.dumps(self.interest_by_region_widget['request'])
KeyError: u'request'`

Any help on how to fix this would be greatly appreciated.

**Comment by ALIrezanouri** [comment]
same issue

**Comment by elibus** [comment]
That should be because you receive an empty answer from the server. If you perform the same request using your browser you will see no data. The PR I have submitted should fix this.

**Comment by dreyco676** [comment]
Thanks @elibus for the explanation. Reopen if this continues to be an issue.
