### ISSUE TITLE
Suggested keywords results returned in non-english language

### ISSUE THREAD

**Issue by nikoskal** [GeneralMills/pytrends#146]
Hi everyone, 
 I am using the following code :
pytrend = TrendReq(google_username, google_password, hl='en-US', custom_useragent='My Pytrends Script')
suggestions_dict = pytrend.suggestions(keyword = kw_list_obj)

When this code runs on my Mac I am getting results in English language without any problem.
But when this code runs on a Debian I am getting results in Greek, e.g. for keyword='obama'
[{"type": "Πρώην Πρόεδρος των Ηνωμένων Πολιτειών Αμερικής",
    "mid": "/m/02mjmr",
     "title": "Μπαράκ Ομπάμα"},
      ...
     ,{"type": "Συμβάν",
        "mid": "/m/057l6lw",
        "title": "Barack Obama 2009 presidential inauguration"}]

In both case hl is set to 'en-US'.
Locales of Debian are set to en-US.

Any help more than welcome.

**Comment by dreyco676** [comment]
That's really odd. Can I ask if your script is running from a Greek locale? I'm curious if those options are somehow being overridden.

**Comment by nikoskal** [comment]
Hi again,
it seems that google trends checks the IP of the system where the code is running. I am running the service on my personal computer, when I am connected through my home ADSL I am getting the results in English. When I connect through the university network and assigned an IP starting from 147.102.x.x I am getting results in Greek.
