### ISSUE TITLE
New pytrends release

### ISSUE THREAD

**Issue by rubencart** [GeneralMills/pytrends#155]
Could you please release a new version on the Python Package Index :-)?

Right now the latest version according to the official package index [page](https://pypi.python.org/pypi/pytrends) is 4.1.1, released on 2017-02-15.

**Comment by dreyco676** [comment]
I'll see if I can get some time to work on this over the week to close out some issues and push out a release.

**Comment by rubencart** [comment]
Would be nice! Thank you.

**Comment by dreyco676** [comment]
new version will release today, it will no longer use authentication so you'll need to adapt your code accordingly
