### ISSUE TITLE
Recursion errors

### ISSUE THREAD

**Issue by AbeIgnocious** [GeneralMills/pytrends#157]
I keep getting RecursionErrors while running the example code. I am using Jupyter notebooks, so that might play a role.

import pytrends.request
import sys
from pytrends.request import TrendReq

sys.setrecursionlimit(2500)

google_username = '____________@gmail.com'
google_password =  '____________'

pytrends = TrendReq(google_username, google_password, hl='en-US', tz=360, custom_useragent=None)
pytrends = build_payload(kw_list=['pizza', 'bagel'])

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-29-2f5b10bf52cf> in <module>()
     11 pytrends = TrendReq(google_username, google_password, hl='en-US', tz=360, custom_useragent=None)
     12 
---> 13 pytrends = build_payload(kw_list=['pizza', 'bagel'])

<ipython-input-16-31fb40089624> in build_payload(kw_list)
      8 # Can use up to 5 keywords as a list to build a payload.
      9 def build_payload(kw_list):
---> 10     pytrends = build_payload(kw_list)
     11     print('Succesfully built the payload')
     12 

... last 1 frames repeated, from the frame below ...

<ipython-input-16-31fb40089624> in build_payload(kw_list)
      8 # Can use up to 5 keywords as a list to build a payload.
      9 def build_payload(kw_list):
---> 10     pytrends = build_payload(kw_list)
     11     print('Succesfully built the payload')
     12 

RecursionError: maximum recursion depth exceeded

**Comment by dreyco676** [comment]
Might be a silly question, but did you put your username/password in?

At any rate there is a new version out. Let me know if the issue persists.
