### ISSUE TITLE
Authentication With Token

### ISSUE THREAD

**Issue by aCampello** [GeneralMills/pytrends#158]
Hi!

Do you guys know if it is possible to login without having to explicit pass your password, e.g. via a hashable Token?

Thanks
Antonio

**Comment by dreyco676** [comment]
No because this isn't an official API there is no way to get a token. By logging in you get a cookie and they use that to authenticate you. I have another branch that I was experimenting on to remove the login altogether but I'm not sure how it impacts rate limits.

**Comment by dreyco676** [comment]
Looks like I can remove the auth part now, the new(er) endpoints don't need the cookies.

**Comment by aCampello** [comment]
Thanks, this is very useful! The new code seems to use without authentication.

**Comment by polyakoff** [comment]
@dreyco676 
Thank you for the clarification. If needed, I can submit a PR on readme.md so it will correspond the recent changes of login removal (this wrong info part about the need to log in may be a bit confusing without looking to the source).

Do you already have any info about the rate limits with this recent change?
