### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'custom_useragent'

### ISSUE THREAD

**Issue by dp87** [GeneralMills/pytrends#166]
I managed to make pytrends work on 2 different machines, a macOS one and a Windows 10 one. However, if I launch the same script on other two machines, I get this error message:

```
Traceback (most recent call last):
  File "script.py", line 56, in <module>
    pytrend = TrendReq(google_username, google_password, custom_useragent='Python Google Trends script')
TypeError: __init__() got an unexpected keyword argument 'custom_useragent'
```

The two machines on which this is not working are a Windows 10 Home one and an Ubuntu 16.04 one, both with Python 2.7, so I am struggling to understand why this might be happening, especially because on two of the four machines things are working as expected.

**Note:** on the two machines that are working, I launched the script for the first time a few weeks ago, and they are both still working. The machines that are _not_ working are new ones, where the script was run for the first time in the last few days, so this makes me think there could have been some changes in the Google backend, and perhaps the first two machines use some sort of cached data that allows them to still connect.

If I remove the custom_useragent from TrendReq, i.e. like this:

`pytrend = TrendReq(google_username, google_password)`

I can get the script to run again but I get no results back, not sure if these two things are connected.

Any ideas what might be causing this and how to fix it?

**Update**

I managed to track down another more specific issue, which I think is the cause of the problem:

```
Traceback (most recent call last):
  File "script.py", line 135, in <module>
    pytrend.build_payload(kw_list=[keyword],geo=geo,timeframe='today 12-m')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pytrends/request.py", line 107, in build_payload
    self._tokens()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pytrends/request.py", line 118, in _tokens
    trim_chars=4,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pytrends/request.py", line 87, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.
```

Is this a recent change on Google's end? If so, can pytrends be updated to avoid this issue?

**Update 2**
Same issue with Python 3.

**Comment by dreyco676** [comment]
Library has been updated to not need Username/Password or Useragent. Please check out the new documentation/example and let me know if you hit any issues.

**Comment by dp87** [comment]
It seems to be working now, thanks @dreyco676 

Just one little thing for future reference: I used to be able to access specific values like this:

`interest_over_time_df.tail(1).values`

But now, after the library upgrade, this returns something like this:

`[[94 u'True']]`

So now, to access the actual number, I need to do:

`interest_over_time_df.tail(1).values[0][0]`

I don't remember the Bool entry in the results before, was this something that was changed in the last update? Not a big deal as I got things working again, but I just thought I'd check to make sure I am not missing anything.
