### ISSUE TITLE
What do we mean by suggestions? 

### ISSUE THREAD

**Issue by rmusngi** [GeneralMills/pytrends#167]
I was wondering if the suggestions part in pytrends displays suggestions that we see at the bottom of google searches?  Or are they from the autocomplete in the search bar?

Thank you!

**Comment by x-fran** [comment]
In my case, the results match neither with the bottom of google searches neither autocomplete in the search bar. Never.

**Comment by rmusngi** [comment]
Same here. That's why I'm wondering where are they from

**Comment by dreyco676** [comment]
Since this is an unofficial API it may be that they have changed the endpoint for Suggestions but PyTrends is still hitting the old one. Please create a PR if you have a new endpoint to point to.
