### ISSUE TITLE
RESPONSE ERROR 

### ISSUE THREAD

**Issue by rmusngi** [GeneralMills/pytrends#173]
I get this error:

`'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 500.`

What does it mean and how can I solve it? Thank you!

**Comment by droso11** [comment]
I have had this problem, passed arguments are invalid, for example I passed to the timeframe arg '{now} {past_time}' where it should be '{past_time} {now}'

**Comment by dreyco676** [comment]
Yes the function args have changed.
