### ISSUE TITLE
no recent 2 months data

### ISSUE THREAD

**Issue by linqianyun51** [GeneralMills/pytrends#179]
When I was using the codes to pull weekly google trend data I didn't get the most 2 month of data, did anyone else is facing this issue?

**Comment by dreyco676** [comment]
Can you share an example call?

Thanks

**Comment by linqianyun51** [comment]
When I tried the following codes, it's not returning the most recent 2 months

trend_payload = {'q': 'mattress', 'date':'today 12-m','tz':'Etc/UTM-4','geo':'US'}
df = connector.trend(trend_payload, return_type='dataframe')

**Comment by linqianyun51** [comment]
@dreyco676 not sure whether that's an API issue, because when I tried to pull the data using supermetrics, I'm also missing most 2 months of data
