### ISSUE TITLE
How to use the address that is made using .suggestions()?

### ISSUE THREAD

**Issue by worchan** [GeneralMills/pytrends#181]
As given in the example 
![advanced](https://user-images.githubusercontent.com/16303779/31858268-2db8180a-b711-11e7-8b3a-b2dba2939a5d.PNG)
If we want to search by topic, then we'll have to use the suggestions() function, extract the information about the code of the topic, then edit the address, and then we'll get the address( Google Trends' address). Now, how do I use this address?

Like in the case of 'iron', we'll get the address: https://trends.google.com/trends/explore?date=all&q=%2Fm%2F025rw19
Now how can we use it (in pytrends) to get results regarding it?

**Comment by TheOtherGuy9603** [comment]
just use the 'mid' you receive from the suggestion as a keyword
in this case,
`pytrend.build_payload(kw_list=[selection_id])`
