### ISSUE TITLE
comparing the same keyword in different timeframes

### ISSUE THREAD

**Issue by dvamossy** [GeneralMills/pytrends#185]
GoogleTrends stopped doing fixed scaling, so data from 2006 is not really comparable to data from 2007. In order to do that, you need to compare the same keyword in 2006 & 2007, and then it will scale it accordingly. Has anyone come up with a solution for this (e.g. to enter multiple timeframes)?

**Comment by dreyco676** [comment]
Yes there is a PR request for tying together multiple daily sets. I think
the same will apply for multi-year.

**Comment by dvamossy** [comment]
Any clue when it will be available? I am working on modifying the source code, but if it's in development, I will give up on it haha

**Comment by dreyco676** [comment]
You can see an example in this PR:
https://github.com/GeneralMills/pytrends/pull/183

**Comment by dreyco676** [comment]
@bigme666 is working on a more formal function in #174
