### ISSUE TITLE
timezone offset

### ISSUE THREAD

**Issue by mnkil** [GeneralMills/pytrends#186]
Hi - first off all Cudos for this amazing pseudo-api, works perfectly for me.

Only have a minor question: timezone-offset e.g. 360 for US CST means, every day has a cut-off at 12PM US CST?

**Comment by mckelvin** [comment]
I did some experiments.

```
360 means -0600, 360 minutes = 6 * 60
-480 means +0800, -480 minutes = -8 * 60
```

As you can see, the sign is wired. If you're using UTC, you should use `0`.
