### ISSUE TITLE
First of all - Loving Pytrends

### ISSUE THREAD

**Issue by mayankshah891** [GeneralMills/pytrends#188]
Great work creating this, really appreciate it.

Is the rate limit stemming from my email, or my email *and* my IP address? If just email, how can I switch emails every couple hundred runs? I don't see that part of the code.

Thanks!

**Comment by rajarshi-xtage** [comment]
@mayankshah891 can you provide any information about what type of rate limit you are facing? i.e. how many calls are allowing for a time interval before rate limiting?

**Comment by mayankshah891** [comment]
400 per hour is what I'm currently experiencing. Changing IP, VPN, etc. doesn't help

**Comment by ezkang** [comment]
Did you happen to solve this problem? I think I am having a same issue here

**Comment by Hotkey** [comment]
+1
