### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by sfranchois** [GeneralMills/pytrends#191]
The introduction in the readme states:

> Main feature is to allow the script to login to Google on your behalf to enable a higher rate limit.

Is this (still) the case? Can't seem to find any way to log in, or have me logged in.

Btw, does someone _more or less_ know what rate limiting Google applies,in terms of  calls per minute, total calls per day, ...? 

Thank you all!

**Comment by mayankshah891** [comment]
The rate limit is 400 per hour, you don't have to login, and (so far) I haven't found a way to get around it

**Comment by sfranchois** [comment]
Super! Thanks for this valuable piece of info.
