### ISSUE TITLE
Pytrends Variable Timeframe and Region

### ISSUE THREAD

**Issue by mdch32** [GeneralMills/pytrends#196]
I am trying to write a dynamic script so that timeframe and region can change under different environments. In this instance, I am pulling a single record from a SQL server (search term, start date, end date, and region), saving each as a variable, and am attempting to build my statement using these variables. No matter what I do I always receive a Code 400 error. Below is an example of what I am doing, any and all help would be greatly appreciated. I would be surprised if this is truly a limitation.

Variables saved:
Search_Term = 'Food Delivery'
Start_Date = '2015-01-01'
End_Date = '2017-11-11'
Dates = '2015-01-01 2017-11-11'
Region = 'US'

Statement that works:
	pytrend = TrendReq(hl='en-US', tz=360)
	pytrend.build_payload(kw_list=[Search_Term], geo = 'US', timeframe = '2015-01-01 2017-11-11')
	interest = pytrend.interest_over_time()

Statement #1 that does not work:
	pytrend = TrendReq(hl='en-US', tz=360)
	pytrend.build_payload(kw_list=[Search_Term], geo = Region, timeframe = Dates )
	interest = pytrend.interest_over_time()

Statement #2 that does not work:
	pytrend = TrendReq(hl='en-US', tz=360)
	pytrend.build_payload(kw_list=[Search_Term], geo = Region, timeframe = Start_Date + ' ' + End_Date)
	interest = pytrend.interest_over_time()

Thank you again for any and all help. 

@dreyco676 @danielbchaves @rajarshi-xtage @bigme666

**Comment by peiyichiang** [comment]
Hi, I am running into a similar problem, so I am wondering how you fixed this?
