### ISSUE TITLE
The request failed: Google returned a response with code 429.

### ISSUE THREAD

**Issue by ezkang** [GeneralMills/pytrends#198]
I am very new to python and I have 2000+ keywords as DNA list and try to crawl data. When I run this code, it appears with "Google returned a response with code 429" even though I added `time.sleep(1)`. Can anyone help me with this problem?

below is my code

    #DNA has 2000+ lists
    from pytrends.request import TrendReq
    import pandas as pd
    import xlsxwriter
    import time
    
    pytrends = TrendReq(hl='en-US,tz=360')
    Data = pd.DataFrame()
    
    #Google Trend Crawler
    for i in range(DNA[i]):
        time.sleep(1)
        kw_list = [DNA[i]]
        pytrends.build_payload(kw_list, cat=0, timeframe='today 5-y', geo='', gprop='')
        df = pd.DataFrame(pytrends.interest_over_time())
    
        #Setting a Google Trend Dates
        if(i==0):
            Googledate = pd.DataFrame(pytrends.interest_over_time())
            Data['Date'] = Googledate.index
            Data.set_index('Date', inplace=True)
            
        #results
        if(df.empty == True):
            Data[DNA[i]] = ""  
        else:
            df.index.name = 'Date'
            df.reset_index(inplace=True)
            Data[DNA[i]] = df.loc[:, DNA[i]]
    Data

**Comment by ezkang** [comment]
I am thinking that when I tried to run all 2000+ list of kw_list, it exceed its limit and keep giving me error for my other small requests. 

Does anyone know the limit per day? 
I read some issues and it seems like its 400 request per hour, but it's been over three hours after my initial error. 

Thanks in advance

**Comment by davejonesbkk** [comment]
I can't say for sure as I've just started using pytrends myself now but I have a fair amount of experience writing scripts to get info from Google search and they will block your ip pretty fast if they suspect you spamming or scraping or any other kind of abuse of the system and you have to pretty careful. 2k is a pretty large amount of requests and even with waits you are going to need to be careful plus Google is good at spotting waits so you need to randomize them.

**Comment by dmil** [comment]
+1 - I have scripts that used to work, but now returns this error. Even with only one keyword being queried only one time.

**Comment by dmil** [comment]
https://github.com/GeneralMills/pytrends/issues/243

**Comment by kalagee-anjaria** [comment]
Hello all,
I am still getting the same error even though my pytrends library is of the latest version. Any suggestions on what should I do now to get rid of this error?

**Comment by Mustafa-Ellebody** [comment]
I tried many solutions, but this one doesn't seem to get blocked: https://rapidapi.com/odlica-odlica-default/api/trendly
