### ISSUE TITLE
Two keywords, parse_data function issue

### ISSUE THREAD

**Issue by kropson** [GeneralMills/pytrends#20]
Hi. I have one problem with script.

If I use two keywords (and each has got different period of time -
month and week) parse_data function returns dictionary without one
keyword. For example if I request "mleko migdałowe, posadzka betonowa"
(Polish language), parse_data returns trends only for "mleko
migdałowe".

Is there a possibility to return dict for both keywords? I care about
relation between keywords trends so I can request it single.

Greetings
Bartek

**Comment by bdewilde** [comment]
Hi @kropson, could you send an example function call, so I could try to reproduce it? As far as I remember, the code should handle multiple keywords, although I'm not sure what you mean by "each has got different period of time").

**Comment by dreyco676** [comment]
I'm able to reproduce this. I'm trying to compare doing it by hand and haven't found any difference to account for why the data does not show up.

**Comment by dreyco676** [comment]
Actually manually trying to download the data from google trends produces the same issue. So this is unfortunately out of our hands. I'll message @GoogleTrends on Twitter with the issue to see if they can fix it.

**Comment by dreyco676** [comment]
Closing, will update if google responds.
