### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by ezkang** [GeneralMills/pytrends#202]
I read the limit is 400 per hour, but it seems like I can go beyond 400 per hour. However, I found out that maximum limit is 1600 request per day. If anyone got other limit , let me know.

**Comment by CarlosQuappe** [comment]
I have the same question about the rate limit. I've heard it changes quite a lot, and that right now is 1600. If anybody has further information, please let us know.

**Comment by dreyco676** [comment]
It varies quite a bit there is no posted amount. 400 is a safe estimate.
