### ISSUE TITLE
A word as a Topic instead of a Search Term?

### ISSUE THREAD

**Issue by jim2312** [GeneralMills/pytrends#204]
Is it possible to specify whether a word (e.g. Holiday) is a Topic instead of a Search Term? In Google Trends, we can do this from the autocomplete in the search bar. Is this possible using pytrends? 

The 'mid' for the topic Holiday is %2Fm%2F03gkl . But I don't know how to use this with pytrends.

Thanks a lot!

**Comment by dripti** [comment]
is there any ans to this??

**Comment by OD1995** [comment]
@dreyco676 why was this closed? There's yet to be an answer and until there is one, surely there is no use in closing it?

**Comment by dreyco676** [comment]
Sorry, we had a huge backlog of PR's and issues. Needed a clean slate. I believe this use case is already covered per the docs https://github.com/GeneralMills/pytrends#common-api-parameters. Please let me know if it is not.
