### ISSUE TITLE
Interest by CITY when geo=country-code and resolution = CITY

### ISSUE THREAD

**Issue by mehtatwinkle** [GeneralMills/pytrends#206]
The code fails to fetch data on interest by city (i.e resolution = CITY in interest by region attribute) when geo = 'country code' instead of ''. It returns interest by subregion only. 

_For eg:_
pytrends = TrendReq(hl='en-US', tz=360)
pytrends.build_payload(["Apple"], cat=0, geo="US", gprop='')

_Here_, pytrends.interest_by_region() and pytrends.interest_by_region(resolution = 'CITY') return the same results. 

This is due to a missing _if_ statement in request.py. This can be resolved by adding the following after **__line_ 193_**: 
`if (self.geo != '') & (resolution == 'CITY'): `
                                                                                                                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`self.interest_by_region_widget['request']['resolution'] = resolution`

**Comment by jmiguel99** [comment]
I'm having the same problem, but you can specify in the geo attribute with an extra parameter. e.g.
 for San Francisco, CA, you will use geo='US-CA-807' that is the denomination for that specific metropolitan area. therefore, the code should look like:

pytrends.build_payload(["Apple"], cat=0, geo="US-CA-807", gprop='')

It should be noted as well, that the response for an specific metropolitan area could include just one city or different cities, towns or districts included in that metropolitan area.

**Comment by alexvaa** [comment]
same problem

**Comment by katiyarsahil** [comment]
where can i get the codes(like US-CA-807 for San francisco) for the entire US?
