### ISSUE TITLE
Monthly trends only up to 2 days ago

### ISSUE THREAD

**Issue by fdeste** [GeneralMills/pytrends#209]
Dear all,
if I use the library to query for the monthly trend (using [today 3-m]) I don't get complete results (I am missing the lasts 2 days). 
Is this a normal behaviour of Google Trends? Maybe I should authenticate?

Thanks for the great work,

**Comment by gdoron** [comment]
I know it's an extremely old issue, but did you manage to overcome this? @fdeste

**Comment by fdeste** [comment]
> I know it's an extremely old issue, but did you manage to overcome this? @fdeste

sorry, I don't remember :-(
