### ISSUE TITLE
pytrends.related_queries() and pytrends.related_topics() only works if there's only one keyword

### ISSUE THREAD

**Issue by jersobh** [GeneralMills/pytrends#212]
Otherwise the dict is empty

**Comment by vinitrinh** [comment]
Facing a similar problem. Is there a way to retrieve the related keywords with empty keyword list?

**Comment by vinitrinh** [comment]
Hi Jersobh, for now, here's a stopgap solution without needing to crack open the package.
`

def get_related_queries(catno = 0, kw_list=[""], 
                        timeframe = period, geo="SG"):
    """
    Gets related queries
    """
    # Create Pytrend Client
    pytrend.build_payload(cat = catno 
                          ,kw_list=kw_list, timeframe = timeframe, geo=geo)

    # Form Request
    related_payload = dict()
    request_json = pytrend.related_queries_widget_list[0]
    related_payload["req"] = json.dumps(request_json["request"])
    related_payload["token"] = request_json["token"]
    related_payload["tz"] = pytrend.tz

    # Send Request
    req_json = pytrend._get_data(
        url=TrendReq.RELATED_QUERIES_URL,
        method=TrendReq.GET_METHOD,
        trim_chars=5,
        params=related_payload,
    )

    # Tabulate Rising & Top searches.
    try:
        top_df = pd.DataFrame(req_json["default"]["rankedList"][0]["rankedKeyword"])
        top_df = top_df[["query", "value"]]
    except KeyError:
        # in case no top queries are found, the lines above will throw a KeyError
        top_df = None

    # rising queries
    try:
        rising_df = pd.DataFrame(req_json['default']['rankedList'][1]["rankedKeyword"])
        rising_df = rising_df[['query', 'value']]
    except KeyError:
        # in case no rising queries are found, the lines above will throw a KeyError
        rising_df = None

    return(top_df,rising_df)

top_df,rising_df = get_related_queries(catno = 288)
top_df`

`

**Comment by yinleon** [comment]
Is there a solution for this?
The code snippet from @vinitrinh isn't working for me :\

**Comment by fersarr** [comment]
Happening to me too. Used two keywords and then the dict result does not have the data for any keywords. Removed one and it works fine

**Comment by dayures** [comment]
still facing this issue with the latest version & Python 3
