### ISSUE TITLE
Unexpected keyword argument 'custom_useragent'

### ISSUE THREAD

**Issue by LianaN** [GeneralMills/pytrends#214]
Hi,

I install `pytrends` with `pip install pytrends --upgrade`. But I have several issues.

1. When I run the example shown below, I get the error `TypeError: __init__() got an unexpected keyword argument 'custom_useragent'`.

```
google_username = "...@gmail.com"
google_password = "..."
pytrend = TrendReq(google_username, google_password, custom_useragent='My Pytrends Script')
```

2. When I try to search for a pair of keywords, for example, ["zoo, bear"] (like "zoo" AND "bear"), I always get an empty result.

**Comment by dreyco676** [comment]
The function call has changed. Please see new docs.
