### ISSUE TITLE
Google Error 503

### ISSUE THREAD

**Issue by nahushk** [GeneralMills/pytrends#215]
Running the example code and keep getting the following error text: 
 
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytrends/request.py", line 88, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 503.

Is the Google API being unresponsive? Or is there something wrong on my end?

**Comment by tylerhutcherson** [comment]
Second this issue. I'm running a version of the daily data request using pytrends and I seem to consistently be getting 503.  

File \"/usr/local/lib/python3.6/site-packages/pytrends/request.py\", 
line 119, in _tokens\n
trim_chars=4,\n
File \"/usr/local/lib/python3.6/site-packages/pytrends/request.py\", 
line 88, in _get_data\n
'response with code {0}.'.format(response.status_code), response=response)\n
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 503.\n

It fails on `pytrend.build_payload(...)`.

**Comment by diplodata** [comment]
TBA - R package is also currently broken https://github.com/PMassicotte/gtrendsR/issues/252

**Comment by TadejVranesic** [comment]
Same error. Someone figured out how to fix it?

**Comment by ha554n** [comment]
It seems like there is a limit to how many times you can query before google locks you out for 24 hours. I think each search term counts as one query.  I have a loop that runs 100 search terms and I can only run it a couple times or so, don't know the exact limit.

**Comment by diplodata** [comment]
Is there any sleep time in your loop?

**Comment by ha554n** [comment]
No, I am running it manually for now to develop. Looks like the limit is about 150 queries a day from my most recent attempt.

**Comment by diplodata** [comment]
You really should include a 1s pause between calls, preferably more. More considerate to their server, and might help to avoid/delay the block.

**Comment by ha554n** [comment]
Good point. That seemed to solve my issue! thanks.

**Comment by dreyco676** [comment]
Best practice is to do 1-5sec random intervals to avoid being obvious bot traffic.
