### ISSUE TITLE
Is there a way to get the number of hits of a term?

### ISSUE THREAD

**Issue by renanfilipe** [GeneralMills/pytrends#218]
Hello, I am using "pytrends.interest_over_time()" to get the info that you can see on the graphic, but that info is normalized and it changes depending of the time frame, so I though that would be better if I had the number of hits. How can I get these numbers?

**Comment by vikramarun** [comment]
The way Google Trends outputs the data (to my knowledge) is just by scaling it down based on the top number of hits for any given time-frame. If you wanted to compare two time frames then, you would have to have at least one data point that was in common between the two time frames. Then you could rescale the entire data set.

If there is a way to get the pure number of hits, I'd be interested as well! But this workaround has been OK for me so far.

**Comment by uppilih** [comment]
It seems as though pytrends provides the unnormalized number of hits though - has this been your experiences as well?
