### ISSUE TITLE
Google returns a response with code 400 when a key word is > 100 characters.

### ISSUE THREAD

**Issue by jcc10** [GeneralMills/pytrends#224]
EDIT: Kind of my fault however it would be good to document it this, The max length of a single key word is 100 characters, however recommended key words may give you a key word that is longer.

So, it looks like google changed their system again.

pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.

Full traceback:

self.pt is a pytrends.request TrendReq object.

```
  File "E:\Enviroments\TensorFlow\Project Foresight\BootstrapCode\trendGetter.py", line 41, in buildPL
    self.pt.build_payload(kw_list)
  File "C:\Python35\lib\site-packages\pytrends\request.py", line 108, in build_payload
    self._tokens()
  File "C:\Python35\lib\site-packages\pytrends\request.py", line 119, in _tokens
    trim_chars=4,
  File "C:\Python35\lib\site-packages\pytrends\request.py", line 88, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.
```
I have the most up-to-date PIP package of PyTrends. (pytrends (4.3.0)) Additionally this was working for the past 4 days, I have not altered the program.

**Comment by jcc10** [comment]
Update: It seems that slowing down the connections by a significant amount. It seems that they will sometimes give you a 400 error instead of a 429 error.

Future people/me: if you are getting 400 errors, add in a insane delay to see if it is just you sending stuff too fast, it might not be a trends update.

**Comment by jcc10** [comment]
Ok, so I figured out what it was and it would be good to document it this, The max length of a single key word is 100 characters, however recommended key words may give you a key word that is longer.

It may also be good to preform a extra sanity check to see if the kw is too long and return a error that is helpful.

**Comment by petersonnek** [comment]
Hey @jcc10, Thanks for the feedback! If you wouldn't mind, could you submit a PR with your proposed documentation updates?
