### ISSUE TITLE
Is it possible to receive daily data instead of weekly?

### ISSUE THREAD

**Issue by GonzaloTunez** [GeneralMills/pytrends#226]
Would be much more useful for real time pattern recognition if  the data we received wasn't a week old.

This API apparently processes daily data but I don't know R

https://github.com/321k/Google-Trends/blob/master/Working%20example

**Comment by GregHilston** [comment]
@GonzaloTunez The referenced project no longer works: https://github.com/321k/Google-Trends/issues/4

I too am interested in daily data

**Comment by ElliotP123** [comment]
It's possible to receive daily with Google Trends. It only shows you daily data if you select a maximum time range of 3months, anything longer and it goes to weekly. 

To be able to scale/normalize the data together you need to pull both the daily and the weekly data and then find a standardizing value. There are plenty of guides online about how to do it.

**Comment by lopezdp** [comment]
@ElliotP123 any clues where those guides might be?

**Comment by rsmahabir** [comment]
Are there any description for the following outputted data?

[u'date', u'exploreUrl', u'formattedTraffic', u'hotnessColor',
       u'hotnessLevel', u'imgLinkUrl', u'imgSource', u'imgUrl',
       u'newsArticlesList', u'relatedSearchesList', u'safe', u'shareUrl',
       u'startTime', u'title', u'titleLinkUrl', u'trafficBucketLowerBound']

**Comment by drjanehall** [comment]
Hello! I'm a biostatistician and have a script available for daily data downloads. I don't check my GitHub  account frequently for updates, but if you have questions or a request, feel free to Tweet me @hall_phd  -- good luck! -- Jane
