### ISSUE TITLE
trending_searches() localised

### ISSUE THREAD

**Issue by ElliotP123** [GeneralMills/pytrends#228]
Afternoon,

I was wondering if it's possible to find the trending searches for a country? I've tried building the payload with 'AU' for Australian and I still feel I'm receiving US related trending searches (all US publications & doesn't match current Google Trending Searches list).

Thoughts?

**Comment by alexvaa** [comment]
+1

**Comment by ChrisBg** [comment]
+1

**Comment by brokeharvard** [comment]
+1

**Comment by dabdada** [comment]
You can do this with providing the pn parameter to the trendng_searches function. As of now I found the following pn values to be valid (then I run into rate limits, so I try to colplete it step by step):

p1 --> US
p3 --> IN
p4 --> JP
p5 --> SG
p6 --> IL
p8 --> AU
p9 --> GB
p10 --> HK
p12 --> TW
p13 --> CA
p14 --> RU
p15 --> DE
p16 --> FR
p17 --> NL
p18 --> BR
p19 --> ID
p21 --> MX
p23 --> KR
p24 --> TR
p25 --> PH
p26 --> ES
p27 --> IT
p28 --> VN
p29 --> EG
p30 --> AR
p31 --> PL
p32 --> CO
p33 --> TH
p34 --> MY
p35 --> UA
p36 --> SA
p37 --> KE
p38 --> CL
p39 --> RO
p40 --> ZA
p41 --> BE
p42 --> SE
p43 --> CZ
p44 --> AT
p45 --> HU
p46 --> CH
p47 --> PT
p48 --> GR
p49 --> DK
p50 --> FI
p51 --> NO
p52 --> NG
p53 --> NZ
p54 --> IE

Maybe the one you need is already in there. I hope this is also resulting in what you have been looking for. If so we should maybe think of adding this to the Documentation
