### ISSUE TITLE
Issue #117 Still not Fixed

### ISSUE THREAD

**Issue by jdglaser** [GeneralMills/pytrends#229]
It appears that the 'gprop' argument does not change the results of the Google Trends query, and just resorts to the default 'web search' no matter what is entered for the parameter. This issue was referenced in Issue #117 but it does not appear to have been fixed. 

Anyone have a way of fixing this? I tried changing the value manually in pytrends.request.build_payload, but got a 400 error from Google Trends.

**Comment by Megatvini** [comment]
have you tried to download the repository and install with setup.py?

**Comment by jdglaser** [comment]
Yes it looks like the issue is fixed when installing directly from Github. It looks like the pip install version is not updated.
