### ISSUE TITLE
Per minute trends for long time ranges

### ISSUE THREAD

**Issue by samre12** [GeneralMills/pytrends#232]
Can this API be used to extract per minute trends for time ranges spanning over years?
I am building a bot that trades per minute and requires historical per minute prices to take a decision. I am thinking of incorporating trends also as an input to the model.

**Comment by dreyco676** [comment]
Unlikely. You will probably hit rate limits given how many requests it would need. Additionally, I'm not sure what the reporting lag is for current data.

**Comment by samre12** [comment]
@dreyco676 is there any alternative way that you know of to achieve the same?
It will be very helpful.
