### ISSUE TITLE
How to get the title list on trending searches

### ISSUE THREAD

**Issue by Mineleague** [GeneralMills/pytrends#236]
Hello GeneralMills, 
I am having an issue with PyTrends and filtering the data on a pandas dataframe. I would like to select the **title** data table only, and then filter out all other info to just get a list of the titles of the trends.
I have tried to slice the pandas dataframes, but I cannot understand how to select the single data table  that has the info I need from the ~10 received in the output.
Thanks, Mineleague

**Comment by datainvestor** [comment]
You might try something like this
```
df=pytrends.trending_searches()
gtrendsus=df.title[0:15].tolist()
```
