### ISSUE TITLE
Errors 429 when calling the API

### ISSUE THREAD

**Issue by raulviitor1** [GeneralMills/pytrends#238]
Hi, I am doing some requests with the pytrends but I am receiving many errors with "The request failed: Google returned a response with code 429."

How can I avoid this message ?

**Comment by lisovyk** [comment]
Did you google what code 429 means? It is not pytrends problem.

**Comment by lisovyk** [comment]
429 code clearly means that you send too many requests. Maybe there are a lot of people in your subnetwork that send requests to the same server, or the server thinks that 16 is too much.

**Comment by jersobh** [comment]
There's only me here. No way to be that.

**Comment by mlasy** [comment]
have the same issue ... i think they updated their policy or something? i had the script running for several month, suddenly i only get 429 without changing anyting

**Comment by dreyco676** [comment]
Duplicate of #243
