### ISSUE TITLE
unable to pull trends for a list of individual keywords: Error code 400

### ISSUE THREAD

**Issue by rushikb** [GeneralMills/pytrends#246]
first, Thanks so much for this package. it is an absolutely invaluable tool. 

I'm trying to pull KW trends for a list of terms, but want to pull data for each term separately, split by region, then append them onto one dataframe. This is because for a list of terms in kw_list, google trends indexes them relative to each other, but I want them indexed relative to search volume in the country. However, I keep running into the same error: ResponseError: The request failed: Google returned a response with code 400

I must be making a very obvious mistake, but any help would be greatly appreciated. 

Here's the code I'm running. I'm using pytrends 4.4, on python 3.6.5

pytrends = TrendReq(hl='ID', tz=360)
kw_list_full = ['jual','beli','harga','belanja']

df_1 = pd.DataFrame()
for i in kw_list_full:
    kw_list = i
    pytrends.build_payload(kw_list, timeframe='today 12-m', geo='ID')
    df_1.append= pytrends.interest_by_region(resolution='REGION')

**Comment by dabdada** [comment]
You need to wrap kwlist into a list. As of the iteration loop of the kw_list_full, i is a string object.

**Comment by dabdada** [comment]
in build payload you need to pass a list object. Due to the iteration in the for loop, your i (and with that your kw_list) is a string object.

So replacing `pytrends.build_payload(kw_list, timeframe='today 12-m', geo='ID')` with `pytrends.build_payload([kw_list], timeframe='today 12-m', geo='ID')`
should do the trick for this.

**Comment by rushikb** [comment]
Thanks so much!
