### ISSUE TITLE
The request failed: Google returned a response with code 500.

### ISSUE THREAD

**Issue by AmitMY** [GeneralMills/pytrends#247]
For a few days now, this following code does not work anymore:
```python
pytrend = TrendReq()
# Create payload and capture API tokens
pytrend.build_payload(kw_list=['Banana'], timeframe='2013-4-28T0 2013-4-28T4')
# Interest Over Time
interest_over_time_df = pytrend.interest_over_time()
```
It fails with:
> The request failed: Google returned a response with code 500.

**Comment by dabdada** [comment]
I do get that for all requests which use a date starting from older than the 1st of january 2015. So if I use the parameter timeframe='2015-1-01T0 2015-1-01T4' it basically works (did not check if I get correct values though).

On the other hand, if I just throw away the T0 and T4 in the parameter string of timeframe it works without issues (this is also how the parameter is given in trends.google.com itself, and it also fails if I add it manually in the url).

So I am not really sure what this T0 and T4 addition is, but I guess its different time slots. In a quick research I could not figure out how this is now selectable (you can not do it via gui), unfortunatelly the range 2013-4-28 to 2013-4-29 does only provide two data points one from each day, so there is also no chance to filter on the dataframe.

I am afraid your requested data is simply to old, sorry.

**Comment by AmitMY** [comment]
> So I am not really sure what this T0 and T4 addition
It's the hours I want data from (I want data in minute granularity)

Fair enough, that's good info too, as much as I don't like it to be.
Thanks!
