### ISSUE TITLE
ModuleNotFoundError: No module named 'pytrends.request'; 'pytrends' is not a package

### ISSUE THREAD

**Issue by avolution** [GeneralMills/pytrends#248]
Was trying to execute the github example 

from pytrends.request import TrendReq
pytrends = TrendReq(hl='en-US', tz=360)
...

Results in Error---->

Traceback (most recent call last):
  File "/pytrends.py", line 1, in <module>
    from pytrends.request import TrendReq
  File "/pytrends.py", line 1, in <module>
    from pytrends.request import TrendReq
ModuleNotFoundError: No module named 'pytrends.request'; 'pytrends' is not a package

**Comment by avolution** [comment]
I have executed 

--> pip install pytrends

before for sure.

**Comment by avolution** [comment]
In the debugger the module looks like this:

pytrends = {module} <module 'pytrends' from '/pytrends.py'>
-pytrends = {module} <module 'pytrends' from '/pytrends.py'>
--pytrends = {module} <module 'pytrends' from '/pytrends.py'>
---pytrends = {module} <module 'pytrends' from '/pytrends.py'>
----pytrends = {module} <module 'pytrends' from '/pytrends.py'>

The ENV is 
Python 3.6.4 :: Anaconda, Inc.

-------

I have been tested it on 
Python 2.7.14 :: Anaconda, Inc.

And here it's working

**Comment by MeSans** [comment]
I had the same issue. 
Renaming the file you want to run to something other than pytrends.py worked for me

**Comment by sravanstrns** [comment]
I had the same issue.
i am using version python 3.6.3  what to do

Traceback (most recent call last):
  File "E:\pytrends\pytrends-master\examples\trends.py", line 1, in <module>
    from pytrends.request import TrendReq
  File "E:\pytrends\pytrends-master\examples\pytrends.py", line 1, in <module>
ImportError: No module named request

**Comment by KorayTugberk-g** [comment]
I still have the same issue.

**Comment by ericvoots** [comment]
Any updates, I have the same issue using python 3.8.3 in Ubuntu

**Comment by d9x33** [comment]
Are you guys sure you're not naming the file you're editing `pytrends.py`? That might be the issue.

**Comment by owardlaw** [comment]
add 

> pytrends = TrendReq(hl='en-US', tz=360) 

at the bottom of your import list

**Comment by rohanayush** [comment]
pip install --upgrade pytrends

This worked for me, I am using python 3.11

**Comment by flosrv** [comment]
no way to make it work. and upgrade or anything will not work att all.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from pytrends.request import TrendReq

ModuleNotFoundError: No module named 'pytrends'
