### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by LAMASLAYER** [GeneralMills/pytrends#250]
Hi, I'm behind a proxy so I'd guess it's the problem here. However I can't find a way to fix it. Here's what i get: 

> C:\Users\ku714\Desktop\projects\pytrends\venv\Scripts\python.exe C:/Users/ku714/Desktop/projects/pytrends/examples/example.py
> Traceback (most recent call last):
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw)
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
>     raise err
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
>     conn.connect()
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\connection.py", line 314, in connect
>     conn = self._new_conn()
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000000000B7EBDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\requests\adapters.py", line 445, in send
>     timeout=timeout
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\urllib3\util\retry.py", line 398, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000B7EBDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/ku714/Desktop/projects/pytrends/examples/example.py", line 5, in <module>
>     pytrend = TrendReq(hl='en-US', tz=360, proxies={'https': 'https://webproxy-fra.deutsche-boerse.de:8080'})
>   File "C:\Users\ku714\Desktop\projects\pytrends\pytrends\request.py", line 54, in __init__
>     requests.get('https://trends.google.com').cookies.items()
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\requests\api.py", line 72, in get
>     return request('get', url, params=params, **kwargs)
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\requests\api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\requests\sessions.py", line 512, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\requests\sessions.py", line 622, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Users\ku714\Desktop\projects\pytrends\venv\lib\site-packages\requests\adapters.py", line 513, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000B7EBDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)

I'm trying to run the example query.

**Comment by dukesun99** [comment]
I am using proxies and it works fine. Did you check your proxy before using it? It seems like your proxy refused your connection...

**Comment by cemanughian** [comment]
I am having the same problem. I specified my proxy correctly.
