### ISSUE TITLE
Timezone (tz) parameters seems to not be working 

### ISSUE THREAD

**Issue by shoyasaxa** [GeneralMills/pytrends#251]
It seems like the timezone parameter does not alter the fetched data. 

For example, requests sent with parameters below produce the exact same data. 

pytrends = TrendReq(hl='en-US', tz=0, geo='')
pytrends2 = TrendReq(hl='en-US', tz=360, geo='')

I know I can localize and convert the timezone, but what is the default timezone that is being used right now to fetch the data? I know that the default tz value is 360, but how do we know that it is actually getting it for this timezone? 

Thank you ahead for your help!

**Comment by anndreh** [comment]
Hi friends,

Any solution for this issue? I'm having the same problem when I try to inform 180, the result ignores this param.

Than you and congratulations for the good lib =)

**Comment by amradel27** [comment]
why is this issue closed it's still not answered !! how do we know that it is actually getting it for this timezone?

**Comment by bibinhashley** [comment]
![git](https://user-images.githubusercontent.com/71463427/116371739-5ea61400-a829-11eb-8cb0-a6ada4398843.png)
Wherever the location is, google calls it with tz -330

**Comment by bibinhashley** [comment]
try and change that data to 'now 1-H', then you will see the and understand usage of timezone. Because there the time would be according to the timezone you given.
