### ISSUE TITLE
Is it possible to receive monthly data instead of hourly?

### ISSUE THREAD

**Issue by tirilazat** [GeneralMills/pytrends#255]
Hello people,

I am currently facing the problem, that no matter how long I pick the search intervall, I always receive hourly data. My goal is to pick a very long search intervall but to receive monthly data.
I use the pytrends.get_historical_interest()-function.

I already tried calculating monthly interest by averaging all the hourly interest values. Sadly, when comparing those results to what I get if I download the monthly data manually, the correlation-coefficient was only 0.17, so that does not seem to work.

Thanks for your help!

**Comment by ars398** [comment]
Same question here - Google Trends with weekly to monthly. Using 10 years I get weekly data however Google Trends in actual does only provide weekly data for 5 years ... 
Thanks for help too.

**Comment by e-271** [comment]
You can do this by changing the date string formats in the request. See my fork here, which does daily resolution:

https://github.com/e-271/pytrends/commit/2f384e1263e39ef2fada1fd6b45433c629fd9134

Whatever resolution you pass in for the date strings seems to be what you get back. But then the date range you request has to match, and for low-resolution settings like hourly the date interval can't be too big (1 week is the max for hourly resolution, I think 6 months is the max for daily).
