### ISSUE TITLE
No historical data after 27/07/2018?

### ISSUE THREAD

**Issue by Exceluser** [GeneralMills/pytrends#258]
So I have tried to get historical googletrends data from the beginning of this year up until now but no matter what I try, it always breaks off after 27/07/2018.

The code to get all data at once was
`hist_data = pytrend.get_historical_interest(['Harambe'], year_start=2018, month_start=1, day_start=1, hour_start=0, year_end=2018, month_end=8, day_end=12, hour_end=0, sleep=60)`
which yielded 

> The request failed: Google returned a response with code 500.

But even trying just a small timeframe did not work
`hist_data = pytrend.get_historical_interest(['Harambe'], year_start=2018, month_start=8, day_start=1, hour_start=0, year_end=2018, month_end=8, day_end=3, hour_end=0, sleep=60)`
yielded an empty dataframe.

Any input on why this happens would be greatly appreciated!

**Comment by Exceluser** [comment]
Ok so I did some more testing and I can get data up until 2018-07-31T10 but not any further. 
Seems like one is only eligible to retain data up until 2 weeks from today.

**Comment by dwightmulcahy** [comment]
I'm getting the same results...  with `The request failed: Google returned a response with code 500.` depending on the number of days requested.

I haven't been able to figure out what the limits are...

**Comment by dwightmulcahy** [comment]
This might also be related to the `500` error #262
