### ISSUE TITLE
The request failed: Google returned a response with code 500.

### ISSUE THREAD

**Issue by meiretest** [GeneralMills/pytrends#262]
Hi people I am getting this error shown in title issue with the following code (in bold):

`   pytrends = TrendReq(hl=language)`
`   pytrends.build_payload(kw_list=keyword_list, timeframe=timeframe, geo=country, gprop=gprop)`
   **`interests_by_region = pytrends.interest_by_region()`**

I get this error (below) with any API method:
> ResponseError(The request failed: Google returned a response with code 500.)

I've previously seen in a post that this could be caused by the timeframe format that has changed recently. However I've already tried the two approachs with **'{past_time} {now}'** and **'{now} {past_time}'** and I'm still getting the same error. Does someone know how to solve this problem? Thanks.

**Comment by dabdada** [comment]
Could you provide all the parameters you are setting? e.g. hl='en,' kw_list=['keyword', ], timeframe='today 1-y', geo='US', gprop=<some props>

Or a python file with this information so we can reproduce the error and check what is going on?

Thanks

**Comment by meiretest** [comment]
I'm setting this following parameters: 

`hl='en', kw_list['tylenol'], timeframe='all', geo='US', gprop='web'`

`pytrends = TrendReq(hl=language)`
`pytrends.build_payload(kw_list=keyword_list, timeframe=timeframe, geo=country, gprop=gprop)`
`interests_by_region = pytrends.interest_by_region()`

Thanks.

**Comment by rsmahabir** [comment]
Yep, getting the same issue.

**Comment by dabdada** [comment]
it seems that gprop="web" is not a valid argument anymore. If I go to trends.google.com though, it is preselected without a parameter in the querystring, so I guess not setting it (or setting gprop='') will return web search by default. images, news, youtube is still working as a valid gprop.
