### ISSUE TITLE
Separate locations for each keyword

### ISSUE THREAD

**Issue by mcfly3001** [GeneralMills/pytrends#263]
The geo attribute currently seems only to allow a single string. It would be helpful though if for a list of search terms the location could individually be adjusted, similar to the node.js implementation. This is especially interesting if users want to compare a the same search term in different locations.

Any suggestions/feedback is welcome :-)

**Comment by mcfly3001** [comment]
Hi,
thanks for your feedback. Actually this feature is available in trends.google.com as well as in node.js-API. On trends.google.com it is a bit hidden though. You will have to enter the same search term twice and afterwards you will be able to change the "filter". The filter allows you to set different countries and timeframes.

**Comment by viktorreglin** [comment]
+1 from me, would very much like to have this feature implemented.

**Comment by Buedenbender** [comment]
+1 for me as well. For research purposes we want to compare the trends data for the same keyword in different regions.
