### ISSUE TITLE
No historical hour-level data pre-2015

### ISSUE THREAD

**Issue by MattieT6** [GeneralMills/pytrends#265]
I'm trying to get historical hour-level data on searches by US state over the period 2010-2018. However, when I run the script with time parameters in "pytrends.get_historical_interest" that include any time period before Jan 1, 2015, the relevant data are not outputted. Any request that also covers more recent time periods includes the more recent data but then cuts off once 2014 is hit. 

As an example, I'm running the following now:

new_state = pytrends.get_historical_interest(kw_list, year_start=2014, month_start=12, day_start=20, hour_start=0, year_end=2015, month_end=1, day_end=20, hour_end=0, cat=0, geo=state, gprop='', sleep=20)

Here the data don't start until midnight on Jan 3, 2015 (this must be the beginning of the week for that call).

Thanks very much! (And apologies in advance if this isn't sufficiently clear--I'm new to this.)

**Comment by dabdada** [comment]
I am not sure what you mean exactly, but if I visit https://trends.google.de/trends/explore?date=2014-08-09%202014-09-09&geo=US&q=data with the period set to somewhen in september 2014, i also get only daily data. I suspect google API does not deliver any more detailed data for >  3 year old timeslots.

Can anyone confirm this?

**Comment by MattieT6** [comment]
Thanks, that's exactly what I'm referring to. Is there a way for me to use the historical hourly data function to pull data at the daily level instead when working with a dataset that includes data > 3 years old? Right now the values are dropped altogether. 

I understand that I can still use the interest over time functionality over smaller time periods and just iterate accordingly, but ideally I'd like to be able to grab longer periods of time at once as the historical hourly data allows.

**Comment by dabdada** [comment]
I am sorry I think I have to let you down on this one, because interest over time also only gets daily data points for older data.

I see no way how we could retrieve data from google, if they do not even use it on their side.

**Comment by MattieT6** [comment]
Okay, thanks for your help!
