### ISSUE TITLE
ResponseError  when using top_charts

### ISSUE THREAD

**Issue by lienfali** [GeneralMills/pytrends#269]
`127.0.0.1 - - [11/Oct/2018 00:26:13] "POST /hottopics HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nilu/Assignment/templates/server/server.py", line 90, in hot_topics
    top_charts = pytrend.top_charts(date=201803, cid='software_technology')
  File "/usr/local/lib/python2.7/dist-packages/pytrends/request.py", line 344, in top_charts
    params=chart_payload,
  File "/usr/local/lib/python2.7/dist-packages/pytrends/request.py", line 101, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
ResponseError: The request failed: Google returned a response with code 404.
`
Getting a ResponseError when using top_chart.
I manage to retrieve data when cid is equal to actors or basketball_players. However, above mentioned error is thrown when searched on software_technology/software_technologies/software/etc.

The API states that cid must be one of the trends from the google trends page, but doesnt return data for inserted cid. Code snippet:
`@app.route('/hottopics', methods = ['POST'])
def hot_topics():
    req = request.get_json()
    keyword = req['trend']
    print 'this is keyword', keyword, type(keyword)

    pytrend = TrendReq()

    pytrend.build_payload(kw_list=[keyword])
    cats = pytrend.categories()
    print 'cats',cats

    # returns DataFramework
    top_charts = pytrend.top_charts(date=201803, cid='basketball_players')# basketball players/actors work, software_technology doesnt`

**Comment by JoseVigil** [comment]
Hi, same exact error here. 

`pytrend = TrendReq()

year = datetime.utcnow().strftime('%Y')
month = datetime.utcnow().strftime('%m')
mt = int(month) - 4
sm = ""

if mt <= 9:
    sm = "0" + str(mt)
else:
    sm = str(mt)

date = year + sm

top_games = pytrend.top_charts(cid="basketball_players", geo='US', date=date)
`

**Comment by lienfali** [comment]
Hi there! Issue is caused by the date. Last measure (data) is from march 2018. Response error is caused by missing data. You can retrieve data by passing a hardcoded 201803. Goodluck!

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by lienfali** [comment]
Btw, this ticket may be closed. Cid which was required was found in the URL. It wasn't software technologies, it was programming_language.

Also, data is not year to date. Its missing data for the last 7 months (now October 2018). Hence the response error.

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by JoseVigil** [comment]
Appreciate the fast response Lien.

I am wondering why there is only until march available for API when I see Sept online. 

https://trends.google.com/trends/explore?q=games&geo=US

Working now until March. Fixed.

**Comment by lienfali** [comment]
You're welcome! However, seems you are looking at the page with related topics. Queries etc. The top_charts method from pytrends is the equal of hot trends of google (default geo US in pytrends):

https://trends.google.com/trends/topcharts#geo=US&date=201803

You see, this link shows march 2018 as last measure.

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________
