### ISSUE TITLE
Cannot parse GALX out of login page running example.py

### ISSUE THREAD

**Issue by mrkristofer** [GeneralMills/pytrends#27]
Hi, I tried running example.py with valid creds but am getting an exception saying it "Cannot parse GALX out of login page".

**Comment by dreyco676** [comment]
Hmm. I'm not able to reproduce this. Could it be that maybe you have two-factor authentication on for your gmail account? You may need to approve the login attempt.

**Comment by dreyco676** [comment]
Fixed the regex and is working on my end. Let me know if the issue continues.
