### ISSUE TITLE
Response Error for a very specific time range

### ISSUE THREAD

**Issue by yetisir** [GeneralMills/pytrends#270]
I've been scratching my head over this one for days and am unsure about the root cause of this error.

I am queerying historical trends for the last several years in 5 day chunks and every timreange seens to work fine except for 1 (Sept 29 2018 - Oct 4 2018).

This isnt limited to a specific keyword, as i have tried at least a dozen different keywords all with the same issue. 

I get a response code 500 when i try to query this timerange, but no issues when queering the timerange on either side. my first thought was that google did have any data during this time period, but i am able to queert each day within the timerange individually with out issue. 

See below for MWE code.

```
# MWE
from pytrends.request import TrendReq
pytrend = TrendReq()

# This doesn't work (5 day period btwn Sept 29 and Oct 4 2018)
pytrend.build_payload(['test'], timeframe='2018-09-29T00 2018-10-04T00')
data = pytrend.interest_over_time()

# This works (4 days prior with one day overlap)
pytrend.build_payload(['test'], timeframe='2018-09-25T00 2018-09-30T00')
data = pytrend.interest_over_time()

# This works (4 days after with one day overlap)
pytrend.build_payload(['test'], timeframe='2018-10-03T00 2018-10-08T00')
data = pytrend.interest_over_time()

# This works (queerying each day individually)
pytrend.build_payload(['test'], timeframe='2018-09-29T00 2018-09-30T00')
data = pytrend.interest_over_time()
pytrend.build_payload(['test'], timeframe='2018-09-30T00 2018-10-01T00')
data = pytrend.interest_over_time()
pytrend.build_payload(['test'], timeframe='2018-10-01T00 2018-10-03T00')
data = pytrend.interest_over_time()
pytrend.build_payload(['test'], timeframe='2018-10-02T00 2018-10-03T00')
data = pytrend.interest_over_time()
pytrend.build_payload(['test'], timeframe='2018-10-03T00 2018-10-04T00')
data = pytrend.interest_over_time()
```

**Comment by yetisir** [comment]
Update: the above code now works, BUT - if we shift the dates by 9 days (time difference between this post and the original), we see the exact same behaviour:


`# MWE
from pytrends.request import TrendReq
pytrend = TrendReq()

# This doesn't work (5 day period btwn Sept 29 and Oct 4 2018)
pytrend.build_payload(['test'], timeframe='2018-10-08T00 2018-10-013T00')
data = pytrend.interest_over_time()

# This works (4 days prior with one day overlap)
pytrend.build_payload(['test'], timeframe='2018-10-04T00 2018-10-09T00')
data = pytrend.interest_over_time()

# This works (4 days after with one day overlap)
pytrend.build_payload(['test'], timeframe='2018-10-12T00 2018-10-17T00')
data = pytrend.interest_over_time()

# This works (queerying each day individually)
pytrend.build_payload(['test'], timeframe='2018-10-08T00 2018-10-09T00')
data = pytrend.interest_over_time()
pytrend.build_payload(['test'], timeframe='2018-10-09T00 2018-10-10T00')
data = pytrend.interest_over_time()
pytrend.build_payload(['test'], timeframe='2018-10-10T00 2018-10-11T00')
data = pytrend.interest_over_time()
pytrend.build_payload(['test'], timeframe='2018-10-11T00 2018-10-12T00')
data = pytrend.interest_over_time()
pytrend.build_payload(['test'], timeframe='2018-10-12T00 2018-10-13T00')
data = pytrend.interest_over_time()
`

**Comment by yetisir** [comment]
after a little more testing, it seems to be the same issue when querying an interval that returns hourly data where the datetime of (now - 2 weeks) is included in the query interval. querying over the same interval but non-hourly data seems to be ok.

**Comment by Abello966** [comment]
I'm having the same issue. I only got the (now - 2 weeks) pattern because of your post, thanks
