### ISSUE TITLE
When using 'now 7-d' I get hourly data -- can not get the last days by any form

### ISSUE THREAD

**Issue by jaguifi** [GeneralMills/pytrends#274]
Hello,
I am trying to get daily data of the last 7 days. When I use the following code I get hourly data when I should get daily because of the formula.
This is the code I am using:

`kw_list = ['pizza']`
`pytrend = TrendReq()`
`categoria="0" `
`timeframe='now 7-d'`
`pytrend.build_payload(kw_list=kw_list, timeframe = timeframe,cat=categoria)`
`interest_over_time_df = pytrend.interest_over_time()`

I just want to get the last days in daily data, but there is no way, am I doing something wrong?

I also tried the following code, but it just gives a dataframe with only the last 4yh day (note that the day I am executing this is 2018, 11, 2, today´s date) :

`kw_list = ['pizza']`
`start_date = datetime(2018, 10, 29).date()`
`end_date=datetime(2018, 11, 2).date()`
`pytrend = TrendReq()`
`categoria="0" `
`timeframe = start_date.strftime('%Y-%m-%d')+' '+end_date.strftime('%Y-%m-%d')`
`pytrend.build_payload(kw_list=kw_list, timeframe = timeframe,cat=categoria)`
`interest_over_time_df = pytrend.interest_over_time()`

If you could help, it would be great.

Thank you.

**Comment by KiransHub** [comment]
Closed without any details?!

**Comment by dreyco676** [comment]
@KiransHub Sorry we had a ton of PR's get merged and ton of stale issues. We needed a clean slate, many questions like these are either already solved by their owners or not applicable to the current package. If they are I'm happy to reopen them.

**Comment by vbadita** [comment]
@KiransHub Apparently Google shows for 7-d data as hourly so the only way to get last 7 days is to retrieve data for the past month and manipulate the DataFrame to select the first 7 lines (days).

See below an example:

   ```
 kw_list = ['pizza']
 pytrend = TrendReq()
 categoria="0" 
 timeframe='today 1-m'
 pytrend.build_payload(kw_list=kw_list, timeframe = timeframe,cat=categoria)
 interest_over_time_df = pytrend.interest_over_time()
 interest_over_time_df['date'] = interest_over_time_df.index
 result = interest_over_time_df.sort_values(by='date',ascending=False)
 print(result.head(7))
```
