### ISSUE TITLE
Incomplete hourly data with get_historical_interest

### ISSUE THREAD

**Issue by awestley** [GeneralMills/pytrends#277]
So this code works fine. It returns all of February and the first hour of March. 
```
kw_list = ["Lockheed"]

historical_results_feb = pytrends.get_historical_interest(kw_list, year_start=2018, month_start=2, day_start=1, hour_start=0, year_end=2018, month_end=3, day_end=1, hour_end=0, cat=0, geo='', gprop='', sleep=5)

historical_results_feb.to_csv('feb-works.csv')
```
I have noticed that when running a similar command it appears that the last few days worth of data are missing. No errors or 500 codes are returned.
```
historical_results_feb = pytrends.get_historical_interest(kw_list, year_start=2018, month_start=2, day_start=1, hour_start=0, year_end=2018, month_end=2, day_end=28, hour_end=23, cat=0, geo='', gprop='', sleep=5)

historical_results_feb.to_csv('feb-missing.csv')
```

Here are the results. Rename txt to csv since github doesn't allow uploading .csv files.

[feb-works.txt](https://github.com/GeneralMills/pytrends/files/2558843/feb-works.txt)
[feb-missing.txt](https://github.com/GeneralMills/pytrends/files/2558844/feb-missing.txt)

**Comment by gbuchbi** [comment]
I have the same problem, and I believe it's because intervals have to be of 7 days as it says in line 406 of request.py, and the code is rounding down the number of weeks, instead of up.
