### ISSUE TITLE
Trending Searches Not Working

### ISSUE THREAD

**Issue by aamazie** [GeneralMills/pytrends#279]
I am getting a 404 Error when calling the trending_searches function. Anyone having an issue?

The error:

    pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 404.

My code:

    trends = pytrends.trending_searches(pn='p1')

    print(trends)

**Comment by jrmlhermitte** [comment]
The url seems to not exist anymore:
```
ipdb> p TrendReq.TRENDING_SEARCHES_URL
'https://trends.google.com/trends/hottrends/hotItems'
```

Is there a quick fix for this? Maybe updating url?

**Comment by darkzbaron** [comment]
same here, it stopped working!

**Comment by SleepyGinger** [comment]
I made [google_trends.py](https://github.com/SleepyGinger/google_trends) for whoever is interested to use.

**Comment by Macatho** [comment]
> I made [google_trends.py](https://github.com/SleepyGinger/google_trends) for whoever is interested to use.

You can scroll with selenium btw.
