### ISSUE TITLE
unable to include geo code using inc_geo_code 

### ISSUE THREAD

**Issue by smanne2** [GeneralMills/pytrends#284]
As I try to set 'inc_geo_code' to 'True' for 'intrest_by_region',  I get a TypeError: interest_by_region() got an unexpected keyword argument 'inc_geo_code'

![image](https://user-images.githubusercontent.com/43011644/48957179-0f0ae200-ef25-11e8-87ba-23bc1880314d.png)

**Comment by pykcel** [comment]
Hi @smanne2, I believe the error comes from the outdated default version of `pip install pytrends`. One work around is to install the last version from git itself:
`pip install https://github.com/GeneralMills/pytrends/archive/master.zip`
