### ISSUE TITLE
get_historical_interest is double counting data points

### ISSUE THREAD

**Issue by e-271** [GeneralMills/pytrends#287]
Every week, get_historical_interest duplicates one data point. See here:

```
2015-01-07 23:00:00,27,False
2015-01-08 00:00:00,28,False
2015-01-08 00:00:00,22,False
2015-01-08 01:00:00,20,False
2015-01-08 02:00:00,21,False
```

[zuck.txt](https://github.com/GeneralMills/pytrends/files/2730218/zuck.txt)

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by sohilsshah91** [comment]
How did you get historical interest over time data. I tried it and I am getting Error 429. I have upgraded the pytrends library. Could you please share any snippet of code you used and dependencies or libraries used?

Thank You!
Regards,
Sohil Shah

**Comment by e-271** [comment]
Can you share the code you are using to request, and the full error message?

**Comment by jtaylor351** [comment]
You need to know the scores of the last hour of the previous week and the first hour of the next week to normalize the scores. I argue it is a feature and not a bug, because without it one week isn't comparable to another week because the scores in one week are computed relative to the highest popularity in the one week time window you are looking at. 

In other words, notice the first score at  2015-01-08 00:00:00 is 28 and the second score at 2015-01-08 00:00:00 is 22. This means the score at 2015-01-08 01:00:00 of 20 relative to the previous week is (20 * 28) / 22 = 25.45
