### ISSUE TITLE
Fetching 61months of data gives weekly stats

### ISSUE THREAD

**Issue by nwillems** [GeneralMills/pytrends#29]
Hi there.

With regards to the date parameters, I think the documentation should be updated. I have just fetched a good portion of keywords, and it seems that the "API" is not consistent :-(. I don't know what to write, and I unfortunately don't have the time to investigate further.

```Python
def download_report(words, downloader):
    default_date = "1/2011 61m"
    default_geo = "DK"

    terms = ', '.join(words)

    downloader.request_report(terms, geo=default_geo, date=default_date)
    downloader.save_csv('./queries/', terms.replace(", ", "_"))
```

See the two attached files as an example, both files are produced from the above code.
[11_beskyttelse_1_indført.txt](https://github.com/GeneralMills/pytrends/files/148060/11_beskyttelse_1_indfort.txt)
[tilfælde_hpv-vaccine_doser_stivkrampe.txt](https://github.com/GeneralMills/pytrends/files/148059/tilfaelde_hpv-vaccine_doser_stivkrampe.txt)

**Comment by dreyco676** [comment]
It looks like the search volume for some of those terms is really tiny. I think rather than report all zeros google tries to help by showing the weeks in which they peak. My suggestion would be to add a term that you know will have a large search volume and use it to help 'force' it to months.

**Comment by dreyco676** [comment]
I'll put a disclaimer up in the documentation. Sorry for the issue.
