### ISSUE TITLE
TRENDING_SEARCHES_URL become OLD

### ISSUE THREAD

**Issue by MShaaban52** [GeneralMills/pytrends#290]
in file requests,py : 
 
   TRENDING_SEARCHES_URL = 'https://trends.google.com/trends/hottrends/hotItems'
become OLD and this is the new link : 
https://trends.google.com/trends/trendingsearches/daily?geo=US

and it affects :  trending_searches() function ..
how to solve this problem ??

**Comment by Poomikak** [comment]
Did you figure this one out? Seems like almost all the URLs has changed.

**Comment by datainvestor** [comment]
trending_searches() function does not work because of this. URL has changed, any way to fix this?

**Comment by vbadita** [comment]
https://github.com/GeneralMills/pytrends/pull/305
