### ISSUE TITLE
Queries without a search term

### ISSUE THREAD

**Issue by blaughish** [GeneralMills/pytrends#292]
Hi!  I was wondering if it is possible to have a null kw_list so that it pulls in the top searches for any given category.  Thinking this could potentially be a good alternative to top charts?

An example of a URL is: https://trends.google.com/trends/explore?cat=47&date=today%201-m&geo=US&gprop=youtube

**Comment by dodecafonico** [comment]
I am also very interested in this

**Comment by rushi-kb** [comment]
+1
