### ISSUE TITLE
All URLs updated in request.py

### ISSUE THREAD

**Issue by Poomikak** [GeneralMills/pytrends#295]
Seems like all the URLs in the request.py has been changed. My code is returning 404. Anyone who knows how to find the new ones? 

I am quiet new with Python, and unsure if I can just copy the link from user point of view, or is all the links speciel ones?

**Comment by Poomikak** [comment]
@dreyco676 can you maybe help me with this one? It is all the URLs in the request.py that is giving error

**Comment by dreyco676** [comment]
We had multiple PR that got merged recently. Please review to see if they have fixed any of your concerns. If not please reopen the issue.
