### ISSUE TITLE
List of Response Codes and their meanings?

### ISSUE THREAD

**Issue by Abello966** [GeneralMills/pytrends#299]
Does anyone know the general meaning of the different response codes?
It seems that 400 means invalid parameters
Some people are getting 500 for specific time ranges 
What is the ResponseCode for exceeding the rate-limit? Are there other codes with different meanings? I'd like to try to write code that treats each of these individually

**Comment by dodecafonico** [comment]
I get error -> ResponseError('The request failed: Google returned a response with code 400.')

I get this error after having called exactly 92 times pytrends.interest_over_time(). I have tried using proxies, changing tor ip identities, etc... always same error after same number of calls

so my guess is that error 400 is directly related to the exceeding of quota limit

**Comment by Abello966** [comment]
>so my guess is that error 400 is directly related to the exceeding of quota limit.

Great, thanks!

>Not  sure why you say that it means invalid parameters

Oh I was just summarizing what I found on the other issues. For example, using an hour descriptor for a search with a time-span greater than 1 week is prohibited, so it generates a 400 error:

`from pytrends.request import TrendReq`
`search = TrendReq(hl="en-US", tz=0)`
`kw_list = ["Blockchain"]`
`search.build_payload(kw_list, cat=0, timeframe="2018-02-01T00 2018-02-09T00")`

-> pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.

**Comment by dreyco676** [comment]
We had multiple PR that got merged recently. Please review to see if they have fixed any of your concerns. If not please reopen the issue.
