### ISSUE TITLE
Script stopped working.. 400 Bad Request error

### ISSUE THREAD

**Issue by ravimevcha** [GeneralMills/pytrends#30]
I have been using this python script for long now... suddenly today this script stopped working. I am getting 400 Bad Request error and now able to download any Google Trend CSV file from the script.. 

Getting error for Connector as well.  "connector = pyGTrends(google_username, google_password)" 

I think this is the main issue.

**Comment by ravimevcha** [comment]
@dreyco676 @bdewilde  can you guys please help resolve this issue. Really appreciate your help.

**Comment by bdewilde** [comment]
The good and bad news is, I can reproduce this error. This part of the code was heavily borrowed from somewhere else, I believe. @dreyco676, any ideas what's gone wrong?

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-7-199aefb15b6f> in <module>()
----> 1 connector = pyGTrends(user, pw)

/Users/burtondewilde/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pytrends/pyGTrends.py in __init__(self, username, password)
     49         self.url_CookieCheck = 'https://www.google.com/accounts/CheckCookie?chtml=LoginDoneHtml'
     50         self.url_PrefCookie = 'http://www.google.com'
---> 51         self._connect()
     52
     53     def _connect(self):

/Users/burtondewilde/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pytrends/pyGTrends.py in _connect(self)
     73         params = urlencode(self.login_params).encode('utf-8')
     74         self.opener.open(self.url_ServiceLoginBoxAuth, params)
---> 75         self.opener.open(self.url_CookieCheck)
     76         self.opener.open(self.url_PrefCookie)
     77

/Users/burtondewilde/.pyenv/versions/3.5.0/lib/python3.5/urllib/request.py in open(self, fullurl, data, timeout)
    469         for processor in self.process_response.get(protocol, []):
    470             meth = getattr(processor, meth_name)
--> 471             response = meth(req, response)
    472
    473         return response

...
```

**Comment by ravimevcha** [comment]
@bdewilde seems like some cookie or google authentication issue. It would be great if you can help fix this issue. Appreciate your help.

**Comment by ravimevcha** [comment]
@bdewilde  @dreyco676  - any luck with this issue? my research project is literally stuck because of this... I have tried to use other python script but none is working fine. This script is the best one which was working flawlessly. I would really appreciate if you can help solve this issue and get script running again.

**Comment by dreyco676** [comment]
Not sure when I'll get time to work on this. I just switched roles at my
company and am slammed with work.

**Comment by ravimevcha** [comment]
@dreyco676 can you give some logic about the code or why this issue is occurring.... may be I or @bdewilde  can debug and try to solve the issue

**Comment by ravimevcha** [comment]
Also, if not possible to fix the issue, it would be great if you guys can suggest some alternate script which is working...

**Comment by dreyco676** [comment]
I guess my best alternative suggestion would be to use selenium webdriver
to automate the pytrends webpage. I'll see if I can take a look at this
tonight, no promises and definitely no ETA on a fix until I can figure out
what's going on.

**Comment by dreyco676** [comment]
Are you both using python 3.5? I don't get this error when I try to run it.

**Comment by ravimevcha** [comment]
@dreyco676 ... Yes I am using Python 3.5.1... I think @bdewilde was also able to replicate this error

**Comment by ravimevcha** [comment]
@dreyco676 I am getting the error... attached screenshot for reference. are you able to run script without any error and download the Google Trend file?

![python error](https://cloud.githubusercontent.com/assets/8564222/13593124/aca65bca-e51e-11e5-923e-3cad66a03d9e.png)

**Comment by dreyco676** [comment]
Yes I'm able to get it to work on 3.4. I'll try 3.5 today.

**Comment by dreyco676** [comment]
Hmm. I'm on Python 3.5.1 :: Anaconda 2.5.0 (64-bit) and get no error running the script.

I did realize I forgot to upload some minor changes to PyPi so if you installed the script with Pip you may have missed those small updates. Update by doing "pip install pytrends --upgrade"

**Comment by ravimevcha** [comment]
@dreyco676  @bdewilde - Thanks a lot... script started working now... many thanks.. really appreciate your support.
