### ISSUE TITLE
Where to specify google account credential ? 

### ISSUE THREAD

**Issue by howardx** [GeneralMills/pytrends#300]
Hi there, great work and thanks for the contributions !

One question, I've done similar work on my own and in my code I always first sign on to google with a gmail account and password. And from earlier issues I see that your code used to support this as well. 

However with the latest version ( I pulled from master ), seems TrendReq class is no longer taking google account credential in its constructor - https://github.com/GeneralMills/pytrends/blob/master/pytrends/request.py#L38

So how can we "log-in" to google without a set of user name and password ? I ran your example and saw a "cookie" in TrendReq object - is this a replacement of username password ? How is it generated every time and will it always be the same ? 

Many thanks for your help - sorry if the question seems naive as I'm new to web scraping. 

Howard

**Comment by goshetovan** [comment]
I would like to know the same thing :) Thanks a lot for the work!

**Comment by dreyco676** [comment]
We had multiple PR that got merged recently. Please review to see if they have fixed any of your concerns. If not please reopen the issue.

**Comment by diggyg97** [comment]
bump. want to know as well
