### ISSUE TITLE
Monthly granularity: mean value for the month?

### ISSUE THREAD

**Issue by JPFrancoia** [GeneralMills/pytrends#306]
Hi, I just have a quick question:

When pytrends returns monthly data, (let's say I queried with the timeframe: `2014-01-01 2019-03-01`), I have data like this:

```
2014-01-01 value
2014-02-01 value
...
```

These monthly values, are they the mean for each month, or the values for the first day of each month?

**Comment by SonnyDriscoll** [comment]
This will be total for the month compared to total monthly searches by geographic region. Please see this post for more details https://ahrefs.com/blog/how-to-use-google-trends-for-keyword-research/

**Comment by SonnyDriscoll** [comment]
In the case you are searching trend data for a single keyword, I believe these will be total values for the month, calculated against total search volumes for that geographic region. Check out this link for more details on this https://ahrefs.com/blog/how-to-use-google-trends-for-keyword-research/

**Comment by dreyco676** [comment]
We had multiple PR that got merged recently. Please review to see if they have fixed any of your concerns. If not please reopen the issue.
