### ISSUE TITLE
Regarding Closed Issues

### ISSUE THREAD

**Issue by dreyco676** [GeneralMills/pytrends#307]
We had multiple PR that got merged recently. Please review to see if they have fixed any of your concerns. If not please reopen the issue.

This project is not as well maintained as I'd like it to be. If you have interest in being a maintainer please let me know.

**Comment by TickTack-z** [comment]
> We had multiple PR that got merged recently. Please review to see if they have fixed any of your concerns. If not please reopen the issue.
> 
> This project is not as well maintained as I'd like it to be. If you have interest in being a maintainer please let me know.

Hi dreyco676,

Do you still need help for maintaining the repository?

**Comment by dreyco676** [comment]
@TickTack-z I'll add you right now! Maybe coordinate with @emlazzarin as he has been doing a lot of maintenance lately. Do you have a handle on PyPI as well for updating the package?

**Comment by TickTack-z** [comment]
> @TickTack-z I'll add you right now! Maybe coordinate with @emlazzarin as he has been doing a lot of maintenance lately. Do you have a handle on PyPI as well for updating the package?

Yep. I got the latest version and will coordinate with @emlazzarin on this.

**Comment by Matt-Simpson-Chi** [comment]
Having working in finance, working on open source was verboten so I have no history.  Will be glad to help if needed though.

**Comment by dreyco676** [comment]
Thanks @Matt-Simpson-Chi we'd love the help! I'd coordinate with @TickTack-z and @emlazzarin, do a PR for any bugs/feature adds and assuming that all goes well we can look at adding you as a collaborator.

**Comment by rheophile10** [comment]
I'd be happy to help maintain this repository, starting with writing some pytests.
