### ISSUE TITLE
The request failed: Google returned a response with code 500.

### ISSUE THREAD

**Issue by tomato82** [GeneralMills/pytrends#309]
pytrends: version 4.6.0
python: version 3.7.1

I've been consistently getting this error.  My code looks loops through the past 300 days and gets weekly data from each date.  It always works fine for the last week, but has issues for about 5 days and then works again (see picture).

![image](https://user-images.githubusercontent.com/50928802/58358388-ac9b8b80-7e4c-11e9-9110-57d8529d2f73.png)

I tried to run alone outside the loop using date (2019-05-09T12 2019-05-16T12) and I get the same results.
![image](https://user-images.githubusercontent.com/50928802/58358608-a3f78500-7e4d-11e9-9dc9-43c6e1485aa2.png)

![image](https://user-images.githubusercontent.com/50928802/58358441-e8ceec00-7e4c-11e9-9486-1567065d5cd5.png)

If I change the date range by 1 (2019-05-10T12 2019-05-17T12) it works
![image](https://user-images.githubusercontent.com/50928802/58358586-8a563d80-7e4d-11e9-8f32-7edbc5c9de86.png)

**Comment by tomato82** [comment]
I tried to run these dates directly in Google Trends and it appears to be a Google Trends issue.

Date range that gives 500 error for pytrends.
![image](https://user-images.githubusercontent.com/50928802/58513544-b1727f00-816d-11e9-8387-a36db117f76e.png)

Date range that works for pytrends.
![image](https://user-images.githubusercontent.com/50928802/58513612-d0711100-816d-11e9-8482-520a21cc7f16.png)

**Comment by tomato82** [comment]
I tried in gtrendsR and it has the same issue.  This seems like a systemic Google Trends issue.

![image](https://user-images.githubusercontent.com/50928802/58557945-98111780-81ed-11e9-9680-43e1ac6a3fe1.png)

**Comment by vbadita** [comment]
I believe this has nothing to do with pytrends. 
This should be closed.

**Comment by tomato82** [comment]
Agreed, closing.
