### ISSUE TITLE
How can I get the date value out of Pandas?

### ISSUE THREAD

**Issue by KiransHub** [GeneralMills/pytrends#310]
I tried the following in a notebook: 

```
resultsDf = pytrends.get_historical_interest(['nodejs'], year_start=2018, month_start=1, day_start=1, hour_start=0, year_end=2018, month_end=2, day_end=1, hour_end=0, cat=0, geo='', gprop='', sleep=0)

resultsDf.head(4)['nodejs']

```

I get a list of dates: 
date
2018-01-01 00:00:00    17
2018-01-01 01:00:00    20
2018-01-01 02:00:00    21
2018-01-01 03:00:00    24
Name: nodejs, dtype: int64

but I can't seem to get the actual values for each date? I want to be able to split the dates into day month year etc... but I don't know how to access the values. 

I can't seem to do this: 
`
resultsDf.head(4)['date']
`
Any it doesn't appear to have a date column but when I print the dataframe date appears there with the other columns?

**Comment by jonrtaylor** [comment]
I believe the date column is the index, so:

`resultsDf.reset_index(inplace=True)`

`resultsDf.date`

should work just fine.

**Comment by dreyco676** [comment]
Looks like this is resolved. Closing for now. Reopen if not the case.
