### ISSUE TITLE
How to pull yesterday's daily trend value on the 1 month?

### ISSUE THREAD

**Issue by ewilk0** [GeneralMills/pytrends#312]
Hi, this repo is amazing in its capability but I can't seem to find a way to pull yesterday's daily value on the monthly chart (not on the site or through the library). For example, today is June 18 but the latest value I can get is June 15 when I need June 17's closing value. Is this possible? Thanks.

**Comment by vbadita** [comment]
I know, it's annoying but we cannot do much. Unless the data from the last 7 days is worth to be processed.
Try to send them a feedback about the 1 month run.
