### ISSUE TITLE
GetNewProxy function is wrong for increment proxy index

### ISSUE THREAD

**Issue by mxmaxi007** [GeneralMills/pytrends#313]
A problem was found in the "GetNewProxy" function of request.py. 
` def GetNewProxy(self):`
        `"""`
       ` Increment proxy INDEX; zero on overflow`
        `"""`
        `if self.proxy_index > len(self.proxies) - 1:`
           ` self.proxy_index += 1`
     `   else:`
           ` self.proxy_index = 0`
First judgement should be `self.proxy_index < len(self.proxies) - 1`

**Comment by thomco** [comment]
I found the same issue.   With this bug, pytrends will always use the first proxy in the list.
@mxmaxi007 : Are you going to do a PR?

**Comment by emlazzarin** [comment]
This is now fixed in #329.
