### ISSUE TITLE
Adding realtime search trends support

### ISSUE THREAD

**Issue by mansiganatra** [GeneralMills/pytrends#314]
Is there a plan to add an api to support the realtime search trends as in the js api : https://github.com/pat310/google-trends-api/issues/99#issuecomment-443531056 ?

**Comment by mansiganatra** [comment]
Added code for above functionality at : https://github.com/mansiganatra/pytrends

**Comment by emlazzarin** [comment]
If you submit a clean PR I think we can add this functionality.
