### ISSUE TITLE
Getting regional codes?

### ISSUE THREAD

**Issue by inabawhite** [GeneralMills/pytrends#315]
Hi,

So I am working on some research where I need historic trends by region for many different countries. Unfortunately, there doesn't seem to be any way for me to generate a list of regional codes for each country so I have to go to the google trends site and manually copy the codes. Is there any way to pull this data automatically through the API? I suppose, alternatively, I could run a try except loop for every two letter combination but this is not very elegant either. Thanks for your consideration.

**Comment by vbadita** [comment]
this can help:

https://sites.google.com/site/tomihasa/google-language-codes

**Comment by inabawhite** [comment]
Thank you. I did end up just using a for loop and try except to get everything, which worked out fine. 

Just for the record, however, it looks to me like these are primarily language codes rather than region codes. One region code might be (for example) IN-NL for the country of India and the region of Nagaland. 

Thanks again for your post though.
