### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas.io.json.normalize'

### ISSUE THREAD

**Issue by kubilaykilinc** [GeneralMills/pytrends#317]
I have pandas, lxml, numpy, json modules. But i've got this error when i run example codes of pytrends.

ModuleNotFoundError: No module named 'pandas.io.json.normalize'

**Comment by geetanshjindal** [comment]
getting same error
python version: Python 3.6.8

**Comment by geetanshjindal** [comment]
fixed, Thanks :)

**Comment by kubilaykilinc** [comment]
Fixed. Thanks
But i've got another error new one.

Traceback (most recent call last):
  File "d:\PythonProjects\SocialMining\googleTrends.py", line 14, in <module>
    top_charts_df = pytrend.top_charts(2019, hl='en-US', tz=300, geo='GLOBAL')
  File "C:\Users\wissen\AppData\Local\Programs\Python\Python37\lib\site-packages\pytrends\request.py", line 433, in top_charts
    params=chart_payload,
  File "C:\Users\wissen\AppData\Local\Programs\Python\Python37\lib\site-packages\pytrends\request.py", line 144, in _get_data
    response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 404.

**Comment by NicePit** [comment]
> fixed, Thanks :)

Hi, I've got now the same problem with pandas version 0.25. I didn't see any fix in the import statement yet nor on pypi not in the repo. Can you estimate when you'll publish a new version? Thanks

**Comment by sfranchois** [comment]
same here. going back to 0.24.1 fttb

**Comment by sarach4erudite** [comment]
Update your Pandas module, it can help.
Running  :
 
conda install -c anaconda pandas

**Comment by hatyar** [comment]
Updating pandas does not help here. I have pandas 0.25 and the only way I could get it to work was to manually change the pytrends code to import pandas.io.json._normalize. Not sure why this was changed by pandas but need to make a change in the code here as well for comparability.

**Comment by ksanderer** [comment]
Same error (pandas version `0.25.0`),  works correctly with `0.23.4`

**Comment by ChristinaLiu2017** [comment]
> Updating pandas does not help here. I have pandas 0.25 and the only way I could get it to work was to manually change the pytrends code to import pandas.io.json._normalize. Not sure why this was changed by pandas but need to make a change in the code here as well for comparability.

Hi, how do you change the pytrends code? Mine still doesn't work.

**Comment by hatyar** [comment]
After you install pytrends - look for the code on your local PC. In the directory there is a file called request.py.Change import pandas.io.json.normalize to import pandas.io.json._normalize.

It is ugly but works until general mills fixes the problem.

**Comment by ChristinaLiu2017** [comment]
> After you install pytrends - look for the code on your local PC. In the directory there is a file called request.py.Change import pandas.io.json.normalize to import pandas.io.json._normalize.
> 
> It is ugly but works until general mills fixes the problem.

It works! Thank you so much.

**Comment by emlazzarin** [comment]
I submitted a PR to fix this issue - hopefully @dreyco676 can merge.

**Comment by emlazzarin** [comment]
@bappaSoumya - that seems like an unrelated problem. Please don't post it here!

**Comment by emlazzarin** [comment]
This has been resolved with #328. Thanks!

**Comment by adesorme** [comment]
Getting this error (pandas 0.24.2)

**Comment by emlazzarin** [comment]
You need Pandas >=.25.

**Comment by adgrig** [comment]
> Getting this error, but now for ._normalize (pandas `0.24.2`). Looks like the new fix breaks it for those who need .normalize from another version?
> 
> `No module named 'pandas.io.json._normalize'`

Look for hatyar's response above (I'm pasting it below just as well) - you need to do that, but in reverse.

Hatyar:
"""After you install pytrends - look for the code on your local PC. In the directory there is a file called request.py.Change import pandas.io.json.normalize to import pandas.io.json._normalize.

It is ugly but works until general mills fixes the problem."""

What worked for me was to change **pandas.io.json._normalize** back to **pandas.io.json.normalize**

**Comment by sergiohzlz** [comment]
Solved with 
pip3 install pytrends==4.6.0

**Comment by jbxiang** [comment]
> 
> 
> getting same error
> python version: Python 3.6.8

install the latest Pandas 1.1.0 and everything is ok.
