### ISSUE TITLE
pytrend.interest_over_time() returns different values !

### ISSUE THREAD

**Issue by Trifa01** [GeneralMills/pytrends#319]
Hello,

I am trying to detect seasonality of google search on a set of key_words. When running the method interest_over_time() some times I get different values for the same key_words and same period of time. In fact when running the example kw_list=['pizza', 'bagel'] I get the same issue:

            pizza  bagel isPartial
date                              
2014-08-24     **63**      1     False

____________________________________________

            pizza  bagel isPartial
date                              
2014-08-24     **62**      1     False

ps: For my key_words the difference is more significant 

What could cause such a problem ? 

Thanks

**Comment by dsgerbc** [comment]
Google could return different values for the same request, if done of different days.  Data is sampled from a larger database, but the every request is cached to return the same thing during the same day.  Next day though you'd get a new random draw.
