### ISSUE TITLE
pandas 0.25.0 support

### ISSUE THREAD

**Issue by a-chugunov** [GeneralMills/pytrends#320]
**Error in pandas 0.25.0:**
ModuleNotFoundError: No module named 'pandas.io.json.normalize'

**FIX:**
Old:
from pandas.io.json.normalize import nested_to_record
New:
from pandas.io.json._normalize import nested_to_record

**Comment by toobaz** [comment]
(this should probably be reopened - it is only closed in https://github.com/GeneralMills/pytrends/pull/323 )
