### ISSUE TITLE
interest_over_time since a given date

### ISSUE THREAD

**Issue by ChGrenier** [GeneralMills/pytrends#326]
I collect data on a large number of keywords and these will need to be updated in the future. So I wonder if it is possible to do an interest_over_time not since 2014 but since another date (the last date retrieved the previous time)

**Comment by emlazzarin** [comment]
Is there something preventing you from looking at the code and figuring out a way to do this? The "Issues" section is for problems with the code - not for personal guidance.

**Comment by jpribyl** [comment]
@emlazzarin this feels like something that could be in the documentation to me? I think the real "issue" would be adding it to the documentation or `examples.py` to save future developers some heartache.

For now I guess a comment here works 🤷 
If you want a custom date then you can pass the param `timeframe=<str>` to the `build_payload` method (see examples.py)

For example:
```python
    pytrend.build_payload(kw_list=['pizza'], timeframe='2020-12-01 2020-12-15')
```
