### ISSUE TITLE
[Enhancement] Hot Trends

### ISSUE THREAD

**Issue by nicolas-raoul** [GeneralMills/pytrends#33]
It would be great to be able to access data from https://www.google.com/trends/hottrends

It is different from the currently implemented function, ehich requires knowing the search terms in advance. It helps _discover_ trendy search terms. Example:

> Request: What are the top trending searches in **2016**?  
> Response: **Meldonium** (300m searches), **Nate Diaz** (200m searches), etc

**Comment by dreyco676** [comment]
Interesting I'll take a look.

**Comment by nicolas-raoul** [comment]
(By the way, I heard about this tool from http://opendata.stackexchange.com/q/7391/754)

**Comment by dreyco676** [comment]
So I'm interested in adding this if it isn't terribly hard. Its a bit outside the wheelhouse of the rest of the package but I'll keep digging.

**Comment by dreyco676** [comment]
This is coming in the next version.
