### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas.io.json._normalize'

### ISSUE THREAD

**Issue by higuuu** [GeneralMills/pytrends#333]
I cannot import TrendReq.
The cause is that cannot import  pandas.io.json._normalize in request.py.
But I found that "Starting in 0.19.0, pandas no longer supports pandas.io.data or pandas.io.wb, so you must replace your imports from pandas.io with those from pandas_datareader" in formal refarence.
How should I do to solve this problem?
I write here my Error code.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c0b1a8c022b1> in <module>()
----> 1 from pytrends.request import TrendReq
      2 # API Connection
      3 pytrends = TrendReq(hl='ja-JP', tz=360)
      4 # Set the search keyword
      5 kw_list = ["Python"]

/usr/local/lib/python3.6/dist-packages/pytrends/request.py in <module>()
      9 import requests
     10 
---> 11 from pandas.io.json._normalize import nested_to_record
     12 from requests.adapters import HTTPAdapter
     13 from requests.packages.urllib3.util.retry import Retry

ModuleNotFoundError: No module named 'pandas.io.json._normalize'

**Comment by emlazzarin** [comment]
Update to Pandas >=0.25.0.

**Comment by higuuu** [comment]
Thanks for your returning.
I can do it!

**Comment by leo-smi** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-c079ff394193> in <module>()
      1 
      2 
----> 3 from pytrends.request import TrendReq
      4 import pandas
      5 

/usr/local/lib/python3.6/dist-packages/pytrends/request.py in <module>()
      9 import requests
     10 
---> 11 from pandas.io.json._normalize import nested_to_record
     12 from requests.adapters import HTTPAdapter
     13 from requests.packages.urllib3.util.retry import Retry

ModuleNotFoundError: No module named 'pandas.io.json._normalize'
