### ISSUE TITLE
How to get data by UK location 

### ISSUE THREAD

**Issue by lftuwujie** [GeneralMills/pytrends#334]
Hi there,

Could you please let me know how could I get the data by time (e.g. by hour) and UK locations?  Currently I am using 
**kw_list = ['chickenpox']
pytrends.build_payload(kw_list)
chickpox_uk = pytrends.get_historical_interest(kw_list,year_start=2019, month_start=1, day_start=1 , hour_start=0
                                 , year_end=2019, month_end=9, day_end=22, hour_end=0, cat=0
                                 ,  geo='GB-ENG')** to get data by hour, but couldn't get the corresponding locations.

Thanks for your kind help in advance

Jie

**Comment by diggyg97** [comment]
Why was this issue closed? Could you find the fix for this?
