### ISSUE TITLE
ConnectTimeout Error

### ISSUE THREAD

**Issue by KwanWaiChung** [GeneralMills/pytrends#335]
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=US (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000002A011B6C548>, 'Connection to trends.google.com timed out. (connect timeout=2)'))

I encountered the error showed above when running the sample code provided.

from pytrends.request import TrendReq

pytrends = TrendReq(hl='en-US', tz=360)
kw_list = ["Blockchain"]
pytrends.build_payload(kw_list, cat=0, timeframe='today 5-y', geo='', gprop='')

**Comment by emlazzarin** [comment]
It looks like your connection timed out. Is there any evidence there's an
issue with the code? What debugging steps have you performed?

**Comment by KwanWaiChung** [comment]
I didn't really debug too much. I ran the code in a different computer, same error too. Is there anything I can do to trace the problem? I assume it is working in your computer?

**Comment by emlazzarin** [comment]
Works for me. A timeout is probably an issue with your connection. Try a
different one.

**Comment by KwanWaiChung** [comment]
Ok sure, Thank you. I will try a different one first and close the issue for now since its not the problem of the code.
