### ISSUE TITLE
Is https://trends.google.com/trends/api/explore deprecated?

### ISSUE THREAD

**Issue by LuckCky** [GeneralMills/pytrends#336]
Hi!
I'm getting an error 'pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.'
And looks like page 'https://trends.google.com/trends/api/explore' does not exist anymore.
Does anyone have same problems or it's me only?

**Comment by emlazzarin** [comment]
Hey Alex - first, this GitHub isn't for debugging people's personal issues.
That being said, you haven't provided any code, or any of the debugging
steps you've already taken. Not only does that slow down fixing anything,
but it suggests you're asking for help selfishly without having tried
yourself first. Could you try to figure it out and post your notes?

The Trends API Explore link has been dead for a very long time - the Google
Trends API isn't officially supported. Like most Google projects, Google
Trends could be shut off any time, and we're at the mercy of a few bored
engineers.

**Comment by LuckCky** [comment]
Thank you for your reply.
My English isn't that good, so looks like I couldn't explain myself clear and you thought that I'm asking for help with debug, but I don't.
I have already figured out that url (https://trends.google.com/trends/api/explore) that have been working several weeks (not very long time) ago isn't working now.

As a collaborator you might know that pytrends code depends on this url, e.g. https://github.com/GeneralMills/pytrends/blob/master/pytrends/request.py#L29

And therefore some pytrends functionality stopped working too.

And my question was if this url not accessible by me only or by everyone?

**Comment by emlazzarin** [comment]
I just ran a bunch of my code and I'm not seeing any issues.

What exactly was working a few weeks ago but isn't working now? Are you going to that URL in your browser, or is it code you're running against the API?

**Comment by dreyco676** [comment]
Can you confirm version #?


________________________________

**Comment by LuckCky** [comment]
Hi @emlazzarin and @dreyco676 !
I upgraded to version 4.7.1 last Friday.

This line of code used to work several weeks ago:
`pytrends.build_payload(payload_list, timeframe='now 1-d')`

And it looks like it was my issue only.
Now it works again.
That's odd, but OK I think.

Thank you very much for your time.
