### ISSUE TITLE
"Rising" related topics instead of "Top"

### ISSUE THREAD

**Issue by danipolo** [GeneralMills/pytrends#337]
Hi,

I found this code and I'm trying to figure out how to get the related topics ordered by "Rising". Right now it looks like it's only available the Top numbers.

```
{'bitcoin':               mid                     title       type  value
0      /m/05p0rrx                   Bitcoin   Currency    100
1       /m/01d_1l                     Price      Topic     45
2        /m/09nqf      United States Dollar   Currency      4
3       /m/0bhr4z                     Value  Economics      2
4       /m/0cncxk                    Trader    Finance      2
5      /m/0vpj4_b            Cryptocurrency      Topic      2
6       /m/015wzt                     Chart      Topic      2
7       /m/02_vjy                    Wallet      Topic      2
8        /m/0ny80          Confidence trick      Topic      1
9   /g/11f1059m3c     Cryptocurrency wallet      Topic      1
10     /m/0wr3qjq                  Coinbase      Topic      1
11    /m/0138n0j1                Blockchain      Topic      1
12       /m/0242l                      Coin      Topic      1
13    /m/0108bn2x                  Ethereum      Topic      1
14       /m/0cldt  Automated teller machine      Topic      1
15       /m/0dvld              Kate Winslet    Actress      0
16      /m/01qmkt               White paper      Topic      0
17      /m/08x2nq                    Ledger      Topic      0
18       /m/06lpz                  Roulette       Game      0
19       /m/034dj                  Gambling      Topic      0
20      /m/0c131z                     Libra  Astrology      0
21      /m/02mxjp      Exchange-traded fund      Topic      0
22     /m/046632s   Biophysical environment      Topic      0
23       /m/0sxyn                     Short      Topic      0
```

And here's my code:

```
from pytrends.request import TrendReq

# Login to Google. Only need to run this once, the rest of requests will use the same session.
pytrend = TrendReq()

# Create payload and capture API tokens. Only needed for interest_over_time(), interest_by_region() & related_queries()
pytrend.build_payload(kw_list=['bitcoin'], timeframe='now 4-H', geo='GB', gprop='')

related_topics_dict = pytrend.related_topics()
print(related_topics_dict)
```

How can I see the rising only?

Thanks

**Comment by TickTack-z** [comment]
Actually I think it will print both rising terms and top terms, this is my output using your code: 
`{'bitcoin': {'rising':     value formattedValue  ...                        topic_title        topic_type
0    1000        +1,000%  ...                           Gambling             Topic
1    1000        +1,000%  ...  Application programming interface    Software class
2     800          +800%  ...                            Penguin              Bird
3     250          +250%  ...                           Exchange  Organized market
4     200          +200%  ...                   Tyler Winklevoss   Olympic athlete
5     200          +200%  ...            Cryptocurrency exchange             Topic
6     200          +200%  ...                        Billionaire             Topic
7     200          +200%  ...                        Forecasting             Topic
8     180          +180%  ...                           Loophole             Topic
9     180          +180%  ...                              eToro           Company
10    180          +180%  ...                   Winklevoss twins             Topic
11    150          +150%  ...                         Prediction             Topic
12    130          +130%  ...                             Broker             Topic
13     90           +90%  ...                           Ethereum             Topic
14     60           +60%  ...                       Bitcoin Cash             Topic
15     60           +60%  ...                        Bitcoin ATM             Topic
16     60           +60%  ...                             Ripple  Payment protocol
17     60           +60%  ...           Automated teller machine             Topic

[18 rows x 6 columns], 'top':     value formattedValue  hasData  ...      topic_mid               topic_title        topic_type
0     100            100     True  ...     /m/05p0rrx                   Bitcoin          Currency
1      26             26     True  ...      /m/01d_1l                     Price             Topic
2       4              4     True  ...       /m/09nqf      United States Dollar          Currency
3       2              2     True  ...     /m/0vpj4_b            Cryptocurrency             Topic
4       2              2     True  ...      /m/0cncxk                    Trader           Finance
5       2              2     True  ...      /m/0bhr4z                     Value         Economics
6       2              2     True  ...       /m/053rd                    Mining             Topic
7       2              2     True  ...     /m/0wr3qjq                  Coinbase             Topic
8       2              2     True  ...      /m/015wzt                     Chart             Topic
9       2              2     True  ...       /m/07br0                     Trade             Topic
10      2              2     True  ...      /m/02_vjy                    Wallet             Topic
11      2              2     True  ...       /m/0g_fl                Investment             Topic
12      2              2     True  ...      /m/078rys                    Ripple  Payment protocol
13      1              1     True  ...  /g/11d_wtvc5k              Bitcoin Cash             Topic
14      1              1     True  ...      /m/01klyk                Prediction             Topic
15      1              1     True  ...     /m/0_lgq95               Bitcoin ATM             Topic
16      1              1     True  ...       /m/0cldt  Automated teller machine             Topic
17      1              1     True  ...       /m/0ny80          Confidence trick             Topic
18      1              1     True  ...    /m/0108bn2x                  Ethereum             Topic
19      1              1     True  ...  /g/11f1059m3c     Cryptocurrency wallet             Topic
20      1              1     True  ...     /m/04q8cv5                  Exchange  Organized market
21      0             <1     True  ...     /m/03gjzw8                     eToro           Company
22      0             <1     True  ...     /m/0gvtvc1          Winklevoss twins             Topic
23      0             <1     True  ...     /m/03cc3gq                  Loophole             Topic
24      0             <1     True  ...       /m/034dj                  Gambling             Topic`

and check the dictionary:
`related_topics_dict['bitcoin'].keys()
dict_keys(['rising', 'top'])`
