### ISSUE TITLE
GitHub and pypi version mismatch

### ISSUE THREAD

**Issue by UJIN88** [GeneralMills/pytrends#338]
If I download the package through:

1) `pip install pytrends`

I get an older version than if I install the package directly through the repository with:

2) `pip install git+https://github.com/GeneralMills/pytrends`

The version numbers are the same, but the version installed through 1. contains outdated functions (e.g. `GetDailyData()` instead of the newer `get_daily_data()`).

Maybe it is possile to update the pypi package?

Thank you for this wonderful work!

**Comment by emlazzarin** [comment]
Yes I'll take care of this.
