### ISSUE TITLE
Error with pandas.io.json._normalize

### ISSUE THREAD

**Issue by shamitb** [GeneralMills/pytrends#341]
Trying to import TrendReq throws an error. Error message below:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-4e8aa36d6ac0> in <module>
      1 #from pytrends.request import TrendReq
----> 2 from pytrends.request import TrendReq
      3 from matplotlib import pyplot as plt
      4 import numpy as np
      5 import pandas as pd

/usr/zepl/miniconda3/lib/python3.6/site-packages/pytrends/request.py in <module>
     11 
     12 
---> 13 from pandas.io.json._normalize import nested_to_record
     14 from requests.packages.urllib3.util.retry import Retry
     15 

ModuleNotFoundError: No module named 'pandas.io.json._normalize'

**Comment by emlazzarin** [comment]
Please look at the numerous already closed diacussions on this.

Upgrade your Pandas version.

**Comment by shamitb** [comment]
Pandas has been upgraded. --upgrade - now it works fine. Thanks!
