### ISSUE TITLE
No module named _normalize

### ISSUE THREAD

**Issue by shamitb** [GeneralMills/pytrends#343]
Even after doing
!{sys.executable} -m pip install --upgrade pandas

I am getting this error when trying to import pytrends /  import TrendReq from pytrends

No module named _normalize

**Comment by emlazzarin** [comment]
After you upgrade Pandas with that command, what version of Pandas is
accessible in your code?

```
import pandas as pd
print(pd.__version__)
```

**Comment by emlazzarin** [comment]
After you upgrade Pandas with that command, what version of Pandas is
accessible in your code?

```python
import pandas as pd
print(pd.__version__)
```

**Comment by shamitb** [comment]
Suddenly started working now - was any code change made in last few minutes?
Pandas 0.25.2

**Comment by emlazzarin** [comment]
No, no changes. You were probably just running from an old environment. Thanks!
