### ISSUE TITLE
Interest by region seems to return different values on the same request sent a few mins apart 

### ISSUE THREAD

**Issue by stuartlynn** [GeneralMills/pytrends#348]
I have been trying to use the interest_by_region function by constructing the payload 
```python
pytrends.build_payload(kw_list, cat=0, timeframe='{} {}'.format(start_day,end_day), geo='US', gprop='')
```
then running 

```python 
pytrends.interest_by_region()
```

if I run this then wait a few minutes and run it again, I get different results which is weird. Any idea why the exact same function call, run a few mins apart would give different results?

Thanks

**Comment by TickTack-z** [comment]
The API will send request to Google and only return what Google returns. It is possible that Google updated the underling data. Can you provide the full code you tested? including the kw_list and start_day, end_day.

Thanks
