### ISSUE TITLE
pytrends possibly leaks password

### ISSUE THREAD

**Issue by yichuanwangsc** [GeneralMills/pytrends#35]
Someone accessed my account using my password minutes after I use this API.
It was a throw away account, but please be cautious!

**Comment by dreyco676** [comment]
What you probably got is an email from Google saying you logged in from
somewhere else. This the pytrends library logging you in to Google with the
python fake-useragent library to act as a random browser to access Google
Trends. Without this you would not be able to access Google Trends.

We do not have any phone home in the code and our code is all open to be
verified.

**Comment by yichuanwangsc** [comment]
I see. The only thing was google estimated my location to be somewhere very far away from me, using a different operating system. That's what got me a little bit suspicious. But maybe this is just part of the fake-useragtent work?

**Comment by dreyco676** [comment]
There is always the slim chance of coincidence but yes Fake-UserAgent is done randomly to prevent Google from blocking users as Bots.

**Comment by yichuanwangsc** [comment]
Good to know. Thank you for your answers!

**Comment by dreyco676** [comment]
Here is the section that is setting the UserAgent

```
        # provide fake user agent to look like a desktop brower
        self.fake_ua = UserAgent()
        self.headers = [
            ('Referrer', 'https://www.google.com/accounts/ServiceLoginBoxAuth'),
            ('Content-type', 'application/x-www-form-urlencoded'),
            ('User-Agent', self.fake_ua.chrome),
            ('Accept', 'text/plain')]
        self.url_ServiceLoginBoxAuth = 'https://accounts.google.com/ServiceLoginBoxAuth'
        self.url_Export = 'http://www.google.com/trends/trendsReport'
        self.url_CookieCheck = 'https://www.google.com/accounts/CheckCookie?chtml=LoginDoneHtml'
        self.url_PrefCookie = 'http://www.google.com'
        self._connect()
```


You can read more about Fake-UserAgent here:

https://github.com/hellysmile/fake-useragent

Do let me know if you notice any else that seems fishy, or would like me to explain further.

**Comment by yichuanwangsc** [comment]
Will do. Thank you! I didn't see any other suspicious things for now, I think it is a false alarm.

**Comment by dreyco676** [comment]
I should correct myself, its not done randomly, it is always set to use the newest version of fake_ua.chrome. If we needed to change it to randome fake_ua.random would provide that but might cause more users to be concerned :-).

**Comment by aCampello** [comment]
Following up this topic, do you know if there is a way to authenticate via a "O2 Auth Token" or something similar, instead of having to pass your password to the python program?
