### ISSUE TITLE
Different result from google trends

### ISSUE THREAD

**Issue by akurniawan** [GeneralMills/pytrends#351]
I compare the result to the google trends directly but it seems that they are different. The following is the code that I used
```py
from pytrends.request import TrendReq

pytrends = TrendReq(hl="en-US", tz=360)
pytrends.build_payload(["anvaya"], cat=179, timeframe="all")
res = pytrends.related_topics()
res["anvaya"]["top"]
```
This is the result from the above code
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/4723643/69692553-f53a4700-1104-11ea-9b84-29809f3f71c9.png">

And this is the result from google trends
<img width="568" alt="image" src="https://user-images.githubusercontent.com/4723643/69692568-fec3af00-1104-11ea-811f-c900fbae706d.png">

This is the parameters that I used to search in google trends
<img width="567" alt="image" src="https://user-images.githubusercontent.com/4723643/69692579-06835380-1105-11ea-906a-b5a2d78eacac.png">

**Comment by melissadecastro** [comment]
I am also sending this issue with interest_over_time(). The numbers values might match correctly/closely for the few couple of geography codes and keywords from my lists. There have been test cases where single geography code and keyword seem to produce consistent results, however, it seems like a waste to make many dataframes just to combine them.

**Comment by aspiringguru** [comment]
I'm also seeing a discrepancy. Not sure how to test.

noticed the issue below on the google-trends-api npm package, it's possible both api's are experiencing difficulty navigating the service. Issue 132 mentions 'does not return the last two days of data.' 

https://github.com/pat310/google-trends-api
https://github.com/pat310/google-trends-api/issues/132
