### ISSUE TITLE
how to input multiple geo codes in pytrend.build_payload

### ISSUE THREAD

**Issue by py-mgmt** [GeneralMills/pytrends#352]
I am trying to get a time-series GSV of one key word but in two different regions using the following code (it used to work when I collected the data for other key words a few months ago):
pytrend.build_payload(["Python"], cat=0, timeframe='all',geo='US-CA,US-TX',gprop='')
gsv = pytrend.interest_over_time()

Any help will be much appreciated.
the error code is as follows,
  File "C:\Python3\lib\site-packages\pytrends\request.py", line 120, in build_payload
    self._tokens()
  File "C:\Python3\lib\site-packages\pytrends\request.py", line 131, in _tokens
    trim_chars=4,
  File "C:\Python3\lib\site-packages\pytrends\request.py", line 101, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.

**Comment by gabrielchavesbosch** [comment]
Nobody managed this? I have the same problem!

**Comment by flucoe** [comment]
Same here. Any suggestions?

**Comment by AlexYarkin** [comment]
Same issue here, 2 years later. Any updates on this? Thanks a lot!

**Comment by iperova** [comment]
Use for loop to loop into geo list

**Comment by qcgm1978** [comment]
I have the same problem, I passed list geos to `pytrends.build_payload` method and error throwed:
`ResponseError('The request failed: Google returned a response with code 400')`
