### ISSUE TITLE
Error 429 after first request

### ISSUE THREAD

**Issue by rmusngi** [GeneralMills/pytrends#354]
Hello!

I am getting Error 429 after my first request. Wondering if this is because I hit the limit somehow? 

Also how long before it goes back to normal again?

**Comment by daveajstearns** [comment]
Having a VPN set up will help you bypass the problems with the 429 error.

**Comment by mikulabc** [comment]
Same here, i thought it was the keyword, then put a different keyword, again only the first request works, 2nd is 429

**Comment by brilam** [comment]
Similarly here but I am using an EC2. Any ideas?

**Comment by mikulabc** [comment]
Yes, hint hint, create a 2nd py file and restart the gtrends.py for each keyword, i know it sucks, but it works, the limits is 1600 requests it appears for a time period of 24h i believe, tested it 2x so far
