### ISSUE TITLE
Error calling top_charts()

### ISSUE THREAD

**Issue by andyherzberg** [GeneralMills/pytrends#355]
Thank you for the awesome pytrends library! 
Maybe I found an issue using that library... I am trying to the monthly top charts using your example 

Top Charts
`pytrends.top_charts(date, hl='en-US', tz=300, geo='GLOBAL')`

With the mothly parameters. According to the documentation I am using 

`Example 201611 for November 2016 Top Chart data`

but the response for the monthly data is always 'list index out of range' while the data on a yearly basis can be called. Is calling the monthly data no more supported?

**Comment by OnePunMan** [comment]
I encountered the same problem. I think Google removed the ability to filter by month. I played around with Google's raw requests and indeed, passing in the month with the year will give an empty list as a result.

It might be related to the fact that Google changed their "Top Charts" to "Year in Search" instead. On their page, there's no option to filter by month.

(eg. https://trends.google.com/trends/yis/2019)

**Comment by MaxGhenis** [comment]
>I think Google removed the ability to filter by month.

I think this is correct. I'd recommend the following:
* Update documentation to specify that the `top_charts()` `date` argument must be a year
* Add a warning if anything other than a valid year is passed as `date`
* In a major release, replace the `date` argument with `year`
* In anticipation of that change, add a `year` argument which can be passed in lieu of `date`, and warn users that use the `date` argument
