### ISSUE TITLE
How can I scrape the interest over time over the last 5 years from a keyword?

### ISSUE THREAD

**Issue by danielp3011** [GeneralMills/pytrends#357]
I had some difficulties understanding the examples.

**Comment by TickTack-z** [comment]
`from pytrends.request import TrendReq
pytrends = TrendReq(hl='en-US', tz=360)
kw_list = ["Blockchain"]
pytrends.build_payload(kw_list, cat=0, timeframe='today 5-y', geo='', gprop='')
pytrends.interest_over_time()`
