### ISSUE TITLE
[Question] Is there a way to get the google trends data in memory instead of a csv file?

### ISSUE THREAD

**Issue by austincap** [GeneralMills/pytrends#36]
I'm trying to use your API as part of a webapp. I want to gather search data from a variety of sources including google trends then aggregate it to get an even more general estimate of how popular a topic is. I was trying to save to csv first then immediately read the csv but that's a little silly. 

How could I say, print line 500 of the csv file before the script stops running?

**Comment by dreyco676** [comment]
hmmm... I honestly can't remember if @bdewilde finished the `parse_data()`  function. That should return a JSON object according to the comments.

If that does work, let me know. We should put it in the documentation as a feature. If it doesn't I'll see if I can finish it off.

**Comment by austincap** [comment]
I'm getting this error: 

AttributeError: type object 'pyGTrends' has no attribute 'parse_data'

**Comment by shobute** [comment]
I am using `parse_data()` without issue, so +1 for adding it to the docs, it's a nice feature!

**Comment by dreyco676** [comment]
@shobute if you wanted to take a stab at that and do a PR I'd be happy to incorporate it. That part was written by @bdewilde and I'd have to spend some time reviewing it.

**Comment by dreyco676** [comment]
This is coming in the next version.
