### ISSUE TITLE
US Metro Code List?

### ISSUE THREAD

**Issue by GoodmanBen** [GeneralMills/pytrends#362]
Is there a common reference where US metro codes are listed, or a way in which they can be derived?

Particularly in reference to building a payload with a term specified like
`geo='US-{State}-{Metro #}`?

Any help on this would be greatly appreciated.

**Comment by GoodmanBen** [comment]
It looks like it is possible to get the information out of an [R package](https://stackoverflow.com/questions/50318748/gtrendsr-geo-msa-area-code,), but that certainly does not seem to be ideal.

**Comment by mlaugharn** [comment]
Is this of any use to you?

https://storage.googleapis.com/adx-rtb-dictionaries/geo-table.csv

**Comment by beniaminogreen** [comment]
I think this should have all of them. Please let me know if it doesn't. 

https://gist.github.com/beniaminogreen/b6da762d3b228192ac90d034f56f7cc3

**Comment by GoodmanBen** [comment]
Very helpful, thank you!

**Comment by MonaMaNotAvailable** [comment]
From the R GitHub gTrendsR repository I found a website to all metro code: https://github.com/PMassicotte/gtrendsR/blob/master/data-raw/country_codes.R
On line 29 there is a website: www.google.com/help/hc/downloads/ds3/Location-Language-Codes-AdWords.xlsx
I believe this should be the ideal file that contains all the metro codes!
