### ISSUE TITLE
pyGTrends

### ISSUE THREAD

**Issue by Bertrand-Russell** [GeneralMills/pytrends#37]
Hi, I'm interested in using pytrends for predicting winners in senate races. I copied your example code, to begin playing around with it, entered a path, my username, password etc. When I run the code, however, I get, "NameError: name 'pyGTrends' is not defined." Any ideas?

**Comment by dreyco676** [comment]
Did you by chance install with Pip?

**Comment by Bertrand-Russell** [comment]
Yes, I did. Should I have used another method?

**Comment by dreyco676** [comment]
No, just wanted to make sure it installed as expected. I'll try on my end over the weekend and let you know.

**Comment by larryisthere** [comment]
+1
ImportError: No module named pyGTrends
example code as well.

**Comment by dreyco676** [comment]
Give it a shot now. I was able to install via pip, open python in terminal and run the example. 

Make sure that pytrends isn't installing for the system Python if you are on Linux or OSX but is installing on whatever version you are developing against.

**Comment by zhilevan** [comment]
I have the same, first I install  `pip install pytrends` then try example and faced with 
`Traceback (most recent call last):
  File "getTrends.py", line 1, in <module>
    from pytrends.request import TrendReq
ImportError: No module named pytrends.request
`
I'm using Mac.

**Comment by akshat-rastogi** [comment]
I am also facing the similar issue. It sometimes works if I use it in a different notebook but keeps failing after sometime.
