### ISSUE TITLE
Add support for payload without keywords (Add me as contributor so I can create a pr)

### ISSUE THREAD

**Issue by kkristof200** [GeneralMills/pytrends#375]
I couldn't find a way to create payload without specific keywords, so I can get search queries for specific requests without adding a keyword to use it as a starting point.

Google Trends supports this: https://trends.google.com/trends/explore?date=today%201-m&geo=US&gprop=youtube

I've cloned the repo and updated the code, to provide this functionality, so all I need is to add me as a contributor, so I can create a pr.

**Comment by MaxGhenis** [comment]
To create a PR in a repo you don't manage, you need to create it in a fork and then follow these instructions: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by kkristof200** [comment]
Didn't know that, but makes sense. Thanks for the info @MaxGhenis !

**Comment by eracle** [comment]
Any news on this?

**Comment by tpilkati** [comment]
Hi, I already solved this and I use this feature through a copy of this repo that I have for myself. If you want to know how look at my commits it's just a little change to the request.py file

https://github.com/GeneralMills/pytrends/pull/414/commits/6ca4733c1a23e45b6cfc084381466dcbd89e3d2b

**Comment by eracle** [comment]
@tpilkati Hey Nice, why aren't proposing a Pull Request?
