### ISSUE TITLE
top_charts not working

### ISSUE THREAD

**Issue by AND1Ventu** [GeneralMills/pytrends#387]
it gives me this error:

raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=US (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11427b430>, 'Connection to 41.44.162.193 timed out. (connect timeout=10)'))

Someone could help me?

**Comment by emlazzarin** [comment]
Should be resolved.
