### ISSUE TITLE
Pytrends error 400

### ISSUE THREAD

**Issue by maron1209** [GeneralMills/pytrends#388]
Hi all, 

I am trying to pull some data from Google Trends but I keep getting the error "The request failed: Google returned a response with code 400.". I think it might has something to do with pytrend.interest_over_time() but I haven't been able to fix it. 

import csv
import time
import pandas as pd
from pytrends.request import TrendReq

pytrend = TrendReq(hl='DK', tz=360)
keywords =['Scandlines']
pytrend.build_payload(
    kw_list=keywords,
    cat=0,
    timeframe='2016-12-14 2017-01-25',
    geo='DK',
    gprop=' '
)

data = pytrend.interest_over_time()
data.to_csv('Uge 16', encoding='utf_8_sig')

Anybody having similar issues?

**Comment by andreian02** [comment]
Hello Maron, 

I managed to recreate your code and i didn't find my issues. 
The imports statements you have are slightly different from me. 
perhaps try if this works for you? 

![image](https://user-images.githubusercontent.com/36339564/80473717-1a173c80-8979-11ea-9c6a-7555aadd787e.png)

**Comment by maron1209** [comment]
Hi Andreian, 

I tried recreating your code by still get the same responseError 400. I am using Google colab, I don't know if that has anything to do with the error. Below is a picture of my response error. 

<img width="1209" alt="Skærmbillede 2020-04-28 kl  15 21 05" src="https://user-images.githubusercontent.com/57493048/80492370-33fa5480-8964-11ea-9cf7-d1b82c9206b8.png">

**Comment by andreian02** [comment]
Hey Maron, 

This is the result i got from using google colab. 
While trying to be helpful human bean, the google colab numbers are different when I query them using jupyter notebook. So i guess that the consolation prize is the library does work. 

![image](https://user-images.githubusercontent.com/36339564/80517139-2b7f3980-89b7-11ea-8938-aa654057c085.png)

**Comment by maron1209** [comment]
Hey Andreain, 

Thank you so much for your help. I will try with something other than Google colab in the hopes of it potentially working.

**Comment by MaxGhenis** [comment]
This is caused by `gprop=' '` (@maron1209 looks like you did `gprop=''`, which is the default and works, see [this colab notebook](https://colab.research.google.com/drive/1qREMpMVDDKCe8f0Ye_a9YyseZVHxxyMR?usp=sharing)). Per https://github.com/GeneralMills/pytrends#common-api-parameters, `gprop` must be `images`, `news`, `youtube` or `froogle` (or an empty string).

I filed PR #409 to check for valid `gprop` values and raise an informative error message when this check fails.

**Comment by andreian02** [comment]
@MaxGhenis good catch
