### ISSUE TITLE
"['geoCode'] not in index" when request CITY LEVEL interest_by_region Google trends

### ISSUE THREAD

**Issue by hanchenresearch** [GeneralMills/pytrends#392]
Hi, the pytrends API developers and maintainers,

Thank you for developing this great API and I'm now just starting to use it for my research. 
I recently ran into a key error when I tried to get Google treands data on city level.
My code is as follows:

import pandas as pd                        
from pytrends.request import TrendReq
pytrend = TrendReq()

kw_list=['Coronavirus']
pytrend.build_payload(kw_list, timeframe='today 3-m', geo='US', gprop='')
pytrend.interest_by_region(resolution='CITY',inc_low_vol=True, inc_geo_code=False)

**This is the error message.**
KeyError                                  Traceback (most recent call last)
<ipython-input-19-91b520252342> in <module>
----> 1 pytrend.interest_by_region(resolution='CITY',inc_low_vol=False, inc_geo_code=False)

~/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/pytrends/request.py in interest_by_region(self, resolution, inc_low_vol, inc_geo_code)
    282 
    283         # rename the column with the search keyword
--> 284         df = df[['geoName', 'geoCode', 'value']].set_index(
    285             ['geoName']).sort_index()
    286         # split list columns into seperate ones, remove brackets and split on comma

~/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2999             if is_iterator(key):
   3000                 key = list(key)
-> 3001             indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
   3002 
   3003         # take() does not accept boolean indexers

~/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/pandas/core/indexing.py in _convert_to_indexer(self, obj, axis, is_setter, raise_missing)
   1283                 # When setting, missing keys are not allowed, even with .loc:
   1284                 kwargs = {"raise_missing": True if is_setter else raise_missing}
-> 1285                 return self._get_listlike_indexer(obj, axis, **kwargs)[1]
   1286         else:
   1287             try:

~/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1090 
   1091         self._validate_read_indexer(
-> 1092             keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
   1093         )
   1094         return keyarr, indexer

~/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1183             if not (self.name == "loc" and not raise_missing):
   1184                 not_found = list(set(key) - set(ax))
-> 1185                 raise KeyError("{} not in index".format(not_found))
   1186 
   1187             # we skip the warning on Categorical/Interval

KeyError: "['geoCode'] not in index"

I actually tried all API methods, and they worked very well, except for this one.

Thank you for your time!

Best,
Han

**Comment by hanhaiyuntian** [comment]
Also, I have an additional question. How can I get CITY-DAILY data? I can request daily data using 'Interest by Region'. However, Google seems to rescale the results per request, then the data is nonomparable. Can we add a similar option of 'resolution' to the 'Interest Over Time' method?

**Comment by andreian02** [comment]
Hello hanhaiyuntian, 

Answering part 1 of your question on City level data. 
I think you might have missed this on from the docs. 
You would need to specify the city level abbreviation, ie, US-AL for Alabama. 

Recreating your example here. 
Hope it helps. 
![image](https://user-images.githubusercontent.com/36339564/81718871-dbbc6a00-94ae-11ea-9037-d9c44f125559.png)

**Comment by andreian02** [comment]
Hello hanhaiyuntian,

Trying to answer part 2 of your question on City level Daily Data, 
Assuming you have a few key cities in mind, using geo='US-AL'  would be just an iteration of what you are aiming to extract. 

I have never used the dailydata function before but do take a look at the explanation in the details section. the url: http://bit.ly/trendsscaling, documents the logic behind understanding daily level data. 

Recreating your example again. 
Interesting to see how Coronavirus search index spikes in Alabama.  
Looks like you are on to something interesting. 
Hope it helps.  

![image](https://user-images.githubusercontent.com/36339564/81720431-fabbfb80-94b0-11ea-8d27-87b6b214a11a.png)

**Comment by hanhaiyuntian** [comment]
Thank you so much for your reply and suggestions, Andreian! 

For the second question, yes, it is a good idea to get the scale parameter! I derived the temporal rescale parameter based on the time-series national-level search index. Then I used this parameter to rescale more lower-level data.

Regarding the first one, Google website seems to return both Metro(DMA) and City level data. For example, if you choose 'US-AZ' (https://trends.google.com/trends/explore?geo=US-AZ&q=coronavirus), we can get data on these two levels in the section of 'Interest by metro'. But the API now seems to return DMA-level data though we specify the resolution as 'CITY', the same results as 'DMA' resolution.

**Comment by BodoBurger** [comment]
I have the same 'geocode not in index' problem. 
I don't get an error with US regions ('US-AL', 'US-NE' ...), but with European region codes like 'FR-F' or any German code ('DE-BY').

You get city-level data over the web interface:
https://trends.google.com/trends/explore?date=today%205-y&geo=DE-BY&q=Corona
https://trends.google.com/trends/explore?date=today%205-y&geo=FR-F&q=Corona

But the same queries produce an error with pytrends. Any ideas?

**Comment by BodoBurger** [comment]
Minimal example for reproduction:
    
    from pytrends.request import TrendReq
    
    #working
    pytrends = TrendReq()
    pytrends.build_payload(['Corona'], timeframe='today 5-y', geo='US-AL', gprop='')
    pytrends.interest_by_region(inc_low_vol=True)

    #not working
    pytrends = TrendReq()
    pytrends.build_payload(['Corona'], timeframe='today 5-y', geo='DE-BY', gprop='')
    pytrends.interest_by_region(inc_low_vol=True)

**Comment by shevajia** [comment]
pytrends can almost deliver the job. There is just a small bug in its job. Here is a fix:
https://github.com/shevajia/PytrendsAddon

**Comment by leo-smi** [comment]
what about the state level?
