### ISSUE TITLE
Deprecate Python 2 support

### ISSUE THREAD

**Issue by MaxGhenis** [GeneralMills/pytrends#401]
As Python 2 was sunset on 2020-01-01, I'd suggest deprecating support for it. This could help drop some code, and if continuous integration is added, it would simplify that testing as well.

**Comment by MaxGhenis** [comment]
For reference, other common packages no longer support Python 2, and many no longer support earlier Python 3 versions:
* [`pandas` requires Python 3.6.1+](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html)
* [`numpy` requires Python 3.5+](https://pypi.org/project/numpy/)
* [`matplotlib` requires Python 3.6+](https://pypi.org/project/matplotlib/)

**Comment by hugovk** [comment]
> For reference, other common packages no longer support Python 2, and many no longer support earlier Python 3 versions:
> 
> * [`pandas` requires Python 3.6.1+](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html)
> * [`numpy` requires Python 3.5+](https://pypi.org/project/numpy/)
> * [`matplotlib` requires Python 3.6+](https://pypi.org/project/matplotlib/)

Matplotlib, scikit-learn, IPython, Jupyter, yt, SciPy, NumPy, scikit-image and other Scientific Python projects have adopted a common policy:

> NEP 29 — Recommend Python and Numpy version support as a community policy standard

* https://numpy.org/neps/nep-0029-deprecation_policy.html
