### ISSUE TITLE
The request failed: Google returned a response with code 429.

### ISSUE THREAD

**Issue by JacobLau84** [GeneralMills/pytrends#413]
The request failed: Google returned a response with code 429.

**Comment by youngjunyi** [comment]
Having the same issue here - The request failed: Google returned a response with code 429.

**Comment by Josh1punch** [comment]
I think you're writing the code in a for loop without sleep time? The svr will be too busy to  handle hundreds of response request

**Comment by CameronSima** [comment]
Received "you have reached your quota limit" on my very first request and all subsequent requests, all spaced several minutes apart.

**Comment by odufb** [comment]
Having same issue. I check  previous answers but all not work for me.

**Comment by jakek1980** [comment]
having the same issue. google returned a response with code 429.

**Comment by mevalerio** [comment]
Is there anyone that can provide a sensible estimation of the number of requests before this error appears?

Thanks

**Comment by JamesTheAwesomeDude** [comment]
> Received "you have reached your quota limit" on my very first request and all subsequent requests, all spaced several minutes apart.

Are you on a university connection or otherwise shared IP?

**Comment by rpivo** [comment]
When testing out a google trends url in postman, I get a 429 response, which looks like it's the result of not having the `NID` cookie set. After that gets set, then the GET request responds with a 200.

I'm not sure if the 429 is always the result of this `NID` cookie not properly getting set, but seems like could be a possibility. There is logic in the request.py file to prepare this cookie: https://github.com/GeneralMills/pytrends/blob/master/pytrends/request.py#L62-L98

**Comment by renatobibiano** [comment]
anyone found a solution to this?
when I run my code on my computer it goes ok, but when I do that on my prod environment (on AWS) I'm getting this 429

**Comment by emlazzarin** [comment]
Fixed by #553.
