### ISSUE TITLE
Top_charts date format

### ISSUE THREAD

**Issue by joonyoung82** [GeneralMills/pytrends#418]
I am able to get result for a full year but not on months using top_charts

You wrote
```
Top Charts
pytrends.top_charts(date, hl='en-US', tz=300, geo='GLOBAL')
Parameters

date

Required
YYYY or YYYY-MM integer
Example 2016-11 for November 2016 Top Chart data
Returns pandas.DataFrame
```

Wouldn't 2016-11 return 2005 results?

According to https://pypi.org/project/pytrends/#top-charts
it's supposed to YYYYMM format, but that fails to return results: "IndexError: list index out of range"

```
Parameters

date

Required
YYYY or YYYYMM integer
Example 201611 for November 2016 Top Chart data
Returns pandas.DataFrame
```

**Comment by GalileoCap** [comment]
Google removed the ability to filter by month when they changed from "Top Charts" to "Year In Search"
#355
