### ISSUE TITLE
_infer_dtype regex doesn't work for string starting in a number

### ISSUE THREAD

**Issue by wkzhu** [GeneralMills/pytrends#42]
https://github.com/GeneralMills/pytrends/blob/master/pytrends/pyGTrends.py#L196

I think the regexes don't encompass all possible options, for example I get this error:

`ValueError: val=3d printer dtype not recognized`

**Comment by dreyco676** [comment]
Resolved with PR #40. I'll have to push out to PyPi when I've got time.
