### ISSUE TITLE
Is there a time delay for pytrends?

### ISSUE THREAD

**Issue by enzoampil** [GeneralMills/pytrends#427]
I have a use case that requires google trends data at the end of the day. Was wondering if data pulls are real time.

I.e., if I query google trends data at the end of the day (at 23:59), will the data for that day be complete, or practically complete?

**Comment by andreian02** [comment]
Hello Enzoampil, 

I think there is usually like a day or two days of lead time before the data is available up till the date you are querying for.

**Comment by enzoampil** [comment]
Thanks @andreian02 !
