### ISSUE TITLE
AWS Fargate Google returned a response with code 429.

### ISSUE THREAD

**Issue by iwasscience** [GeneralMills/pytrends#435]
I have a task running on AWS Fargate that needs to execute around 20.000 pytrends requests. After around 2500 requests I only received "Google returned a response with code 429". I had to stop the Container from running and wait for a while, until the error message did not come up again. The same happened after around 5.000 queries were reached. 

I am sleeping 60 seconds after each request, but it still happens. Is there anything I can do to avoid that error message? Maybe 60 seconds is not enough? Or am I just making too many requests from the same Location/IP?

One thought I have:

Once the I catch that Error Message, I sleep for a longer period of time (e.g. 1 hour) instead of 60 seconds. Sadly there is no time period given how long one should wait until the block is gone.

After letting the container run for 2 more hours the block is gone, so implementing my thought above should solve my issue.

**Comment by tyoc213** [comment]
@iwasscience this limit that is being hit from AWS (only?) is around somewhere?

Is there something we can do instead of just not sending "many request" I haven't metered them to know "how many" can be made.
