### ISSUE TITLE
issues with SSL  (urlopen error ssl certificate verify failed (_ssl.c:590)) and possible fix

### ISSUE THREAD

**Issue by wtpfede** [GeneralMills/pytrends#44]
I don't think my solution is good enough for a commit, so I'll just leave this here:

While running the included example I immediately hit an SSL error:
**URLError: urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)**

I fixed this by **editing pyGTrends.py:**

on line 11 add: 
`import ssl`
on line 18 add an import for the HTTPSHandler of urllib2: 
`from urllib2 import build_opener, HTTPCookieProcessor, HTTPSHandler`

then in **def _connect in pyGTrends.py:**

on line 59 add: 
`self.hn = HTTPSHandler(context=ssl._create_unverified_context())`
on line 60: 
`self.opener = build_opener(HTTPCookieProcessor(self.cj ),self.hn)`

I hope this helps!

**Comment by dreyco676** [comment]
Please let me know if this is still an issue in 1.2.0
