### ISSUE TITLE
Bug on "suggestions" when "requests_args" is not empty

### ISSUE THREAD

**Issue by jwcdbd** [GeneralMills/pytrends#448]
If requests_args is not empty, then in line 453 of the requests.py, the "self.requests_args" is included as kwargs and line 126 of the _get_data method includes it again. So it causes an error.

**Comment by jhammarstedt** [comment]
Hi @jwcdbd ,might be facing the same issue now or at least I can't run the suggestions properly: 

"TypeError: requests.sessions.Session.get() got multiple values for keyword argument 'verify'"

Did you find a workaround to solve this?
