### ISSUE TITLE
Inconsistent data collection using multiple keywords 

### ISSUE THREAD

**Issue by abd96** [GeneralMills/pytrends#453]
Hello there, 

calling `pytrends.build_payload(kw_list)` on a list of multiple keywords is returning results that are different from calling 
`build_payload()` on a list containing a single keyword. 

Result of data for etherium when  `kw_list=['etherium', 'ninja']` : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3, 2, 2, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 2]

Result of data for etherium when `kw_list=['etherium']` : [4, 7, 4, 7, 5, 5, 8, 5, 7, 6, 6, 4, 4, 4, 3, 4, 5, 8, 9, 7, 6, 7, 10, 5, 4, 5, 4, 6, 4, 5, 2, 3, 3, 2, 3, 5, 4, 4, 3, 4, 6, 5, 5, 5, 4, 4, 4, 3, 5, 4, 5, 4, 3, 3, 5, 5, 2, 5, 9, 7, 16, 11, 10, 7, 10, 8, 11, 16, 18, 20, 56, 43, 47, 76, 74, 62, 37, 40, 37, 23, 26, 27, 32, 25, 37, 34, 26, 24, 21, 20, 27, 36, 22, 28, 34, 33, 49, 73, 79, 92, 89, 61, 77, 100, 71, 46, 47, 36, 28, 30, 19, 22, 17, 20, 18, 15, 11, 19, 12, 15, 15, 15, 16, 11, 12, 10, 9, 9, 11, 10, 7, 10, 6, 12, 12, 10, 10, 11, 11, 7, 7, 7, 5, 6, 5, 8, 5, 6, 8, 7, 7, 6, 6, 8, 9, 9, 6, 5, 4, 6, 5, 6, 7, 4, 4, 5, 4, 7, 4, 5, 5, 3, 7, 13, 6, 5, 5, 7, 6, 13, 5, 7, 6, 4, 4, 5, 6, 5, 4, 4, 4, 3, 5, 4, 4, 4, 5, 4, 4, 3, 4, 3, 4, 4, 4, 3, 5, 4, 5, 4, 5, 7, 8, 6, 7, 6, 7, 9, 4, 5, 5, 6, 6, 10, 10, 8, 7, 10, 10, 7, 7, 9, 7, 9, 7, 13, 17, 15, 16, 13, 10, 13, 9, 7, 7, 6, 6, 7, 6, 8, 8, 10, 12, 20, 14, 11, 11, 16, 26, 64, 53]

My Code snippet : 

`pytrends = TrendReq(hl='en-US', tz=360)`
`pytrends.build_payload(kw_list, cat=0, timeframe='today 5-y', geo='', gprop='')  `
`data = pytrends.interest_over_time()  `
`print(data.to_dict()['etherium'].values())  `

**Comment by werageth** [comment]
This is working as it should. Google trends scales the data against both keywords. Since 'ninja' is searched much more than 'etherium' the latter is scaled down. Compare to actual google trend webpage and you can see this is returning the correct result.

https://trends.google.com/trends/explore?q=etherium,ninja

**Comment by abd96** [comment]
Thank your for your helpful comment.
