### ISSUE TITLE
Longevity

### ISSUE THREAD

**Issue by iethan** [GeneralMills/pytrends#46]
In trying to get related entities it looks like Google is not using the same method of get requests in the pytrend API. It's using the URL: 
https://www.google.com/trends/api/widgetdata/relatedsearches/csv?req={"restriction":{"geo":{"country":"US"},"time":"2004-01-01 2016-08-16"},"keywordType":"ENTITY","metric":["TOP","RISING"],"trendinessSettings":{"compareTime":"2004-01-01 2005-01-01"},"requestOptions":{"property":"","backend":"IZG","category":44}}&token=[TOKEN]&tz=240

Are there plans to incorporate this new method into the pytrends module? Thanks in advance.

**Comment by dreyco676** [comment]
I'm not sure I follow. Do you want to be able to see the "Related topics" as keywords? Or how would you want this to work?

**Comment by iethan** [comment]
Yep, the related topics. I noticed the url to download reports changed from the one you use in the API to the json one above. I couldn't figure out how to get related topics from the script.

**Comment by dreyco676** [comment]
This should be addressed in the next version. You can take a peek in the json_returns branch.
