### ISSUE TITLE
What would be this proxy IP addres be 34.203.233.13?

### ISSUE THREAD

**Issue by tyoc213** [GeneralMills/pytrends#464]
It is a free proxy? a proxy provided by google as the 8.8.8.8 dns?? or why it is suguested as solution to rate limit?

Any proxy would work? how many proxies would I need depending in how many request I make per hour?

Say I want to do 1000 request per hour.

**Comment by pvhk** [comment]
Hello, did you find a solution ?

**Comment by tyoc213** [comment]
Not, the solution seem to run on GCP... but haven't tried that... also I guess yeah you can have a series of proxies if possible, but don't know how plausible is to have as many proxies as needed per hour??? maybe use free proxies out there, but I wonder about who sees the traffic...
