### ISSUE TITLE
Getting inconsistent Interest Over Time data when the same query is executed in different days

### ISSUE THREAD

**Issue by nicolasakf** [GeneralMills/pytrends#466]
I am using the get_daily_data function to retrieve data from a single keyword, using the following arguments:

get_daily_data(KEYWORD, 2004, 1, today.year, today.month, geo='', wait_time=0)

By the way Google Trends API (Interest Over Time) request works, this query should retrieve me the exact same time series values, unless a new all-time high search volume measure is reached - considering that I am only looking at non-partial data. However, when I tried to repeat this same query on two different days, I received a completely different time series, even though no new all-time high value was reached. I also tried to compare the percentage change between consecutive days - that must stay the same even if the series is re-normalized by a new all-time high value -, but again, no success; the data is still incompatible.

Has anyone here encountered the same issue? I suppose this is probably a Google Trends problem and not a pytrends problem, but in any case, it would be nice to know if anyone has any thoughts on that.

Thanks in advance.

**Comment by liyuduan817** [comment]
I think it's a Google Trends problem and i have the same question with you.With the same time, Goole Trends send different time series.

**Comment by tylercroberts** [comment]
I think this is due to how Google Trends aggregates the data. You are seeing the results from some random sample of tweets. The seed used to generate this sample is refreshed daily IIRC

**Comment by emlazzarin** [comment]
This comes up pretty regularly, and I believe it has to do with how Google randomly samples results. Either way, unlikely something that can be fixed given it occurs in their UI as well.
