### ISSUE TITLE
The request failed: Google returned a response with code 429.

### ISSUE THREAD

**Issue by kalagee-anjaria** [GeneralMills/pytrends#467]
I am continuously getting this error even though I try sending requests in an interval of 5-10 minutes. Has Google changed it's rate limit policy? If not, then why does this error keep coming? And how should I get rid of it?
Thanks in advance.

**Comment by AndyMcGowan** [comment]
Having the same issue! Seems to work fine locally but not remotely. Makes me think its something to do with aws. Haven't tested it on a google compute engine yet though.

**Comment by kalagee-anjaria** [comment]
Yes. I am having this same problem. It's working fine in my localhost but not on AWS server.

**Comment by YLaido** [comment]
It usually means you're using a flagged IP address. This happens all the time with datacenter IPs. 
Try ipv6 or another provider.

**Comment by ousooners2834** [comment]
I have had the same issue myself recently. Google Cloud Functions started getting flagged all of a sudden as well.

**Comment by JessHPRH** [comment]
@YLaido how do I do that please?

**Comment by AntonioBlago** [comment]
tried also with different proxies, but no success. I am also interested in using  ipv6 @YLaido

**Comment by tylercroberts** [comment]
This sounds like the same issue as https://github.com/GeneralMills/pytrends/issues/461

**Comment by YLaido** [comment]
Well, turns out ipv6 gets banned even quicker than ipv4. Don't know if it's because I deleted the `.google-cookie` file.

**Comment by emlazzarin** [comment]
Thanks for the suggestion, @YLaido!
