### ISSUE TITLE
trending_searches without parameter returns the USA trending searches

### ISSUE THREAD

**Issue by iturbe** [GeneralMills/pytrends#481]
After running these two requests 

```
trending_searches_world = pytrends.trending_searches()
trending_searches_usa   = pytrends.trending_searches(pn='united_states')
```
every 2 hours for the last seven days, they return the same exact 20 trends.

I know it is entirely possible that the trends match up sometimes but they are consistently identical over a sample of 82 requests.

Might it be that there's a specific keyword to access global searches?

**Comment by iturbe** [comment]
So the actual endpoint the function uses doesn't have an aggregation for worldwide trends.

A workaround is to get all available geographies' trends and use that data, I suppose.

Worth noting that some articles online mention that calling the function without a parameter yields worldwide trends. This is NOT the case, as a quick inspection of the source code will reveal (as I should've done). The default parameter is indeed USA trends.

**Comment by qcgm1978** [comment]
> So the actual endpoint the function uses doesn't have an aggregation for worldwide trends.
> 
> A workaround is to get all available geographies' trends and use that data, I suppose.
> 
> Worth noting that some articles online mention that calling the function without a parameter yields worldwide trends. This is NOT the case, as a quick inspection of the source code will reveal (as I should've done). The default parameter is indeed USA trends.

Yes. The source code is `def trending_searches(self, pn='united_states'):`
