### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by ryangniadek** [GeneralMills/pytrends#500]
Is there anything preventing python3.9 from being explicitly supported by this project? Currently, only 3.3-3.7 are listed on [PyPI](https://pypi.org/project/pytrends/) although the README does say 3.3+.  

We were receiving a Bad magic number error which suggests there is a versioning issue. However, the issue was solved by deleting all `*.pyc` files.

@juliachen7

**Comment by emlazzarin** [comment]
I'm not aware of any issues. The problem is that this project lacks tests, so maintainers seem reluctant to merge and make upgrades. I'll explicitly upgrade the `setup.py` and see what happens.
