### ISSUE TITLE
request for tests

### ISSUE THREAD

**Issue by emlazzarin** [GeneralMills/pytrends#503]
Merging PRs is difficult for the maintainers because of a lack of robust tests. If somebody writes a broad set of tests, it will significantly improve the ability to merge updates with less risk.

Thank you for your help!

**Comment by rheophile10** [comment]
I can help write you some tests.

**Comment by Terseus** [comment]
Hi @emlazzarin 

I'm interested in writing a solid unit test suite, I have experience writing tests for third-party APIs using [VCR.py](https://vcrpy.readthedocs.io/en/latest/) among other techniques, however before that I would like to extract the requirements from the setup.py.
While thinking about it I though it would be a good idea to modernize the build system by migrating [from setup.py to pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/).

Before starting any work, are you willing to accept such changes to the project?

**Comment by emlazzarin** [comment]
That sounds great to me. Very willing to do so. Thank you, David!

**Comment by Terseus** [comment]
Cool @emlazzarin  ^_^

However please be patient, I might take a while for each PR/change, I have a life with a family and a fulltime job :)
Don't worry, if I see I cannot continue I'll communicate with you via this issue.

**Comment by rheophile10** [comment]
Am I muted or blocked or something?

**Comment by emlazzarin** [comment]
Why would you be muted?

David — no worries and thank you.

**Comment by rheophile10** [comment]
I think perhaps my manner or etiquette is wrong. I did offer to help in September and I received no response but @Terseus perhaps just did more to express his experience or it may have just been a fluke.

**Comment by emlazzarin** [comment]
I’m just here to review and accept contributions.

**Comment by rheophile10** [comment]
I guess I better PR to fix the function then.

**Comment by Terseus** [comment]
Hi @emlazzarin 

I started writing the first few tests based on vcrpy, before covering all the current tests I would like your opinion about how they look and how they will be maintained.
You have an example here: https://github.com/Terseus/pytrends/pull/3/files

Advantages:
* Now the tests will load pre-recorded responses saved using vcrpy, in case the backend changes the responses we can regenerate whem using `pytest --record-mode=rewrite`.
* Now we can check the full backend response, or what we're interested in; this allow to refactor whatever we want with the guarantee that the generated requests and the parsed responses will be the same.
* The YAML files with pre-recorded responses will not be shown in the diffs or in PRs once the first commit is merged and Github process the `.gitattributes` file, at least in theory, this may require some tweaking.

Things to consider:
* Some responses are quite big, I'm not sure if we want to compare _everything_ or what should we ignore.
* The test `test_tokens` checks what I though it's interesting not only to compare but to show (e.g. now it's very clear that the API returns widgets with `{"userType": "USER_TYPE_SCRAPER"}` as mentioned at #534.
* The test `test_interest_over_time` only compare length, first 3 rows and last 3 rows, I think that's enough to guarantee correctness here.
* `test_build_payload` and `test_tokens` are testing what I consider internal implementation details and not observable behavior, however I think they can be highly valuable if we refactor the related code.

I highly appreciate your comments here.
Please tell me if you're OK with this kind of testing and I'll continue.

**Comment by emlazzarin** [comment]
When I get back to a computer I can review the specifics of what’s being tested, but the approach looks sound to me. Let’s proceed and thanks very much!
