### ISSUE TITLE
problem exportin to csv

### ISSUE THREAD

**Issue by artrax57** [GeneralMills/pytrends#505]
I am using this code:

`import pandas as pd #pandas 0.25
pd.set_option('display.width', None)

from pytrends.request import TrendReq

pytrend = TrendReq(hl='en-US', tz=360)

pytrend.build_payload(kw_list=['crypto'], geo = 'US', timeframe = 'now 4-H', cat = 0)
related_queries= pytrend.related_queries()
save_csv('dataframes.csv')
print(related_queries)
print("\n")

`

And I get this error:

Traceback (most recent call last):
  File "test to csv-3.py", line 10, in <module>
    save_csv('dataframes.csv')
NameError: name 'save_csv' is not defined

**Comment by webertim** [comment]
```python
import pandas as pd #pandas 0.25
pd.set_option('display.width', None)

from pytrends.request import TrendReq

pytrend = TrendReq(hl='en-US', tz=360)

pytrend.build_payload(kw_list=['crypto'], geo = 'US', timeframe = 'now 4-H', cat = 0)
related_queries= pytrend.related_queries()
pd.DataFrame(related_queries).to_csv('dataframes.csv')
print(related_queries)
print("\n")
```

**Comment by artrax57** [comment]
Thank you webertim

I got the csv file in this format.

![Captura de Pantalla 2022-02-10 a la(s) 8 16 35](https://user-images.githubusercontent.com/2922523/153440423-3aaf975f-1c19-415f-9072-be73b983535b.JPG)

**Comment by artrax57** [comment]
is there a way to have the csv by columns in this format?

![Captura de Pantalla 2022-02-10 a la(s) 8 30 18](https://user-images.githubusercontent.com/2922523/153440553-e31ac126-3252-46a5-9fa8-85123d86e394.JPG)
![Captura de Pantalla 2022-02-10 a la(s) 8 30 10](https://user-images.githubusercontent.com/2922523/153440541-3dafe4a8-349a-4a90-b2d4-602378dbef68.JPG)
