### ISSUE TITLE
export related queries to csv in columns

### ISSUE THREAD

**Issue by artrax57** [GeneralMills/pytrends#506]
I have this code:

`import pandas as pd #pandas 0.25
pd.set_option('display.width', None)

from pytrends.request import TrendReq

pytrend = TrendReq(hl='en-US', tz=360)

pytrend.build_payload(kw_list=['crypto'], geo = 'US', timeframe = 'now 4-H', cat = 0)
related_queries= pytrend.related_queries()
pd.DataFrame(related_queries).to_csv('dataframes.csv')
print(related_queries)
print("\n")`

And it display the information in this way:
![Captura de Pantalla 2022-02-10 a la(s) 8 16 35](https://user-images.githubusercontent.com/2922523/153627763-15bba410-46bc-4057-b4cc-a0594a0b907d.JPG)

Is it possible to have that information in columns?

![Captura de Pantalla 2022-02-10 a la(s) 8 30 10](https://user-images.githubusercontent.com/2922523/153627940-195ca213-4e7f-4f75-a652-3b2fde3e6a49.JPG)
![Captura de Pantalla 2022-02-10 a la(s) 8 30 18](https://user-images.githubusercontent.com/2922523/153627949-835d3823-31a7-429b-9da2-b307538d044e.JPG)

**Comment by emlazzarin** [comment]
You should learn how Pandas works. This isn't an issue with pytrends.
