### ISSUE TITLE
same keyword for 3 different regions with the customized date range

### ISSUE THREAD

**Issue by rabbitofcam** [GeneralMills/pytrends#507]
Hi, 

Is there a way to get the following data with pytrends? 
key_word = 'iPhone'
geo = ['New York', 'California', 'Texas']
date_range = '2022-02-01' to '2022-02-15'

**Comment by rabbitofcam** [comment]
Here's the data I want to get with t pytrends. 
<img width="1259" alt="Screenshot 2022-02-15 at 18 54 01" src="https://user-images.githubusercontent.com/18384786/154129494-a76deb64-e98c-4914-8319-7764dec60b37.png">

**Comment by airsean** [comment]
Why did this get closed?

**Comment by emlazzarin** [comment]
@airsean Issues aren't for support questions — although if you'd like to help, we welcome your contribution.
