### ISSUE TITLE
request report

### ISSUE THREAD

**Issue by senielee** [GeneralMills/pytrends#51]
Thanks for updating the code and now the connector works.  However it seems like the request_report automated link doesn't works. 

When I use the example payload = {'q': ['Pizza, Italian, Spaghetti, Breadsticks, Sausage'], 'cat': '0-71'}, the link report is https://accounts.google.com/logout?hl=en-US&continue=http%3A%2F%2Fwww.google.com%2Ftrends%23cmpt%3Dq%26q%3DPizza%2C%2BItalian%2C%2BSpaghetti%2C%2BBreadsticks%2C%2BSausage%26hl%3Den-US%26cat%3D0-71%26content%3D1
which doesn't seem to be a valid link to download, anyone else have same problem?

**Comment by dreyco676** [comment]
Ick, it shouldn't be using accounts.google.com... Can you share some details like what version you are running (there was a small update early this morning to 2.0.2), Python version and maybe OS?

I know it doesn't help to here it but when I clone the repo and run the example on Python 3.5 I get:
http://www.google.com/trends/trendsReport?content=1&export=1&q=Pizza%2C+Italian%2C+Spaghetti%2C+Breadsticks%2C+Sausage&cat=0-71&cmpt=q&hl=en-US

Which is valid and downloads the correct data.

**Comment by senielee** [comment]
I am running Python 3.5.2 on Spyder.  I upgraded pytrends just now and it still gives "https://accounts.google.com/..."

Checked pytrends.py file, and it should get "http://www.google.com/trends/trendsReport", any idea why?

**Comment by dreyco676** [comment]
Silly question but did you put in your login credentials?

```
google_username = "an_email@gmail.com"
google_password = "password"
```

**Comment by senielee** [comment]
Yes, I used this package before and it worked perfectly until google changed it causing bad request problem.  It seems like even after I upgrade pytrends package it is still calling the function from the older version.  But I might be wrong.

**Comment by dreyco676** [comment]
You can check the version being called by trying this:

```
import pip
pip.main(["show","pytrends"])
```

It should say 2.0.2

**Comment by senielee** [comment]
It is version 2.0.2, I think I found the problem, I have multiple google account and seems like I have to sign in the corresponding gmail in browser before establishing the connection. Thanks for your help.

**Comment by dreyco676** [comment]
Yea it may not like two Google accounts from the same computer and try to log the other one out first.

**Comment by dreyco676** [comment]
Reopen if this issue persists.
