### ISSUE TITLE
"TypeError: requests.sessions.Session.get() got multiple values for keyword argument 'verify'"

### ISSUE THREAD

**Issue by pybokeh** [GeneralMills/pytrends#513]
Hello, when I pass in `requests_args={'verify':False}` and then call:
`pytrends.trending_searches(pn='united_states')`

I get the `"TypeError: requests.sessions.Session.get() got multiple values for keyword argument 'verify'"` error.

Is there a proper way to address this or a workaround?  The only workaround I am able to perform is to remove the `requests_args` parameter, then manually export the root and intermediary SSL certificates as base-64 encoded X.509 through the browser when visiting https://trends.google.com/trends/, combine them into a .pem file and then reference that .pem file from my Python script.  My understanding is with my corporate Windows machine, the Windows "certificate store" isn't being recognized by my Python environment.

Not sure if this [issue](https://github.com/GeneralMills/pytrends/issues/448) is related.

Environment:
Python version 3.9.8
Windows 10 OS

**Comment by mhornba** [comment]
Hi,
I have a similar problem. When I pass the path of a certificate with requests_args={'verify':'C:/path/certificate.crt'} and then call:
KEYWORDS_CODES=[pytrend.suggestions(keyword=i)[0] for i in KEYWORDS]
I get "TypeError: requests.sessions.Session.get() got multiple values for keyword argument 'verify'"

Additionally - not sure if it is related to the latter - when I call 
pytrend.build_payload(wordlist,timeframe=TIMEFRAME ,geo=GEO, cat=CATEGORY) after I pass requests_args={'verify':'C:/path/certificate.crt'}
I get "KeyError: 'content-type'" coming from requests\structures.py, line 54, in __getitem__return self._store[key.lower()][1]

Thanks for any ideas for a workaround!

Environment:
Python version 3.10.4
Windows 11 Pro
