### ISSUE TITLE
request_report() got an unexpected keyword argument 'date'

### ISSUE THREAD

**Issue by schiller061** [GeneralMills/pytrends#52]
Hi everyone,
first of all thanks for the support on here, super helpful! I just updated to 2.0.2 to solve the http connection error problem. When I run request_report() now though, I get the TypeError: "request_report() got an unexpected keyword argument 'date' "

The code that triggers the error looks something like this:

    search_string_date = str(month) + "/" + str(year) + " 36m"
    # connect to Google
    connector = pyGTrends(google_username, google_password)
    # make request
    connector.request_report(keys, date=search_string_date, geo="US")

Any ideas? I'm lost at this point. This worked perfectly before the google connection problems and my update to 2.0.2 and I haven't changed anything.

Thanks in advance!

**Comment by dreyco676** [comment]
Yup the API changed if you want to use the older version 1.3 it will work that way but the connection is fixed from 1.2. The new version uses a dictionary to make it so it can take new parameters users find without waiting on them to be implemented.

```
payload = {'q': keys, 'date': search_string_date, 'geo': 'US')
connector.request_report(payload)
```

Let me know if this doesn't solve your issue and we can reopen it.

**Comment by schiller061** [comment]
Thanks A LOT! works perfectly fine now. 

Different issue but I'll just ask since you might know: Is there a good way to get around the quota limit for running more than 200 requests?

**Comment by dreyco676** [comment]
```
import time 
time.sleep(x) 
```

where x is a number of seconds between each call (usually 5 is sufficient. Version 3 will have a rate limiter.

**Comment by schiller061** [comment]
Thanks! I already have the sleeper function in my program but after roughly 200 requests it shuts me down anyway. Once I turn on a VPN and "suggest" I'm located in a different place it works again...

**Comment by dreyco676** [comment]
Do you happen to know how long it takes for Google to reset the rate? Ie 15min, 1hr, 1day?
