### ISSUE TITLE
What's the rate limit for the API?

### ISSUE THREAD

**Issue by bluefinch83** [GeneralMills/pytrends#523]
Does anyone know what the rate limit is for this api? I thought it was 100 queries per 100 seconds, according to this documentation https://developers.google.com/analytics/devguides/reporting/mcf/v3/limits-quotas .  So, whenever I get a 429 error, I try waiting 100 seconds and then send another 80-100 queries. However, sometimes, it keeps returning a 429, even after I wait several minutes. Is there a daily limit as well? If so, how can one get around that?

**Comment by stergioa** [comment]
I have the exact same problem...

**Comment by fabiorangel** [comment]
This rate limit if set for official APIs. Pytrends API is non official, which means it is limited by google understanding that your requests might be a scrapper. So, you should have a list of proxies to iterate and try to bypass the google scrapping security.

**Comment by lr2bmail** [comment]
> What proxies do you reccomend for that task and how to find them?

$1 vps + [https://github.com/serverok/squid-proxy-installer](url) = 1 proxy

**Comment by emlazzarin** [comment]
Fixed by #553.
