### ISSUE TITLE
TrendReq.get_historical_interest is wrong

### ISSUE THREAD

**Issue by rheophile10** [GeneralMills/pytrends#528]
google trends api returns results relative to the time period queried because the values returned are returned as a percentage of the maximum interest in that period. 

For example 
```
from pytrends.request import TrendReq
from datetime import datetime, timedelta     

pytrends = TrendReq()

kw_list = ['mermaids']
hourly_period_in_days = 500
end = datetime.today()
start_1 = end - timedelta(hourly_period_in_days)
start_2 = end - timedelta(hourly_period_in_days*2)
tf = start_2.strftime('%Y-%m-%d')+' '+ end.strftime('%Y-%m-%d')
pytrends.build_payload(kw_list, timeframe=tf)
test2_df = pytrends.interest_over_time()
tf = start_1.strftime('%Y-%m-%d')+' '+ end.strftime('%Y-%m-%d')

if not any(test2_df[test2_df.index.to_series().between(start_1, end)]['mermaids']==test1_df['mermaids']):
    print('see what I mean')
```

By breaking a request for trends data into a period into many smaller requests for smaller periods that are subsequently concatenated together, TrendReq.get_historical_interest returns data that is distorted actually  

```
kw_list = ['mermaids']
hourly_period_in_days = 500
end = datetime.today()
start_1 = end - timedelta(hourly_period_in_days)
start_2 = end - timedelta(hourly_period_in_days*2)
kwargs_for_test_1 = get_kwargs_for_historical_interest(kw_list, start_1, end, "daily")
kwargs_for_test_2 = get_kwargs_for_historical_interest(kw_list, start_2, end, "daily")
test1_df = pytrends.get_historical_interest(**kwargs_for_test_1)
test2_df = pytrends.get_historical_interest(**kwargs_for_test_2)
if any(test2_df[test2_df.index.to_series().between(start_1, end)]['mermaids']==test1_df['mermaids']):
    print('nothing to see here')
```

**Comment by rheophile10** [comment]
I forgot to give you get_kwargs_for_historical_interest was just a function that converted a start and end datetime to all the kwargs for pytrends.get_historical_interest

**Comment by rheophile10** [comment]
no new code was added. This passes all current tests.

**Comment by rheophile10** [comment]
if you were going to write a function that would perform this it would have to first pull monthly data over the time period and then you would have to multiply the daily or weekly data you pulled iteratively by the monthly interest (divided by 100) to recreate scores that were relative to the period pulled. It would be computationally pretty expensive and fairly hard on the google trends api too (they'd almost certainly block your ip address) but not much harder or more expensive than what we have now.

**Comment by emlazzarin** [comment]
I see the error and recognize it needs to be resolved. The data that results from it is "a bit off" at best and "completely incorrect" most of the time.

I suspect this is one of the popular functions in this library. If we get rid of it, I think people will come back and ask questions as they struggle to reimplement it. Do you think implementing it correctly, as you outlined, with some thoughtful rate-limiting, could be better than simply removing it?

**Comment by rheophile10** [comment]
I offer you two viable courses of action to choose from: 

1. I can write a function that does what it is supposed to do but it's going to be brutal. It will involve more API calls because we'll have to break the date range up into months (which I think is 3-4x more calls) and then we will have to call the monthly change over the period to do normalization. 

I would make the pytest first to show more clearly how this function fails and then produce a function that works. 

We can do this to support legacy users. 

You might use it if you were doing a one-time data pull to start a database on a trend you wanted to track (the use case I was exposed to pytrends by) but if you were going to maintain historic data going forward you'd actually have to store daily, weekly or hourly data by month and re-normalize each time. 

I can make a new function that does what this old function said it was going to do make it in such a way as to make database tracking of a trend easier (and I can document how you would do that with a google cloud function in a medium article or something). I can also make pytests for it. Basically the pytest should be that the ratio of interest on two respective periods within a single get_historical_interest pull should be the same in any two get_historical_interest pulls where the date ranges in each pull are different (but inclusive of the two respective periods). 

or 

2. We delete the function because it draws us into supporting weird ETL schemes. I admire what @pat310 did with his [nodejs library for google trends](https://github.com/pat310/google-trends-api): he stuck faithfully to google's documented api functionality. 

###### TLDR 

I recommend that you look at the relative simplicity of what @pat310 did and if you still want me to go ahead and fix the function (1) I will, but if you feel it is better to remove it entirely (2) it might be easier for us in the long run. If you go with the latter I will still make you an article we can link in an issue here that explains how to produce the effects of get_historical_interest with the functions we already offer. Maybe doing that will goad somebody in coming around and coming up with a better way of doing it than I can think of.

**Comment by omar2205** [comment]
Hi @rheophile10, Did you end up making that article on how to produce the effects of get_historical_interest?
