### ISSUE TITLE
iterator in get_historical_interest is wrong

### ISSUE THREAD

**Issue by doughalperin** [GeneralMills/pytrends#530]
An extra call may be made to google trends for daily frequency.

Also pandas append is deprecated.

Here's a potential fix & simplification to the code
        while start_date < end_date:
            # format date to comply with API call (different for hourly/daily)

            if frequency == 'hourly':
                start_date_str = start_date.strftime('%Y-%m-%dT%H')
                date_iterator_str = date_iterator.strftime('%Y-%m-%dT%H')
            elif frequency == 'daily':
                start_date_str = start_date.strftime('%Y-%m-%d')
                date_iterator_str = date_iterator.strftime('%Y-%m-%d')

            tf = start_date_str + ' ' + date_iterator_str

            try:
                self.build_payload(keywords, cat, tf, geo, gprop)
                week_df = self.interest_over_time()
                df = pd.concat([df, week_df])  #df.append(week_df)
            except Exception as e:
                print(e)
                pass

            # just in case you are rate-limited by Google. Recommended is 60 if you are.
            if start_date != initial_start_date and sleep > 0:
                time.sleep(sleep)

            start_date = date_iterator
            date_iterator += delta

**Comment by emlazzarin** [comment]
Hey Doug — could you issue a pull request with the fix if it makes sense?
