### ISSUE TITLE
Is Pytrends Web scraping the data from Google Trends?

### ISSUE THREAD

**Issue by paulwarb** [GeneralMills/pytrends#531]
I'm not clear how this library is getting the data from Google Trends. Is it web scraping this data from Google Trends.

**Comment by jorgecabrejas7** [comment]
Working one the same issue. Seems he is using some kind of official API, but can't find any info about it. When we use the pytrends package we get some values that slightly differ from the ones obtain through the webpage. Also, we are trying to extract hourly data, which we had to request weekly timeframe to do so, but as of today, google trends webpage is no longer providing with hourly data in the graphics. The url to the API the package is using is trends.google.com/trends/api/wigdetdata

TL;DR: it seems it is not
