### ISSUE TITLE
How to avoid HTTP status 429 (too many requests)?

### ISSUE THREAD

**Issue by Rombersoft** [GeneralMills/pytrends#535]
Who can share experiences about problems with HttpStatus 429 (Too many requests)?
I noticed that the developer thought about using the proxy server. Does it exist some statistics about what I must do in order to be banned by Google Corporation? Public API is missing and how much is legal to use google back end in order to show google trends results on my own site???

**Comment by rheophile10** [comment]
what function are you using?

**Comment by Rombersoft** [comment]
> what function are you using?

I think it does not mean. You execute a request and get 429 status

**Comment by rheophile10** [comment]
@Rombersoft I was trying to understand how pytrends produces that result. But if your question is in general what to do with HTTPStatus 429 and how to get around that, stackoverflow is probably a better forum for you. 

Good day

**Comment by xenova** [comment]
I think I figured it out. By default, pytrends doesn't supply a user agent, so it uses the default one. This causes the request to be blocked.

I propose allowing a user to pass a user-agent in via the `requests_args` argument.

**Comment by emlazzarin** [comment]
Fixed by #553.
