### ISSUE TITLE
No way to know what changed between versions

### ISSUE THREAD

**Issue by Terseus** [GeneralMills/pytrends#539]
Currently there is no way to know what changed between versions except to download both versions from pypi and check the differences in the source code, this makes very risky to depend on this library for anything non-amateurish.

Please consider adding one or more of the following:
* Release in Github with changelog.
* Annotated tags in the commit where the version is released.
* Add a CHANGELOG.md file to the repo with a header for every version released; bonus points if you follow the [Keep a changelog format](https://keepachangelog.com/en/1.0.0/).
* Add a changelog section in the README.md with a header for every version released.

**Comment by emlazzarin** [comment]
This is a great idea, but the problem is that the project lacks active maintainers. I have been deputized to help, but am only doing so with a little bit of free time. I think the General Mills team has abandoned the project.

I would welcome such contributions.

**Comment by kaifman-curve** [comment]
> Currently there is no way to know what changed between versions except to download both versions from pypi and check the differences in the source code, this makes very risky to depend on this library for anything non-amateurish.
> 
> Please consider adding one or more of the following:
> 
> * Release in Github with changelog.
> * Annotated tags in the commit where the version is released.
> * Add a CHANGELOG.md file to the repo with a header for every version released; bonus points if you follow the [Keep a changelog format](https://keepachangelog.com/en/1.0.0/).
> * Add a changelog section in the README.md with a header for every version released.

Is there a recent version of Pytrends that is available? The latest version I can see is dated Feb 22 https://pypi.org/project/pytrends/

**Comment by Terseus** [comment]
Given that @emlazzarin has started doing releases here in Github, I think we can close this now.
