### ISSUE TITLE
Related Queries Functionality

### ISSUE THREAD

**Issue by gururise** [GeneralMills/pytrends#55]
The 'toprelated' API function seems to pull data from the Google Trends "related queries" section.  On the Google Trends website, one can configure the related queries section to show:

1. "rising" queries
2. "top" queries

It seems the data being pulled with the "toprelated" api function only pulls the rising queries.  It would be nice to be able to select the "top" queries as well.

**Comment by dreyco676** [comment]
resolved in 3.1.0 see related()
