### ISSUE TITLE
Hash for 4.8.0 changed on pypi

### ISSUE THREAD

**Issue by josges** [GeneralMills/pytrends#555]
Hi, we realized that the hash of file pytrends-4.8.0-py3-none-any.whl changed on pypi. The pypi UI shows an upload date for this file of Uploaded Jan 10, 2023. After looking into the new wheel, it seems that at least request.py got replaced by the 4.9.0 version.
Was this an accident or did somebody tamper with the repo?

**Comment by emlazzarin** [comment]
This was an accident — thanks for pointing it out. Let me see if I can fix it on pypi.

**Comment by josges** [comment]
Thanks for answering!
Good to know that nothing malicious was going on. We will just upgrade to 4.9.0.
The changed file for 4.8.0 seems to contain the code for 4.9.0 though. This may break stuff for users that got removed.
