### ISSUE TITLE
429 with headers in place

### ISSUE THREAD

**Issue by netvids** [GeneralMills/pytrends#560]
I am getting the error 429 when building my payload, I have put in place the header like mentionned in the previous thread. Its weird because I didnt push much request in the last days. I try to change my IP with a vpn, still the same. 

`  File "/home/kali/.local/lib/python3.10/site-packages/pytrends/request.py", line 189, in build_payload
    self._tokens()
  File "/home/kali/.local/lib/python3.10/site-packages/pytrends/request.py", line 195, in _tokens
    widget_dicts = self._get_data(
  File "/home/kali/.local/lib/python3.10/site-packages/pytrends/request.py", line 159, in _get_data
    raise exceptions.TooManyRequestsError.from_response(response)
pytrends.exceptions.TooManyRequestsError: The request failed: Google returned a response with code 429
`
Header:
`requests_args = {
    'headers': {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36'
    }
}
`

**Comment by terry-zc** [comment]
Same issues. It seems that Google Trends update their Google Trends UI. I don't know if it makess a difference

**Comment by Yu-Hsuan-Liu** [comment]
same issue

**Comment by aktywnitu** [comment]
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 429.

**Comment by netvids** [comment]
Issue was resolved in https://github.com/GeneralMills/pytrends/issues/561
