### ISSUE TITLE
new version of google trends not compatible whit pytrend  4.9.0

### ISSUE THREAD

**Issue by ithabibi** [GeneralMills/pytrends#566]
hi dear Eddy Lazzarin
In recent days, Google Trends has made changes in its service.
I think that the new version of google trends is not compatible with Pytrends 4.9.0
Please check the issue.
for more information, I added python stack trace of error.
![Capture](https://user-images.githubusercontent.com/38087594/226101671-c55ffc61-2fe0-4004-b473-949a20fa365d.PNG)

best regards
ithabibi

**Comment by ozfrenz** [comment]
Same for me
    158 if response.status_code == status_codes.codes.too_many_requests:
    159     raise exceptions.TooManyRequestsError.from_response(response)
--> 160 raise exceptions.ResponseError.from_response(response)

ResponseError: The request failed: Google returned a response with code 400

I tried user_agent, proxy and vpn as well. Also changed to "GET" to "POST" in @jesvinc https://github.com/GeneralMills/pytrends/issues/561#issuecomment-1462899426

still no luck. 

Thanks for all efforts

**Comment by karam-khanna** [comment]
Same as above

**Comment by totencrab** [comment]
This solution posted by @ckosmic [here](https://github.com/GeneralMills/pytrends/pull/563#issuecomment-1464193409) works consistently for me.

At line 76 and 89, insert explore before /?geo

`                        f'{BASE_TRENDS_URL}explore/?geo={self.hl[-2:]}',`

**Comment by megaluck** [comment]
I´ve did what totencrab suggested Now I get a 400 error 

    raise exceptions.ResponseError.from_response(response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400

**Comment by totencrab** [comment]
> I´ve did what totencrab suggested Now I get a 400 error
> 
> ```
> raise exceptions.ResponseError.from_response(response)
> ```
> 
> pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400

Sorry mate 🤷‍♂️ I'm new to this.

This is a copy of my [pytrends.py](<script src="https://gist.github.com/totencrab/17af7368082a28e5f028473e8570a00e.js"></script>) that's working correctly.

**Comment by ithabibi** [comment]
> hi dear Eddy Lazzarin In recent days, Google Trends has made changes in its service. I think that the new version of google trends is not compatible with Pytrends 4.9.0 Please check the issue. for more information, I added python stack trace of error. ![Capture](https://user-images.githubusercontent.com/38087594/226101671-c55ffc61-2fe0-4004-b473-949a20fa365d.PNG)
> 
> best regards ithabibi
