### ISSUE TITLE
Problem about Pytrends build_payload

### ISSUE THREAD

**Issue by ziqingwang-kate** [GeneralMills/pytrends#567]
Dear Sir or Madam, 

I hope this email finds you well. This is Ziqing Wang, a research associate from Stanford GSB. We are recently using Pytrends to conduct a research project. I am writing to inquire some questions about pytrends.  

From March 8th, we always got the error message "TooManyRequestsError code 429" when running the function “pytrends.build_payload”. Even people who use the pytrends for the first time with a new IP address get the same error.  

I am so appreciated it if you can give me some suggestions about this. Or are there any alternative functions in pytrends that can scrape historical volume data of Google Trends with keywords? 

 
Many thanks, 
Ziqing

**Comment by jiangcheng1999** [comment]
use :  pytrend = TrendReq(retries=3), another way is to swtich your proxy constantly, but then you need to find some valid proxies

**Comment by JacobFredman** [comment]
Having the same problem too, 
I don't now if it's new, but Google requests uniq token per request - even if you do a slightly change in your request - you need a new token that suit to that request.

**Comment by sripriya97** [comment]
@ziqingwang-kate https://github.com/GeneralMills/pytrends/issues/561#issuecomment-1462358749 check this out, adding NID cookie worked for me.

**Comment by sripriya97** [comment]
@ziqingwang-kate https://github.com/GeneralMills/pytrends/issues/561#issuecomment-1462358749 check this out, adding NID cookie worked for me.

**Comment by emlazzarin** [comment]
Closed because this should be resolved in #570.
