### ISSUE TITLE
Still Getting 429 Errors After 4.9.1 Update

### ISSUE THREAD

**Issue by searchsolved** [GeneralMills/pytrends#573]
I'm still getting consistent 429 errors after the latest PyTrends update. 

Should I by doing something different? I've read the docs and they look the same as before the PyTrends update. 

Thanks.

**Comment by uzairamer** [comment]
this solution worked for me:

```
session = requests.Session()
session.get('https://trends.google.com')
cookies_map = session.cookies.get_dict()
nid_cookie = cookies_map['NID']
```

then plug the NID cookie in the `TrendReq` object
```
TrendReq(hl='en-US', tz=360, retries=3, requests_args={'headers': {'Cookie': f'NID={nid_cookie}'}})
```

**Comment by DumbFace** [comment]
> this solution worked for me:
> 
> ```
> import requests
> 
> session = requests.Session()
> session.get('https://trends.google.com')
> cookies_map = session.cookies.get_dict()
> nid_cookie = cookies_map['NID']
> ```
> 
> then plug the NID cookie in the `TrendReq` object
> 
> ```
> from pytrends.request import TrendReq
> 
> TrendReq(hl='en-US', tz=360, retries=3, requests_args={'headers': {'Cookie': f'NID={nid_cookie}'}})
> ```

Thanks a lot, it worked for me.

**Comment by searchsolved** [comment]
Thanks that worked for me too!

**Comment by fackse** [comment]
The solution provided by @uzairamer works for me too. Thanks a lot @uzairamer !

**Comment by emlazzarin** [comment]
Could we incorporate this into the codebase?

**Comment by whatalnk** [comment]
> I don't understand why this solution works at all, this is basically what the [GetGoogleCookie](https://github.com/GeneralMills/pytrends/blob/master/pytrends/request.py#L67) method is already doing, or at least trying to do.

It seems that GetGoogleCookie is not working as intended.

I accessed to https://trends.google.com/trends/explore?geo=JP, which is used by GetGoogleCookie, from Google Chrome (Secret Window): 
* First time: it returned error (404 or 429)
* Second time (after reload): It returned normal responce
   
https://trends.google.com/trends?geo=JP is ok, and it redirected to https://trends.google.com/home?geo=JP.

**Comment by Terseus** [comment]
Hi @whatalnk 

That request is expected to fail with a 429, pytrends doesn't care if it works or not, it's only meant to generate a valid NID cookie.

Even when the request fails the backend returns a NID cookie that we can use to the next request(s).

Thanks for the response ,though.

**Comment by Terseus** [comment]
Hi @fackse,

I see you're using `proxies` in the second solution, but not in the first.

The `TrendReq` class behaves differently between when using proxies and when doesn't:
* when using proxies, the instance will retrieve a new NID cookie _for every request_.
* when not using them the instance will reuse the same NID over and over again.

Please, can you try to execute the first solution using `proxies` in the same way you do in the second solution and report if there's any difference in the error rate?

Thanks a lot.

**Comment by whatalnk** [comment]
Thank you for your quick reply. [This comment](https://github.com/GeneralMills/pytrends/issues/573#issuecomment-1503033797) was my misunderstandig.

Well, I found funny things.

I downloaded source code (pytrends==4.9.1) from PyPI, and checked the contents.
It seems that the change from the commit f6b2d0c230beccfb7fb1aff998ed6308685e3230 is not included.

In requests.py, `GetGoogleCookie` is still use  `f'{BASE_TRENDS_URL}/?geo={self.hl[-2:]}'`, not `f'{BASE_TRENDS_URL}/explore/?geo={self.hl[-2:]}'`

**Comment by fackse** [comment]
> @fackse
> 
> > pytrends.build_payload("Meech", timeframe="2023-03-06 2023-04-03", geo='US')
> 
> kw_list is interpreded as `M, e, e, c, h`, not `Meech`
> 
> How about
> 
> ```
> pytrends.build_payload(["Meech"], timeframe="2023-03-06 2023-04-03", geo='US')
> ```
You're absolutely right, my bad! 🤦‍♂️

**Comment by fackse** [comment]
It appears to be working! I installed it using "`pip install git+https://github.com/GeneralMills/pytrends`". I tested it with 1108 requests, each consisting of 5 keywords. To speed up the process, I used ThreadPoolExecutor to parallelize it and a proxy. The call was made with the following code:

pytrends = TrendReq(hl='en-US', tz=360, retries=3, proxies=[proxy]*100000)
pytrends.build_payload(chunk, timeframe="2023-03-06 2023-04-03", geo='US')

During the test, I encountered 196 instances of the message "Proxy error. Changing IP". To better control the behavior after the third attempt, I set the retries parameter to 3. Only 15 times did the request fail to go through within three attempts, in which case I had to re-initialize TrendReq (again with 3 retries - as seen in the code above).

**Comment by datacubed** [comment]
@emlazzarin @Terseus sorry to pester, but any idea when we would get this much needed release?

**Comment by emlazzarin** [comment]
https://pypi.org/project/pytrends/4.9.2/ has now been updated with the correct code. Thanks!

**Comment by jack-k-20230331** [comment]
I tried 'pip install pytrends' and it prompted 429 error today. The version is 4.9.2. 

But it seems working when I 'pip install git+https://github.com/GeneralMills/pytrends'

**Comment by JUSTINDSBAUTISTA** [comment]
Hello, 

I don't know if you will response or not, but it's good to give it a try.
I am intern, and have a task to SCRAPE the google trends.
- I have to get the RelatedQueries and the graph.
- and write it to .CSV

I did research for almost a week, but I don't get any guide from my work place.
But I found this code from the internet, that takes the RELATED QUERIES & RELATED TOPICS but not the Graph and save it as .csv file.
But you have to copy and paste each URL from the NETWORK.

I would be happy to learn PYTHON.
Thank you for your help.

**Comment by JUSTINDSBAUTISTA** [comment]
```
import httpx
import json
import pandas as pd

# Set the geographical location to the United States

geo_location = "CA"

# Add the API URLs
topics_url = f"https://trends.google.com/trends/api/widgetdata/relatedsearches?hl=en-US&tz=240&req=%7B%22restriction%22:%7B%22geo%22:%7B%22country%22:%22CA%22%7D,%22time%22:%222024-09-12T18%5C%5C:05%5C%5C:57+2024-09-13T18%5C%5C:05%5C%5C:57%22,%22originalTimeRangeForExploreUrl%22:%22now+1-d%22,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22programming%22%7D%5D%7D%7D,%22keywordType%22:%22ENTITY%22,%22metric%22:%5B%22TOP%22,%22RISING%22%5D,%22trendinessSettings%22:%7B%22compareTime%22:%222024-09-11T18%5C%5C:05%5C%5C:57+2024-09-12T18%5C%5C:05%5C%5C:57%22%7D,%22requestOptions%22:%7B%22property%22:%22%22,%22backend%22:%22CM%22,%22category%22:0%7D,%22language%22:%22en%22,%22userCountryCode%22:%22CA%22,%22userConfig%22:%7B%22userType%22:%22USER_TYPE_LEGIT_USER%22%7D%7D&token=APP6_UEAAAAAZuXQhcOGUPuW6AsOipJBkyUfkQjfuYgk"

queries_url = f"https://trends.google.com/trends/api/widgetdata/relatedsearches?hl=en-US&tz=240&req=%7B%22restriction%22:%7B%22geo%22:%7B%22country%22:%22CA%22%7D,%22time%22:%222024-09-12T18%5C%5C:05%5C%5C:57+2024-09-13T18%5C%5C:05%5C%5C:57%22,%22originalTimeRangeForExploreUrl%22:%22now+1-d%22,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22programming%22%7D%5D%7D%7D,%22keywordType%22:%22QUERY%22,%22metric%22:%5B%22TOP%22,%22RISING%22%5D,%22trendinessSettings%22:%7B%22compareTime%22:%222024-09-11T18%5C%5C:05%5C%5C:57+2024-09-12T18%5C%5C:05%5C%5C:57%22%7D,%22requestOptions%22:%7B%22property%22:%22%22,%22backend%22:%22CM%22,%22category%22:0%7D,%22language%22:%22en%22,%22userCountryCode%22:%22CA%22,%22userConfig%22:%7B%22userType%22:%22USER_TYPE_LEGIT_USER%22%7D%7D&token=APP6_UEAAAAAZuXQhdFr9kwhcYtatVcsQ2f0ELPYNdUo"

# Get the data from the API URLs
topics_response = httpx.get(url=topics_url)
queries_response = httpx.get(url=queries_url)

# Remove the extra symbols and add the data into JSON objects
topics_data = json.loads(topics_response.text.replace(")]}',", ""))
queries_data = json.loads(queries_response.text.replace(")]}',", ""))

result = []

# Prase the topics data and the data into the result list
for topic in topics_data["default"]["rankedList"][1]["rankedKeyword"]:
    topic_object = {
        "Title": topic["topic"]["title"],
        "Search Volume": topic["value"],
        "Link": "https://trends.google.com/" + topic["link"],
        "Geo Location": geo_location,
        "Type": "search_topic",
    }
    result.append(topic_object)

# Prase the querires data and the data into the result list
for query in queries_data["default"]["rankedList"][1]["rankedKeyword"]:
    query_object = {
        "Title": query["query"],
        "Search Volume": query["value"],
        "Link": "https://trends.google.com/" + query["link"],
        "Geo Location": geo_location,
        "Type": "search_query",
    }
    result.append(query_object)

print(result)

# Create a Pandas dataframe and save the data into CSV
df = pd.DataFrame(result)
df.to_csv("keywords.csv", index=False)
```
