### ISSUE TITLE
Data Not Complete / ReadTimeout error

### ISSUE THREAD

**Issue by nicktba** [GeneralMills/pytrends#581]
Getting the error `HTTPSConnectionPool(host='trends.google.com', port=443): Read timed out.` when running the script for Interest over time. 

If data is produced it is incomplete and only shows a few data points. 

Is anyone else getting this error?

**Comment by nicktba** [comment]
If data is produced is very low quality and often is littered with "0" and occurring spikes to 100.

**Comment by aliamrabdalla** [comment]
Yes I am receiving this error continuously too. Does anyone have a solution ?

**Comment by nicktba** [comment]
Looks like the SERPAPI is also facing this issue.

(https://github.com/serpapi/public-roadmap/issues/887
)

**Comment by igalci** [comment]
Seems like a Google bug because the embed feature is also not working well:

![image](https://github.com/GeneralMills/pytrends/assets/70971657/21c90243-f3e3-4721-9771-1014c9f90172)

**Comment by StevenACanon** [comment]
Getting this issue constantly now, any resolution?

**Comment by Terseus** [comment]
Read timeouts can be a problem in Google servers, a problem in your connection, or a bug; in the latter case it would be **much** more prevalent, so I'm inclined it's one of the two first options, both of them are out of our control.
