### ISSUE TITLE
Data on google trends ui is not reflected by pytrends api

### ISSUE THREAD

**Issue by TomasJavurek** [GeneralMills/pytrends#582]
google trends:
![image](https://github.com/GeneralMills/pytrends/assets/33832672/f8e1edd3-df28-4d18-a6e0-fd452d4a7f4d)

pytrends:
![image](https://github.com/GeneralMills/pytrends/assets/33832672/31f27a88-4098-471d-ad89-8454be9a1eb7)

the code for pytrends:
`pytrend.build_payload(kw_list=["zen"], geo="US", timeframe='today 1-m')
df = pytrend.interest_over_time()
df.plot()
`

**Comment by DUOLabs333** [comment]
Yes, I've been noticing the same problem, especially more frequently. I'm also running into timeout issues.

**Comment by Terseus** [comment]
This is a known issue, see https://github.com/GeneralMills/pytrends/issues/577, https://github.com/GeneralMills/pytrends/issues/550 and https://github.com/GeneralMills/pytrends/issues/534.
