### ISSUE TITLE
Pytrends Data Inconsistencies 

### ISSUE THREAD

**Issue by paulwarb** [GeneralMills/pytrends#585]
I've noticed a few people have mention the data from the Pytrends package is inconsistent with Google Trends site. This can be found #577 and #550 and #534.

What percentage of Pytrends results are wrong? Are there any solutions known?

Issues look like this. 

![image](https://github.com/GeneralMills/pytrends/assets/95624080/f3016f08-cd95-430e-aaf3-21d870d1a2fa)

![image](https://github.com/GeneralMills/pytrends/assets/95624080/2382fb8b-9ef4-4f6c-b219-9164c3840bbb)

**Comment by Terseus** [comment]
> I've noticed a few people have mention the data from the Pytrends package is inconsistent with Google Trends site. This can be found #577 and #550 and #534.

Yup, it's a known problem from Google Trends API. 


> What percentage of Pytrends results are wrong?

There's no way to know except what you did: compare the results with the web. 

In our experience the more recent are the results, more holes are in it and more different from the "real" results tend to be. 


> Are there any solutions known?

Unfortunately no.
