### ISSUE TITLE
Interest by Subregion , cid?

### ISSUE THREAD

**Issue by Nzteb** [GeneralMills/pytrends#60]
Hi,

first of all thank you for this beautiful and efficient script.

For a research project Iam interested in using the Google Trends function 'interest by subregion' automatically and iam curious if I could use a modified version of pytrends to receive the desired functionality.

For example if one enters the term 'Python' on the main page and sets the country to 'United Kingdom',  below the 'interest over time' - graph (which is accesable by the 'trends' function) there is a map and I need to be able to grap the corresponding data, which is also available as csv, automatically.

To modify pytrends my first idea is to use the existing 'trends' function as a framework of which the core change should be to correct _payload['cid'] = '**TIMESERIES_GRAPH_0**'_  to the value that correspondents to the json of the 'interest by subregion' data. I tried to find that value for 'cid' with the developer console of Chrome by observing the get and respond calls of Google Trends , yet I was not able to find it.

(To that end Iam looking for the link that goes like: _https://www.google.com/trends/fetchComponent?hl=en-US&q=Python&geo=US&cid=**--WhichValueHere--**_  and points to the 'interest by region' data. )

It would be very helpful if you could point out the correct value for the 'cid' key or if you showed me where I can find it.

Otherwise I would be very happy to hear about a different/better approach to get to the json (or csv) of the 'interest by subregion' section of Google Trends.

If Iam able to write the code with the desired functionality I would be happy to contribute it to the pytrends project.

Your help is much appreciated!

Regards

**Comment by Nzteb** [comment]
It turns out that one must only change the cid value to 'cid=GEO_MAP_0_0' to get to the 'interest by region' data. Iam still struggling with #45 but after that I will try to augment the script.

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.
