### ISSUE TITLE
Reach Quota Limit

### ISSUE THREAD

**Issue by zhangjinge588** [GeneralMills/pytrends#61]
Hi, when I was trying to call trend(payload) function on over 45 different pairs of keywords, the program keeps return "You have reached your quota limit. Please try again later." JSON response after successfully calling 10 times. After doing some research on StackOverflow, it says that enable PREF cookie on google.com would solve the problem. But I don't know how to enable this on python. Could anyone provide some hint or fix that? Thanks!

**Comment by dreyco676** [comment]
Can you link the stackoverflow article?

**Comment by zhangjinge588** [comment]
http://stackoverflow.com/questions/17393969/google-trends-quota-limit

**Comment by zhangjinge588** [comment]
Is it solvable by any chance?

**Comment by dreyco676** [comment]
This is already being done with Requests.Session(). You are probably hitting the 10/min rate limit. Space your requests you can do the following:

```
import time

# connect to Google
pytrend = TrendReq(google_username, google_password, custom_useragent='My Pytrends Script')
for payload in list_of_payloads:
    # trend
    trend = pytrend.trend(trend_payload)
    print(trend)
    time.sleep(6)
```
