### ISSUE TITLE
Google start to Blocking again???

### ISSUE THREAD

**Issue by GodHad** [GeneralMills/pytrends#633]
Hi, everyone. 
My python code was working well but not get too many requests error. Does this means Google start to block again?
How to fix this issues? I am using this on Laravel.                                                                                                                                                Is there any good way to use other method?

**Comment by RalfKellner** [comment]
Just experienced multiple 429 request errors today as well for requests that worked until last week, I hope this is not permanent.

**Comment by GodHad** [comment]
Isn't there any other better way? This is very urgent. The code is working on live site and that is stopped to working.

**Comment by RalfKellner** [comment]
As far as I know, no. Google Trends does not offer an official API and everyone scrapes it as long as they change their request policy.

**Comment by GodHad** [comment]
Thank you for updating. 
Did you just check your code is working? I am wondering that is because of IP.

**Comment by RalfKellner** [comment]
No, I don't think it is the IP. I changed it without any impact. Currently, I am trying some workarounds from older issues. For instance, increasing the number of retries helped to derive a few requests, however, not for long. Many older issues include descriptions to use header information and similar things. Maybe this can help currently as well.

**Comment by zhendonginusa** [comment]
I have been experiencing the same error since 11/09. I have tried different laptops, Google accounts, and internet connections. Unfortunately, the block has never been lifted, which is very frustrating.

**Comment by GodHad** [comment]
How about now? I think that is working.

**Comment by zhendonginusa** [comment]
It's still the same error here. I think Google blocks me.
