### ISSUE TITLE
Connect Error

### ISSUE THREAD

**Issue by samemon** [GeneralMills/pytrends#64]
Hi,

I am trying to use the example.py code, but it gives me the following error right after the line:
  **pytrend = TrendReq(google_username, google_password, custom_useragent='My Pytrends Script')**

Here's the error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pytrends/request.py", line 34, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/pytrends/request.py", line 45, in _connect
    soup_login = BeautifulSoup(login_html.content, "lxml").find('form').find_all('input')
  File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

Do you happen to see what the problem is? I have tried to install lxml and it's just fine.
Thanks.

**Comment by dreyco676** [comment]
Yes, `lxml` parser is a requirement per the docs.

**Comment by dreyco676** [comment]
Do you have an old version of lxml?

**Comment by dreyco676** [comment]
I'm closing this due to it being a configuration issue with dependencies and not the Pytrends package. Hopefully the stackoverflow article addresses it.

**Comment by unnir** [comment]
have the same issue, 
stack didn't help, I'm using anaconda python 3.5 on MacOS.
