### ISSUE TITLE
RateLimitError

### ISSUE THREAD

**Issue by sarahjohns** [GeneralMills/pytrends#66]
Hi!

Thank you for the updates of the code. I tried to run the new updated version. After about 10 downloads, I receive the following traceback:

Traceback (most recent call last):
  File "C:/Users/Documents/Python Scripts/collect_gtrends.py", line 34, in <module>
    trend=pytrend.trend(trend_payload, return_type='dataframe')
  File "C:\Users\AppData\Roaming\Python\Python27\site-packages\pytrends\request.py", line 62, in trend
    raise RateLimitError
pytrends.request.RateLimitError

I don't think this is the quota limit problem. Maybe I was downloading too frequently? How may seconds do you guys wait in between requests? My current program lets it sleep for 5-10 seconds. Is that not enough? Thank you!

**Comment by sarahjohns** [comment]
Actually, I tried again, now it gives the same traceback plus the following message:
Exceeded Google's Rate Limit. Please use time.sleep() to space requests.

I was using your old version of pytrends several months back. During that time, letting it sleep for 5-10 seconds worked well for me. Has Google increased the limit recently? If you know what the limit is, it would be very helpful for me. Thank you!

**Comment by dreyco676** [comment]
I've been successful with 6 seconds. I think they allow 10/min

**Comment by sarahjohns** [comment]
How many requests do you generally have? I remember that it used to be 1500 downloads per 24 hrs. Now it seems to be much lower. How many requests are you able to download with the 6 seconds wait in between? Thank you!

**Comment by sarahjohns** [comment]
I still experience the RateLimitError after 10 downloads even when I put time.sleep(30). One of the previous posts mentioned that they needed a cookie in the browser called PREF. Do you know how to add it? I could not figure out a way to add it... I would really appreciate it if you could help me figure out this issue.

**Comment by dreyco676** [comment]
And you are for sure logged into your Gmail account? I'm able to chug along
at 10/min. I've put it a loop to see how long I can keep going.

**Comment by sarahjohns** [comment]
I have a loop that goes down a list of inputs. Is it important that I call TrendReq(google_username, google_password, custom_useragent=None) inside the loop, i.e., before every request?

**Comment by dreyco676** [comment]
No I don't think you would need to relogin each time. I just tested as was
able to run 200 requests spaced at 10/min but then it finally gave me the
error.

```

# connect to Google
pytrend = TrendReq(google_username, google_password,
custom_useragent='My Pytrends Script')

trend_payload = {'q': 'Pizza, Italian, Spaghetti, Breadsticks,
Sausage', 'cat': '0-71'}

i = 1
while i <= 3000:
    # trend
    trend = pytrend.trend(trend_payload)
    #print(trend)
    print(i)
    time.sleep(6)
    i += 1

```

**Comment by dreyco676** [comment]
No I don't think you would need to relogin each time. I just tested as was
able to run 203 requests spaced at 10/min but then it finally gave me the
error. So if I had to guess its probably 10/min, 200/hr.


```
# connect to Google
pytrend = TrendReq(google_username, google_password,
custom_useragent='My Pytrends Script')

trend_payload = {'q': 'Pizza, Italian, Spaghetti, Breadsticks, Sausage', 'cat': '0-71'}

i = 1
while i <= 3000:
    # trend
    trend = pytrend.trend(trend_payload)
    #print(trend)
    print(i)
    time.sleep(6)
    i += 1
```

**Comment by sarahjohns** [comment]
I see. Thank you a lot!

**Comment by senielee** [comment]
I used time.sleep(randint(20, 30)) and I got Rate Limit error after 10 request. That seems weird or google change the rate limit again?

**Comment by urataj** [comment]
I've found that I'm limited to 12 requests per hour.
However, for some time this morning I've received the following response:
Response did not parse. See server response for details. Sorry, our systems are a little stressed out right now and need to take a deep breath. Please try again in a few moments.

**Comment by cdshinde** [comment]
Yes, I too saw this response, when I was trying to run the "https://www.google.com/trends/fetchComponent" URL with its required query parameters from the browser.  Though it was working normally from the Google Trends URL, for the same URL/IP combination.

**Comment by paulwohlfarth** [comment]
I'm receiving the same error, funnily enough when scraping the data only. I could still download reports manually without issues even after I hit a suspected rate limit. I also agree with urataj, the rate limit, if that's what's causing this, must be much lower than 200/hr. Could there be some 24hr limit as well? I've also noticed that some of the data seems to be compromised. By that I don't mean the occasional sampling error but large parts of the data having zero values or being otherwise completely spurious.

**Comment by dreyco676** [comment]
I'm guessing that the library has a bug that is not correctly passing the session/cookies to google and hits an extremely low rate limit. I will look into it when I've got time. Until then if this is a showstopper check out a version before v3.0 it has a clunkier method to get the data.

**Comment by paulwohlfarth** [comment]
For all I know it is a showstopper for now as the URL used to scrape has changed completely. There is now a token added to the end, which looks very much like the session id's used in the developer platform for the official google api's (at least that's the way it works for maps apparently). And I believe this token hasn't been there before. I wonder if this means that we might get an official trends api soon though? I believe it was planned originally but pretty much forgotten for years. Let's hope the guys at google caught up with that now.

**Comment by gmlee7** [comment]
I have been struggling for two days on the rate limit. I should have read this thread before starting. I also found that the rate limit is very low: After 12 calls (with 30-second intervals), I got a rate limit error. I wish Google supports official API soon...

**Comment by colincolinkn** [comment]
Getting this error again... Can you help us to solve it soon? Thanks!
Response did not parse. See server response for details.

**Comment by patrickongwong** [comment]
Getting similar error...

**Comment by Michelangelo1994** [comment]
Hi, I have a similar problem here. Can anyone help us out to resolve this issue? Thanks.

**Comment by dreyco676** [comment]
I spent some time investigating today. It looks like they changed the API and perhaps throttled the old one.

https://www.google.com/trends/api/widgetdata/multiline?

It looks like it has a ton more parameters that I'll have to wade through but hopefully using that I can resolve this.

**Comment by dreyco676** [comment]
Here is the URL for getting CSV's directly for Pizza & Bagel

https://www.google.com/trends/api/widgetdata/multiline/csv?req=%7B%22time%22%3A%222012-01-24%202017-01-24%22%2C%22resolution%22%3A%22WEEK%22%2C%22locale%22%3A%22en-US%22%2C%22comparisonItem%22%3A%5B%7B%22geo%22%3A%7B%7D%2C%22complexKeywordsRestriction%22%3A%7B%22keyword%22%3A%5B%7B%22type%22%3A%22BROAD%22%2C%22value%22%3A%22pizza%22%7D%5D%7D%7D%2C%7B%22geo%22%3A%7B%7D%2C%22complexKeywordsRestriction%22%3A%7B%22keyword%22%3A%5B%7B%22type%22%3A%22BROAD%22%2C%22value%22%3A%22bagel%22%7D%5D%7D%7D%5D%2C%22requestOptions%22%3A%7B%22property%22%3A%22%22%2C%22backend%22%3A%22IZG%22%2C%22category%22%3A0%7D%7D&token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&tz=360

**Comment by dreyco676** [comment]
URL decodes to:

https://www.google.com/trends/api/widgetdata/multiline/csv?req={"time":"2012-01-24 2017-01-24","resolution":"WEEK","locale":"en-US","comparisonItem":[{"geo":{},"complexKeywordsRestriction":{"keyword":[{"type":"BROAD","value":"pizza"}]}},{"geo":{},"complexKeywordsRestriction":{"keyword":[{"type":"BROAD","value":"bagel"}]}}],"requestOptions":{"property":"","backend":"IZG","category":0}}&token=XXXXXXXXXXXXXXX&tz=360

**Comment by dreyco676** [comment]
Looks like you can maybe get the the Token from 

`https://www.google.com/trends/api/explore?hl=en-US&tz=360&req=%7B%22comparisonItem%22:%5B%7B%22keyword%22:%22pizza%22,%22geo%22:%22%22,%22time%22:%22today+5-y%22%7D,%7B%22keyword%22:%22bagel%22,%22geo%22:%22%22,%22time%22:%22today+5-y%22%7D%5D,%22category%22:0,%22property%22:%22%22%7D&tz=360`

which decodes to
```
https://www.google.com/trends/api/explore?hl=en-US&tz=360&req=
{
   "comparisonItem":[
      {
         "keyword":"pizza",
         "geo":"",
         "time":"today 5-y"
      },
      {
         "keyword":"bagel",
         "geo":"",
         "time":"today 5-y"
      }
   ],
   "category":0,
   "property":""
}
&tz=360
```

**Comment by dreyco676** [comment]
I'm able to pull back data this way but it is not a trivial fix and will take some time.

**Comment by cwallac** [comment]
@dreyco676 absolutely fantastic, thanks for discovering that.

**Comment by dreyco676** [comment]
In case people are curious as to how I'm doing this. I'm using Fiddler to inspect the web requests that go across when using my browser. From there its all about making PyTrends mimic those requests.

**Comment by jiby91** [comment]
**@dreyco676**  Awesome !!! Thanks a lot.

**Comment by jiby91** [comment]
@dreyco676 How did you get the url where I can find the token ? I would like to select a specific country.

**Comment by dreyco676** [comment]
[Fiddler](http://www.telerik.com/fiddler) Just look for a URL that starts with `https://www.google.com/trends/api/explore?hl=en-US&tz=360`

You can specify the country with the `geo` param.

**Comment by dreyco676** [comment]
Alright I was able to test that I have request limit that is in the 100's. I will close this issue as it will be fixed in the next release.
