### ISSUE TITLE
search for category only

### ISSUE THREAD

**Issue by ylelkes** [GeneralMills/pytrends#72]
Would it be possible to get results without keywords, but only within a designated category? For instance, to get these results (within the arts and entertainment category):
https://www.google.com/trends/explore?cat=3&date=2014-01-01%202014-12-31&geo=GB

**Comment by dreyco676** [comment]
Hmm this might be possible in the new version. Let me know if its a continued want and I'll look into it.

**Comment by ericross2** [comment]
I apologize for commenting on a closed issue, but like ylelkes I would be interested in getting results over a time period for specific categories with no/all keywords. I can get a result with a manual Google Trends search on their site and it appears the API removes the q parameter entirely (just as ylelkes shows above). I've played with the keyword parameter of the payload all day -- leaving it blank, empty quotes, asterix, asterix in unicode, 'a or b or c...' etc., removing q entirely -- but I can't figure it out. When I do run pytrends using empty quotes, etc. it gives me a resulting array of small positive and negative numbers (+5, -1, 0, etc.). Would you have a chance to look at this? Thank you.
