### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by icharalamp** [GeneralMills/pytrends#75]
The installation process return that:

Failed building wheel for lxml
.....

.....
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\ioannis\appdata\local\temp\pip-build-l7gi7l\lxml\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\ioannis\appdata\local\temp\pip-lhokac-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\ioannis\appdata\local\temp\pip-build-l7gi7l\lxml\

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.
