### ISSUE TITLE
hottrendsdetail parameters

### ISSUE THREAD

**Issue by magdalena90** [GeneralMills/pytrends#78]
Hi,

When running the function hottrendsdetail on python 2.7 no matter which country I select it always returns the US results.

Following the code in example.py, here's what I am doing:
```
country_payload = {'geo': 'MX'}
hotTrendsDetail = pytrends.hottrendsdetail(country_payload)
```

And here's the link I extract from the first result, from where I realised this belongs to the US hottrends:
http://www.google.com/trends/hottrends?pn=p1#a=20161108-polls

Thank you

**Comment by magdalena90** [comment]
I just figured out what wasn't working: the country_payload has a different format than the one used in example.py, the key is 'pn' instead of 'geo' and I got the value from inspecting the google trends url when selecting the country I wanted (for Mexico is p21).

So running:
country_payload = {'pn':'p21}
hotTrendsDetail = pytrends.hottrendsdetail(country_payload)

I finally got Mexico's hot trends

**Comment by candoz** [comment]
Awesome, thanks for the advice.
I've never used the 'hottrend' functionality before, so I never had this problem (for normal requests the correct payload is still 'geo').
Unfortunately Google changes those payloads from time to time (also the 'cat' codes in the example.py seems to be outdated), so from time to time it's better to test manually which are the correct payloads on the browser address bar, and then adjust the ones inside your pytrend script accordingly.

**Comment by magdalena90** [comment]
Thanks! I will do this from now on

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.
