### ISSUE TITLE
 payload['cid'] = 'TIMESERIES_GRAPH_0' TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by sv1478** [GeneralMills/pytrends#79]
Hi,

I new to python but was encountering an issue
 payload['cid'] = 'TIMESERIES_GRAPH_0'
TypeError: 'str' object does not support item assignment

I have attached my code. i am trying to arguments from the command line and use them to get the trends

[poetgoogletrends.txt](https://github.com/GeneralMills/pytrends/files/579522/poetgoogletrends.txt)

**Comment by dreyco676** [comment]
Umm you might want to uh... edit that script you have up.

That said you are constructing the payload as a string. You shouldn't need to include the extra quotes. If arg1 = 'somecoolthing' you should be able to do payload['cid]=arg1.
