### ISSUE TITLE
Can we have support date format having day in it?

### ISSUE THREAD

**Issue by cdshinde** [GeneralMills/pytrends#80]
Currently "trend" API uses multiple custom date formats
One of them is {'date': 'MM/YYYY #m'} and there are many more..
If I wanted to also pass an exact date in the past to get data between say 10/02/2016 and 04/03/2016 I don't think there is any method that can support it. Could you make changes in the API so that it can support the "day" parameter too?
Or please can you guide me how to get achieve this, if I have missed this.

Thanks in advance.

**Comment by candoz** [comment]
I cannot try this at the moment, but I guess you can do something like this:
`payload['date'] = '2016-02-10 2016-03-04'`
Let me know if that solves your problem, otherwise I'll do some tests when I get home.

**Comment by cdshinde** [comment]
So you meant something like this

**Comment by candoz** [comment]
Yep

**Comment by cdshinde** [comment]
Then that did not work.

**Comment by candoz** [comment]
Ok, I tried it and apparently it doesn't work.
I only used this api for months-data (so I've never faced this specific problem), but now I'm curious to know if there's a way to do what you're asking for. Cheers

**Comment by dreyco676** [comment]
This is supported in the upcoming version, stay tuned.
