### ISSUE TITLE
Daily Data / Not from "today"

### ISSUE THREAD

**Issue by antoinefranz** [GeneralMills/pytrends#82]
Hello,

I would like to get daily data from every day of a month.
I use {'date': 'today #-d'} but instead of today I want to write something like "2011/10/08" or "2011-10-08" or ...
It doesn't work.

Do you have any idea of a solution to get daily data from a month ?

Thank you in advance for your help.

**Comment by candoz** [comment]
Directly from the README file:

> Custom Timeframe Pattern:
> 
>  By Month: {'date': 'MM/YYYY #m'} 
>  where # is the number of months from that date to pull data for
> 
> For example: {'date': '10/2009 61m'} would get data from October 2009 to October 2014
> -> Less than 4 months will return Daily level data
> -> More than 36 months will return monthly level data
> -> 4-36 months will return weekly level data

So, if I correctly understood your problem, if you want all the daily data for May 2006:

`{'date': '05/2006 1m'}`

**Comment by jiby91** [comment]
Hi, 
I think this might help you.
https://github.com/jiby91/Daily-GoogleTrends-Data

**Comment by dreyco676** [comment]
This type of workflow is supported in the upcoming version.
