### ISSUE TITLE
Hourly timestamps in Pandas dataframe are broken

### ISSUE THREAD

**Issue by rubenvereecken** [GeneralMills/pytrends#84]
While I was trying out the API I wanted to get the trends for a specific topic for the last 7 days, resulting in hourly data. Using the default json return type everything looked well (pay attention to the timestamps):

```
> t.trend({'q':'...', 'date': 'today 7-d'})
...
'rows': [{'c': [{'f': 'Nov 6, 2016, 16:00 PST', 'v': '2016-11-07'},
     {'f': '59', 'v': 59.0}]},
   {'c': [{'f': 'Nov 6, 2016, 17:00 PST', 'v': '2016-11-07'},
     {'f': '62', 'v': 62.0}]},
   {'c': [{'f': 'Nov 6, 2016, 18:00 PST', 'v': '2016-11-07'},
...
```

Trying the equivalent with a Pandas dataframe as output resulted in the hourly timestamps to all be equal per day, just cut off. I'm guessing this is due to incorrect expectations of daily data or something:

```
> dp = t.trend({'q':'...', 'date': 'today 7-d'}, 'dataframe')
> dp.index[0]
Out: Timestamp('2016-11-07 00:00:00')
> dp.index[1]
Out: Timestamp('2016-11-07 00:00:00')
```

**Comment by dreyco676** [comment]
The new google API uses seconds since the epoch so I think this is now solved in the new version released, let me know if this is a continued issue by reopening.
