### ISSUE TITLE
Wouldn't it make more sense to use Pandas Series objects instead of DataFrames?

### ISSUE THREAD

**Issue by candoz** [GeneralMills/pytrends#86]
Pandas DataFrames are meant for 2-dimensional data, whilst Pandas Series are for 1-dimensional data. (http://pandas.pydata.org/pandas-docs/stable/dsintro.html)
Since a Trend is 1-dimensional, I think it would make more sense to use Pandas Series with dates as index.
Or maybe I'm missing something?

**Comment by dreyco676** [comment]
Thanks for the interest.

You can search for up to 5 trends at a time and thus would have multiple series. The workflow for many is to extract the data to a CSV and pandas dataframe.to_csv() accomplishes that seemlessly.
