### ISSUE TITLE
search a topic instead of a keyword

### ISSUE THREAD

**Issue by timothy2799** [GeneralMills/pytrends#87]
Is it possible to search for a Topic, instead of a keyword?

Say, I'm searching for 'Pope' as a topic, rather than just the keyword 'pope'. They give so different results from the Google Trends. I try input the code shown in the url '%2Fm%2F05rd8' , but it doesn't work.

Thank you!

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.
