### ISSUE TITLE
Hottrends detail API Not working 

### ISSUE THREAD

**Issue by mycloudyhopes** [GeneralMills/pytrends#88]
I m using this simple script. https://gist.github.com/mycloudyhopes/eac94350b613544a731bf78c4dc76f16
But, all it is doing is returning the  US trends

**Comment by dreyco676** [comment]
Google's API changed new version of PyTrends will be released later this week and this specifically has been resolved.

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.
