### ISSUE TITLE
writing to csv

### ISSUE THREAD

**Issue by Eroizman** [GeneralMills/pytrends#89]
after running the code how to export to csv?

**Comment by candoz** [comment]
I use this method:

```
df = pytrends.trend(payload, return_type='dataframe')
df.to_csv(<YOUR_FILEPATH>)
```

See here for more details about "to_csv()" in official pandas documentation:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html

Bye!
