### ISSUE TITLE
Can't install via pip 

### ISSUE THREAD

**Issue by ovived** [GeneralMills/pytrends#90]
i keep getting an XML error when I try to install via pip.. Any ideas? i'm using windows and have no other issues on other plugins

**Comment by candoz** [comment]
Sorry, I use it on Linux and didn't have any problem... Anyway, have you already tried installing it in a virtual env?

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.

**Comment by maryamtorshizy** [comment]
Hi I still cannot install pytrends
