### ISSUE TITLE
discrepancy on return data set

### ISSUE THREAD

**Issue by uduwage** [GeneralMills/pytrends#91]
I was able to replicate the issue with example code. 

When you set trend_payload to have multiple keywords vs single keyword there is discrepancy in the results. 

Here is the example: I change `example.py` in the repo to reflect following: 

`trend_payload = {'q': 'ebay'}` Once ran with this setting I get following results set: 
[SingleKeyWords.txt](https://github.com/GeneralMills/pytrends/files/640920/SingleKeyWords.txt)

but when include another keyword: `trend_payload = {'q': 'ebay,amazon'}` I get a different results set
[MultipleKeyWords.txt](https://github.com/GeneralMills/pytrends/files/640921/MultipleKeyWords.txt)

It gets worse, if I include four key words, the values have very large discrepancy compare to single keyword. 
`trend_payload = {'q': 'ebay,amazon,walmart,google'}`
[Multiple2.txt](https://github.com/GeneralMills/pytrends/files/640922/Multiple2.txt)
 
Is it due to latest changes in the Google API or lack of sleep time between request therefore google is giving you garbage?

**Comment by candoz** [comment]
There's nothing wrong, it's just the way Google Trends works: it normalizes in the same way all the data for every request, being it a single request or a multiple request.
If you want independently normalized data for four terms you have to make four different requests: one for each term.

**Comment by uduwage** [comment]
I understand 0-100 normalization lets take first few records: 
Date,ebay
2004-01-01,44.0
2004-02-01,44.0
2004-03-01,46.0
2004-04-01,46.0

now with two search terms: 

2004-01-01,17.0,42.0
2004-02-01,16.0,42.0
2004-03-01,16.0,44.0
2004-04-01,15.0,44.0

finally 4 terms.
Date,amazon,ebay,google,walmart
2004-01-01,4.0,11.0,6.0,1.0
2004-02-01,4.0,11.0,6.0,1.0
2004-03-01,4.0,11.0,6.0,1.0
2004-04-01,4.0,11.0,8.0,1.0

keyword ebay drop 10 times... that seems like a strange normalization. Statistically i understand 0-100 normalization. But this is strange. The link only talks about 0-100:
Date,amazon,ebay,google,walmart

[https://support.google.com/trends/answer/4365533?hl=en](https://support.google.com/trends/answer/4365533?hl=en )

**Comment by candoz** [comment]
It didn't "drop" anything; putting it simple, it just means that a lot more people searched for "google" instead of "ebay" over the years (see the peak for google in October 2013).
That 4.0 value just means that in January 2004 the search volume for "ebay" was roughly the 4% of the searches for "google" in October 2013. 
That's all, you don't have to reason in absolute values

**Comment by dreyco676** [comment]
@candoz is correct, its just the way the math works out.
