### ISSUE TITLE
You guys seeing these 'null' values showing up since today ? Jan 10:"Jan 10, 2017, 08:08 PST"},,{"v":null}]

### ISSUE THREAD

**Issue by rcornall** [GeneralMills/pytrends#93]
Im seeing lots of these today:
... "f":"Jan 10, 2017, 08:08 PST"},,{"v":null}] ... 
where the values are just null for the last 9 hours now. It doesnt matter what request I make.
Just wondering if you guys have seen this before at all or what kind of inconsistencies I can expect when working with this unofficial API.

Sorry I know this is not a pytrends issue but I thought i would post here anyways.

**Comment by dreyco676** [comment]
Google changed their API, I will be switching pytrends to the new API but it will take time. I'll keep this open and see if its still any issue after we've switched.

**Comment by rcornall** [comment]
Hey it looks like its working again with the original api?
https://www.google.com/trends/fetchComponent?q=canada%2camerica&date=now%201-d&cid=TIMESERIES_GRAPH_0&export=3

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.
