### ISSUE TITLE
Issue with hl (header language) parameter

### ISSUE THREAD

**Issue by dbensoussan** [GeneralMills/pytrends#99]
Hi, 
First of all, thanks a lot for this update, the rate limit seems to have risen a lot compared to before!

I noticed that the `hl` parameter causes a bug when it's not set to English.
Below is an attempt of `pytrend.interest_over_time()` with `hl='fr-FR'` in the declaration of the pytrend object:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-54-065f2e0afcfd> in <module>()
      3 
      4 # Interest Over Time
----> 5 interest_over_time_df = pytrend.interest_over_time()

C:\Program Files\Anaconda3\lib\site-packages\pytrends\request.py in interest_over_time(self)
    112         over_time_payload = dict()
    113         # convert to string as requests will mangle
--> 114         over_time_payload['req'] = json.dumps(self.interest_over_time_widget['request'])
    115         over_time_payload['token'] = self.interest_over_time_widget['token']
    116         over_time_payload['tz'] = self.tz

AttributeError: 'TrendReq' object has no attribute 'interest_over_time_widget'
```
This probably comes from these lines of code:
`if widget['title'] == 'Interest over time':`
`self.interest_over_time_widget = widget`

I think the widget title string is translated to the `hl` language, hence the error.

**Comment by dreyco676** [comment]
Hmm. I guess that makes sense. I'll have to take a look to verify. 

Does this impact the results in anyway other than ease of use?

**Comment by dbensoussan** [comment]
This is pure ease of use.
It is meant to translate a topic to any language (but has no effect on exact term searches).

For example, the FIFA World Cup topic code is `/m/030q7`.
On the Google Trends website, this payload `q=/m/030q7&hl=fr-FR` will return the result in French: FIFA World Cup becoming _Coupe du monde de football_.

Doing some more tests I just ran on another issue (maybe indirectly related to the first one):

When using a topic code as a keyword, for instance:
`pytrend.build_payload(kw_list=['/m/030q7'], timeframe='today 1-m', cat=0, geo='FR')`
`interest_over_time_df = pytrend.interest_over_time()`

The column name of the returned dataFrame is the topic code instead of its translation into words.
Please note that this was not an issue in the previous version of pytrends, maybe it'll help you finding where the bug comes from.

Thanks for your help!

**Comment by dreyco676** [comment]
Yea, the second issue is they don't label the returned data set until it gets rendered in a chart, so pytrends uses the input from the user, otherwise it would be 0,1,2,3,4 for column names.

**Comment by kritideep** [comment]
Hey everyone I came to fault here this code bcz whenever scarps the trending news then results come out in the us region not as india. And I want the result the India region not the us.. Please updated as soon as possible.. Thanks all of guys

**Comment by dreyco676** [comment]
@dbensoussan I'm going to remove the `hl` parameter since I can't support parsing all the languages available. The data should remain the same but the headers will be in English. I will open another issue for the second thing you pointed out.
